### ISSUE TITLE
Error Object of class CURLFile could not be converted to string

### ISSUE THREAD

**Issue by ricoxor** [mgp25/Snap-API#1]
Here is the PHP code that I am running.

``` php
$snapchat = new Snapchat('account', 'm198sOkJEn37DjqZ32lpRu76xmw288xSQ9', FALSE);
$snapchat->login('account', 'password');
$id = $snapchat->upload(
    Snapchat::MEDIA_IMAGE,
    file_get_contents($picture_url)
);
$snapchat->setStory($id, 10, 'lol');
```

The result is `( ! ) Catchable fatal error: Object of class CURLFile could not be converted to string in C:\wamp\www\Snap-API-master\src\snapchat_agent.php on line 305`

**Comment by mgp25** [comment]
@ricoxor the code should be like this:

``` php
$snapchat = new Snapchat($username, $auth_token, $debug);
$snapchat->login($username, $password);

$path = "/Users/mgp25/Desktop/test.jpg"; // path to image or video

$snapchat->setStory($path, 10, 'lol');
```

That will work, i made some changes in the api to make easier scripts. If you have any doubt, just tell me.

Regards

**Comment by ricoxor** [comment]
Thank's that work but there is notices. 
http://gyazo.com/ceee491c8065a39b99a350b3e75b57df

Why we need to set the $auth_token ? It is in the snapchat_agent.php :/

**Comment by mgp25** [comment]
@ricoxor i have to fix and improve the code yet, remember you need to have curl installed. I'll be updating the code in my spare time, if you find anything you can send your pull requests too.

Regards
