### ISSUE TITLE
Gmail login info

### ISSUE THREAD

**Issue by EricZeiberg** [mgp25/Snap-API#106]
Why does this require gmail login information? Can it work with just username and password?

**Comment by teknogeek** [comment]
no, it requires gmail login info. the login requires an encrypted google
password (generated by encrypter.jar) to get a valid bearer for the header

**Comment by EricZeiberg** [comment]
Do you have to own both accounts, or can you use your gmail logins and log into someone else's snapchat?

**Comment by teknogeek** [comment]
the combination is irrelevant as long as both are valid

**Comment by EricZeiberg** [comment]
Alright, thanks Joel

**Comment by teknogeek** [comment]
yessir

**Comment by ferdau** [comment]
Small question following this `issue`: 

``` php
exec("java -jar " . __DIR__ . "/encrypter.jar $this->gEmail $this->gPasswd", $result);
var_dump($result);
```

Result is always NULL (even with success), but when I replace this code and just simply put NULL it doesn't work, what is happening with this variable?
