### ISSUE TITLE
Allow setStory to take object as parameters(?)

### ISSUE THREAD

**Issue by jkaberg** [mgp25/Snap-API#117]
This is spawned from my orginal idea over here, https://github.com/mgp25/Snap-API/issues/73

What I want to achieve is an automated bot that receives snaps and re-posts them on its story directly

My basic code wich I want to achieve this with is;

```
$snapchat = new Snapchat($username, $gEmail, $gPasswd, $debug);
$snapchat->login($password);

$snaps = $snapchat->getSnaps();

if (!is_null($snaps))
{
    foreach($snaps as $snap)
        //echo $snap->id;
        $snapchat->setStory($snapchat->getMedia($snap->id), $snap->time);
        $snapchat->markSnapViewed($snap->id);
}

$snapchat->closeAppEvent();
```

Now obviously this fails as setStory() only handles file objects. So with that in mind I'm requesting support for the above :-) (I hope you get what I mean)

PS: It fails with the following msg:

```
PHP Warning:  finfo_file(▒▒▒▒): failed to open stream: No such file or directory in /opt/Snap-API/src/snapchat.php on line 2179
PHP Warning:  file_get_contents() expects parameter 1 to be a valid path, string given in /opt/Snap-API/src/snapchat.php on line 2196
PHP Notice:  Undefined variable: type in /opt/Snap-API/src/snapchat.php on line 2226
```

**Comment by jkaberg** [comment]
Oh and btw, how does one mark a snap as "viewed" so that above wont post the snap to story again?

EDIT, using:

```
$snapchat->markSnapViewed($snap->id);
```

:smiley:

**Comment by jkaberg** [comment]
Ok so I solved this without doing it the way I intended to, perhaps people might be interested in the final piece

```
// Login

$tmpPath = '/tmp/';
$snapchat = new Snapchat($username, $gEmail, $gPasswd, $debug);
$snapchat->login($password);

$snaps = $snapchat->getSnaps();

if (!is_null($snaps))
{
    //print_r($snaps);
    foreach($snaps as $snap) 
    {
        echo "Processing " . $snap->id . "\n";
        $tmpFilePath = $tmpPath . $snap->id;

        file_put_contents($tmpFilePath, $snapchat->getMedia($snap->id));
        $snapchat->setStory($tmpFilePath, $snap->time);
        $snapchat->markSnapViewed($snap->id);
        unlink($tmpFilePath);
    }
}

$snapchat->closeAppEvent();
```

I'm running the above with a random intervall crontab like so,

```
2 * * * * sleep ${RANDOM:0:3}m ; php /opt/bot/bot.php >/dev/null 2>&1
```

(you may close this now)

**Comment by jkaberg** [comment]
@mgp25 

I'd like to make use of 

```
auth-<username>.dat
```

Would you mind giving me an example on how I can do that? I understand that I need to make use of

```
$snapchat->openAppEvent();
```

The wiki nor examples gives much details into this

(if you'd like you can use the code above as reference)

**Comment by mgp25** [comment]
@jkaberg we have to fix that, because the lasts commits broke the reuse of the auth

**Comment by jkaberg** [comment]
@mgp25 yes, I see

But once your done fixing it, would you mind giving an example on how to use it? (like an example bot?)

**Comment by sallaben** [comment]
http://www.github.com/sallaben/storybot PLEASE help me out with this.. I'm
willing to rewrite the entire thing with you but I already have a dedicated
community and several accounts with thousands of followers to test this on.

**Comment by sallaben** [comment]
Basically I've done what you're trying to do already, although pretty
sloppily. I would like you to help me make it better! Thanks :)

**Comment by jkaberg** [comment]
@sallaben This script does that, 

https://github.com/mgp25/Snap-API/issues/117#issuecomment-99879561
