### ISSUE TITLE
Login doesn't seem to work

### ISSUE THREAD

**Issue by CptCarbonat** [mgp25/Snap-API#118]
I'm trying to use this API, but I have an Issue. When I try to login, there is no error, but then when I try to send something like `$snapchat->sendMessage('xxx', 'Hello World!');`, it says `Warning:  Invalid argument supplied for foreach() in D:\Programme\xampp\htdocs\snapchat\src\snapchat.php on line 720
You have to add xxx as a friend first!`. 
It seems like the request for an Auth-Token doesn't return anything, but i have actually no idea why it doesn't work. :(

**Comment by ghost** [comment]
You don't have xxx in your contacts.

**Comment by CptCarbonat** [comment]
Yeah sure not, I put in a Username that is in the Contacts of the Account I logged in with. XXX is just a placeholder.

**Comment by btrka** [comment]
I'm getting this also. It seems my account logs in fine, but won't send chat msgs or update story etc.

**Comment by Krupson** [comment]
Same here. Seems like snapchat has changed their API. When trying to log in into my account with $debug = true first request to https://feelinsonice-hrd.appspot.com/loq/device_id returns "Error: UNAUTHORIZED"

**Comment by mgp25** [comment]
@Krupson ip/host blocked try a different one

**Comment by CptCarbonat** [comment]
@mgp25 Do you have an idea why it doesn't work? Did I oversee something? I checked pretty much all the issues other people had to deal with, but didn't find anything that could cause the problem for me.

**Comment by mgp25** [comment]
@CptCarbonat Check your ip/host. Its working. Try with a diff ip

**Comment by CptCarbonat** [comment]
@mgp25  ok, thank you

**Comment by mgp25** [comment]
Check your gmail accounts and remove previously auth.dat. Its working fine :smile:
