### ISSUE TITLE
Here we go again

### ISSUE THREAD

**Issue by ghost** [mgp25/Snap-API#121]
I'm getting this after updating to v9.7.3.0.

`You're using a version of Snapchat or operating system that's no longer supported. Please upgrade your device's operating system and update to the newest app version to use Snapchat. Thanks!`

Changing user agent does not work :-(

**Comment by jkaberg** [comment]
I'm seeing this aswell @mgp25

**Comment by StevePavlin** [comment]
Waiting for a fix aswell.

**Comment by teknogeek** [comment]
i would appreciate it if you learned how to code tyvm f47effd4751f1352bda86b81e9dce449ed3882fd
