### ISSUE TITLE
Error while testing exampleFunctional.php

### ISSUE THREAD

**Issue by spartanz51** [mgp25/Snap-API#122]
My friends: 

```
Warning: Invalid argument supplied for foreach() in /home/rzzhtdwi/public_html/respawn/SnAPI-Chat-master/src/snapchat.php on line 2271

Warning: Invalid argument supplied for foreach() in /home/rzzhtdwi/public_html/respawn/SnAPI-Chat-master/src/snapchat.php on line 720
You have to add username as a friend first!
```

**Comment by mgp25** [comment]
Post debug log

**Comment by spartanz51** [comment]
What's debug log?

**Comment by mgp25** [comment]
@spartanz51 set `$debug` to `true`

**Comment by spartanz51** [comment]
Thanks, i will post (Sorry i'm french)

**Comment by spartanz51** [comment]
http://pastebin.com/W3gf5dC

**Comment by mgp25** [comment]
@spartanz51 make sure you are using a correct gmail account and you snapchat data its ok. If you have used your account in latest snapchat app version, you cant use this API (yet), we have to update the login feature.

You can register a new account using this API meanwhile

Regards

**Comment by spartanz51** [comment]
Thanks !
I'll try
