### ISSUE TITLE
Unable To Login....intermittent response

### ISSUE THREAD

**Issue by iOsMechanic** [mgp25/Snap-API#127]
Im getting this error ....sometimes it goes thru and sometimes i get this error?

`POST /loq/login HTTP/1.1 User-Agent: Snapchat/9.8.1.0 (HTC One; Android 4.4.2#302626.7#19; gzip) Host: feelinsonice-hrd.appspot.com Accept: / Accept-Language: en Accept-Locale: en_US X-Snapchat-Client-Auth-Token: Bearer Advice=auto Accept-Encoding: gzip Content-Length: 6328 Content-Type: application/x-www-form-urlencoded Expect: 100-continue DATA: username=testmac9962&password=masafi123&height=1280&width=720&max_video_height=640&max_video_width=480&dsig=212f4317d73034c21be7&&application_id=com.snapchat.android&req_token=9302d952ddc159b86e1a52e8f7a881245eeb4d84191aea8419b47714dfc51cfb stdClass Object ( [message] => Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :) [status] => -103 [logged] => ) RESULT: 1 {"result":false,"message":"Couldn't login, please try again."}`

**Comment by mgp25** [comment]
@iOsMechanic use the `EncryptedPassword` provided by gmail auth, you need java enabled in order to execute a `.jar`

**Comment by iOsMechanic** [comment]
Well try to explain it as its not a problem fro Jar File cause ive already logged in .

1.When i comment this code then the scripts works for some time 

		if(file_exists(__DIR__ . DIRECTORY_SEPARATOR . self::DATA_FOLDER . DIRECTORY_SEPARATOR . "auth-$this->username.dat")){
			$this->totArray = unserialize(file_get_contents(__DIR__ . DIRECTORY_SEPARATOR . self::DATA_FOLDER . DIRECTORY_SEPARATOR . "auth-$this->username.dat"));
		}
		if(array_key_exists($this->username, $this->totArray[0])){
			$this->auth_token = $this->totArray[0][$this->username];
		}
		if(array_key_exists($this->username, $this->totArray[1])){
			if($this->totArray[1][$this->username][1] > time()) parent::setGAuth($this->totArray[1][$this->username][0]);
				
		}

2.then i get a resonse like

REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id Sent Request info: POST /loq/device_id HTTP/1.1 User-Agent: Snapchat/9.8.1.0 (HTC One; Android 4.4.2#302626.7#19; gzip) Host: feelinsonice-hrd.appspot.com Accept: */* Accept-Language: en Accept-Locale: en_US X-Snapchat-Client-Auth-Token: Bearer Content-Length: 98 Content-Type: application/x-www-form-urlencoded DATA: timestamp=1433315283276&req_token=9309cd5a864156a86e1210e7f3a77d5493e34d8719d00a8f69b4bf14dec5143b RESULT: {"dtoken1i":"00001:xLxxXo/0S2CL5F5O1t4nv0Q9brbnPg5kdl5uGv9bmNirKJ1kwcHC93KbkvWQs3t0","dtoken1v":"tIQgP8Nk2YJ+lazbeL886n+pNGtrApkEFs5U5TxCP5w\u003d"} REQUEST TO: https://android.clients.google.com/auth Array ( [device_country] => us [operatorCountry] => us [lang] => en_US [sdk_version] => 19 [google_play_services_version] => 7097038 [accountType] => HOSTED_OR_GOOGLE [Email] => sameerthehun@gmail.com [service] => audience:server:client_id:694893979329-l59f3phl42et9clpoo296d8raqoljl6p.apps.googleusercontent.com [source] => android [androidId] => 378c184c6070c26c [app] => com.snapchat.android [client_sig] => 49f6badb81d89a9e38d65de76f09355071bd67e7 [callerPkg] => com.snapchat.android [callerSig] => 49f6badb81d89a9e38d65de76f09355071bd67e7 [EncryptedPasswd] => AFcb4KRkszBMAEyNGfK_KST582JyJTxgdK2R_4XJcqIznEbC55H6Jxe9SnvFjVFcRPYwNq5h13yvzT5-_eWBULiwQ4U5GqiegMeDAzfSf_UuOS_Z25Knspwhp2wh_DSy6w6MWXo4XBd7diJFAGjtmwrfAi_IInf1uMGX-znVaGi2iXO4qA== ) DATA: 1 RESULT: Auth=eyJhbGciOiJSUzI1NiIsImtpZCI6ImM2ZjcxM2YwZWVmZWQzODNlMDg4NTc0ZDhlMjVhMjFmNjVlNmUxNmMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwic3ViIjoiMTAxMTc4NjEwNTYwMzIxNzE5MjA0IiwiYXpwIjoiNjk0ODkzOTc5MzI5LXFnMGkwdTg4dDBobThrNmsxbWJyYm5zdWoxMDFoNzN2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJzYW1lZXJ0aGVodW5AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF1ZCI6IjY5NDg5Mzk3OTMyOS1sNTlmM3BobDQyZXQ5Y2xwb28yOTZkOHJhcW9samw2cC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImlhdCI6MTQzMzMxNTI4NCwiZXhwIjoxNDMzMzE4ODg0fQ.4pfl424jG05ZUAvx-PUWe_X-x02CVQTuO98joWDV3fj4ZLVDdzTi-_iVE4XxDgABsyFx0fXbDoifzv3tBeZ3v0xk3zA0bCeXU1JIKPNGcv1fHv2JmtFL2jhmKnbV6sa5Ff4J3GpM6P7HYWAq0RDUJQxsKhNnePtGxfYRcxJw80g issueAdvice=auto Expiry=1433318884 storeConsentRemotely=1 REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/login Sent Request info: POST /loq/login HTTP/1.1 User-Agent: Snapchat/9.8.1.0 (HTC One; Android 4.4.2#302626.7#19; gzip) Host: feelinsonice-hrd.appspot.com Accept: */* Accept-Language: en Accept-Locale: en_US X-Snapchat-Client-Auth-Token: Bearer Advice=auto Accept-Encoding: gzip Content-Length: 6322 Content-Type: application/x-www-form-urlencoded Expect: 100-continue DATA: username=xxxx&password=xxx&height=1280&width=720&max_video_height=640&max_video_width=480&dsig=85328406451da449ce3d&dtoken1i=00001%3AxLxxXo%2F0S2CL5F5O1t4nv0Q9brbnPg5kdl5uGv9bmNirKJ1kwcHC93KbkvWQs3t0&ptoken=ie×tamp=1433315283967&attestation=<very long auth token>&application_id=com.snapchat.android&req_token=93089b5356018c686e1b7ce9f0ad1ac412e74d861948ba8189b41714dac51aab stdClass Object ( [message] => Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :) [status] => -103 [logged] => ) RESULT: 1
