### ISSUE TITLE
Log in problem

### ISSUE THREAD

**Issue by emiliobasualdo** [mgp25/Snap-API#134]
Working until today.
triple checked account username, password, etc
even tried with other accounts.
do you what might be causing it?

REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id

Sent Request info: POST /loq/device_id HTTP/1.1
User-Agent: Snapchat/9.8.0.0 (HTC One; Android 4.4.2#302626.7#19; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: _/_
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer 
Content-Length: 98
Content-Type: application/x-www-form-urlencoded

DATA: timestamp=1434408077987&req_token=930f2255428109586e8497e0f6a4418423ea4d81194bba8d49b43f14dac5183b
RESULT: {"dtoken1i":"00001:UN34c2jrRPePgz6wCaN//g8nGegNApwCIHON68q83KGxjOmvfApL80dORocNyrLt","dtoken1v":"eDFHU+Ja/w6VetxqHEce0ishoFygZBfZpm/tnD4awgQ\u003d"}
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

REQUEST TO: https://android.clients.google.com/auth
Array
(
    [device_country] => us
    [operatorCountry] => us
    [lang] => en_US
    [sdk_version] => 19
    [google_play_services_version] => 7097038
    [accountType] => HOSTED_OR_GOOGLE
    [Email] => gaytomasgay@gmail.com
    [service] => audience:server:client_id:694893979329-l59f3phl42et9clpoo296d8raqoljl6p.apps.googleusercontent.com
    [source] => android
    [androidId] => 378c184c6070c26c
    [app] => com.snapchat.android
    [client_sig] => 49f6badb81d89a9e38d65de76f09355071bd67e7
    [callerPkg] => com.snapchat.android
    [callerSig] => 49f6badb81d89a9e38d65de76f09355071bd67e7
    [EncryptedPasswd] => AFcb4KQoWj4W-0d-eIz55vCfOo8ja0ft19M968mdmVDLcjD_WNLVPJMMlbz_KMCyRaKDA7Ty405_Nfn4abdpoh2iSaO5yhK2uWX32x_ZBj6jiSwccpPlGP9GoQ_C2SgemWRluak6jo88RM51aJfSvDxMtp_fOiWMxOodXVEJWBAu8SyxsQ==
)
DATA: 1
RESULT: Auth=eyJhbGciOiJSUzI1NiIsImtpZCI6IjQyZWJmNWQ2OGI2YzQ3ODQ2YTU1OTM4ZTZmMTY1NzlmYjlhZmJhZTMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwic3ViIjoiMTA4NDU5NDMzNzQyNzg5ODkwNDA3IiwiYXpwIjoiNjk0ODkzOTc5MzI5LXFnMGkwdTg4dDBobThrNmsxbWJyYm5zdWoxMDFoNzN2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJnYXl0b21hc2dheUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiaWF0IjoxNDM0NDA4MDc5LCJleHAiOjE0MzQ0MTE2Nzl9.TYSkProAZQi05ffWG8glJvmzuUzZ1TVB1fanSHLbS423Ucgz1ALgawjgRk2CNQw52U6ZcMoYjheY5X2m6g7Tdh3v1wzba6ptq0PV4hLRINiqN27ErDv9Y4uV2p1T3AIMYYD_YoEYBl8C1WXPvDYALXw11ExrzD-IDhZMUjK3UYHxr63-VaNdGfoQYT805XgLB6ZY5iIihmxgsKg4DhimZqeDOoh8Uf5sHwZVyOTqWJpPlolgbmGlN5Z8Uwpcz3mXmKpYejbggGYmWS7I6w_AVL2UYNpqtFA-_6wYLPJyqhcJKCX_B9266TesaHyzpPADGfCxQzZMXmdMGKx9D8p8ug
issueAdvice=auto
Expiry=1434411679
storeConsentRemotely=1

REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/login

Sent Request info: POST /loq/login HTTP/1.1
User-Agent: Snapchat/9.8.0.0 (HTC One; Android 4.4.2#302626.7#19; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: _/_
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer Advice=auto
Accept-Encoding: gzip
Content-Length: 6327
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue

DATA: username=sanandrestv&password=SaintAndrews&height=1280&width=720&max_video_height=640&max_video_width=480&dsig=8a7d894e0d36b6462397&dtoken1i=00001%3AUN34c2jrRPePgz6wCaN%2F%2Fg8nGegNApwCIHON68q83KGxjOmvfApL80dORocNyrLt&ptoken=ie&timestamp=1434408078473&attestation=eyJhbGciOiJSUzI1NiIsIng1YyI6WyJNSUlFZmpDQ0EyYWdBd0lCQWdJSUpSQWpzN1lXcEE4d0RRWUpLb1pJaHZjTkFRRUZCUUF3U1RFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBb1RDa2R2YjJkc1pTQkpibU14SlRBakJnTlZCQU1USEVkdmIyZHNaU0JKYm5SbGNtNWxkQ0JCZFhSb2IzSnBkSGtnUnpJd0hoY05NVFF3T1RJeU1Ea3dPVEEwV2hjTk1UVXdPVEl5TURrd09UQTBXakJzTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNBd0tRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCd3dOVFc5MWJuUmhhVzRnVm1sbGR6RVRNQkVHQTFVRUNnd0tSMjl2WjJ4bElFbHVZekViTUJrR0ExVUVBd3dTWVhSMFpYTjBMbUZ1WkhKdmFXUXVZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3RFNWUmM5NXBYSytLUWdRNTU4YUpCdUtaa0t2WjVZVWJDZG94ZWZpbHo5STlWRlhHQnhhWjlBaDgvWmg0QU9mSiszdTFOS1hZMzNlRUdPbHdsVGpSYTA2UFBtS050ekVkdW4wciswTTJpMGJlYlVXTHRnZU00N2k1bUZKVDhyVlh6ZWVCWkZQU1ptaGNDT21yeUJBaHZzbHdKejU5K215R0ZRMHY2K0FXRGNEQ3drQlVjdlNsZ1p1VU1sK05aU0tMK2ZOWDdhNkdDelFHWWp2TVdnVVptN3JyUGVYMG5GVTFqVEtzdW9PT1FScldoUlpOQ1dvVEI0UEFsSU9UZ3JIOWZwVWVsU2hEbzltSmo3a0VJcW9ZVXdKQmw5Z2dqQjNNbWwxdzhiVlJVVTJnRUhobXlCUWxiWkVQbVVVQ0ZiSzRqcFdvdW5XcEVxSzZKdjlid3BCSlFJREFRQUJvNElCUlRDQ0FVRXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUIwR0ExVWRFUVFXTUJTQ0VtRjBkR1Z6ZEM1aGJtUnliMmxrTG1OdmJUQm9CZ2dyQmdFRkJRY0JBUVJjTUZvd0t3WUlLd1lCQlFVSE1BS0dIMmgwZEhBNkx5OXdhMmt1WjI5dloyeGxMbU52YlM5SFNVRkhNaTVqY25Rd0t3WUlLd1lCQlFVSE1BR0dIMmgwZEhBNkx5OWpiR2xsYm5Sek1TNW5iMjluYkdVdVkyOXRMMjlqYzNBd0hRWURWUjBPQkJZRUZMT2F4S0x1anVlNEp3UWtpY1B1a3M3OFFnRHBNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVTdDBHRmh1ODltaTFkdldCdHJ0aUdycGFnUzh3RndZRFZSMGdCQkF3RGpBTUJnb3JCZ0VFQWRaNUFnVUJNREFHQTFVZEh3UXBNQ2N3SmFBam9DR0dIMmgwZEhBNkx5OXdhMmt1WjI5dloyeGxMbU52YlM5SFNVRkhNaTVqY213d0RRWUpLb1pJaHZjTkFRRUZCUUFEZ2dFQkFISlVOZWZYOVFKVVRTOXNrUkFhbDBIU21kRi9DaG5XUW1IVzM0aHhReHNlQmRFT1UzcVZkZWZKRi95b09RSmpBWTJvclhDTmFGVXpTK09jLzVrWCt5RG5PbVA5TDhmQ2hTMzhnbmZrZTB6ZVd6MWRnZGhiazJhUUNUWi9NV0IyMFptc1pWeEI2d0xEVjFOS0M4STZwOVY0aytQTENydUxUMFFiN2xkUnFTdDNLSERTSCt0TThVZi9CVjJXbjZzTEZtYTliZ1FnUXIyaElYay83MXBWWnZMUDFHQnJmWDF4cW5UbTc3dXFUNWlUeW5taGd0SXVrUmJLNVN3aXphc0U2dytJd2RMTWYwZFRLWHBXS1FIZ3JDQklkKzlldnNEUjBFN3VOL3BzZjNaVkNmLzM3UzhrUXZaS3NaV0JSblJLeExQZFVDV0g1VUErK0txcS9JdGNtUVU9IiwiTUlJRDhEQ0NBdGlnQXdJQkFnSURBanAyTUEwR0NTcUdTSWIzRFFFQkJRVUFNRUl4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MUhaVzlVY25WemRDQkpibU11TVJzd0dRWURWUVFERXhKSFpXOVVjblZ6ZENCSGJHOWlZV3dnUTBFd0hoY05NVE13TkRBMU1UVXhOVFUxV2hjTk1UWXhNak14TWpNMU9UVTVXakJKTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNoTUtSMjl2WjJ4bElFbHVZekVsTUNNR0ExVUVBeE1jUjI5dloyeGxJRWx1ZEdWeWJtVjBJRUYxZEdodmNtbDBlU0JITWpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSndxQkhkYzJGQ1JPZ2FqZ3VEWVVFaThpVC94R1hBYWlFWis0SS9GOFluT0llNWEvbUVOdHpKRWlhQjBDMU5QVmFUT2dtS1Y3dXRaWDhiaEJZQVN4RjZVUDd4YlNEajBVL2NrNXZ1UjZSWEV6L1JURGZSSy9KOVUzbjIrb0d0dmg4RFFVQjhvTUFOQTJnaHpVV3gvL3pvOHB6Y0dqcjFMRVFUcmZTVGU1dm44TVhIN2xOVmc4eTVLcjBMU3krckVhaHF5ekZQZEZVdUxIOGdaWVIvTm5hZytZeXVFTldsbGhNZ1p4VVlpK0ZPVnZ1T0FTaERHS3V5Nmx5QVJ4em1aRUFTZzhHRjZsU1dNVGxKMTRyYnRDTW9VL000aWFyTk96MFlEbDVjRGZzQ3gzbnV2UlRQUHVqNXh0OTcwSlNYQ0RUV0puWjM3RGhGNWlSNDN4YStPY21rQ0F3RUFBYU9CNXpDQjVEQWZCZ05WSFNNRUdEQVdnQlRBZXBob2pZbjdxd1ZrREJGOXFuMWx1TXJNVGpBZEJnTlZIUTRFRmdRVVN0MEdGaHU4OW1pMWR2V0J0cnRpR3JwYWdTOHdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdOUVlEVlIwZkJDNHdMREFxb0NpZ0pvWWthSFIwY0RvdkwyY3VjM2x0WTJJdVkyOXRMMk55YkhNdlozUm5iRzlpWVd3dVkzSnNNQzRHQ0NzR0FRVUZCd0VCQkNJd0lEQWVCZ2dyQmdFRkJRY3dBWVlTYUhSMGNEb3ZMMmN1YzNsdFkyUXVZMjl0TUJjR0ExVWRJQVFRTUE0d0RBWUtLd1lCQkFIV2VRSUZBVEFOQmdrcWhraUc5dzBCQVFVRkFBT0NBUUVBSjR6UDZjYzd2c0J2NkphRSs1eGNYWkRrZDl1TE1tQ2JaZGlGSnJXNm54N2VaRTRmeHNnZ1d3bWZxNm5nQ1RSRm9tVWxOejEvV204Z3pQbjY4UjJQRUF3Q09zVEpBWGFXdnB2NUZkZzUwY1VEUjNhNGlvd3gxbURWNUkvYitqekcxWmdvK0J5UEY1RTB5OHRTZXRIN09pRGs0WWF4MkJnUHZ0YUhaSTNGQ2lWQ1VlK3lPTGpnSGREaC9PYjByMGE2NzhDL3hiUUY5WlIxRFA2aXZnSzY2b1piK1RXelp2WEZqWVdoR2lOM0doa1hWQk5nbnd2aHRKd29Ldm11QWpSdEpaT2NncWdYZS9HRnNOTVBXT0g3c2Y2Y29hUG8vY2svOU5keDNMMk1wQm5nSVNNalZST1BwQllDQ1g2NXIrN2JVMlM5Y1MrNU9jNHd0N1M4Vk9CSEJ3PT0iLCJNSUlEZlRDQ0F1YWdBd0lCQWdJREVydm1NQTBHQ1NxR1NJYjNEUUVCQlFVQU1FNHhDekFKQmdOVkJBWVRBbFZUTVJBd0RnWURWUVFLRXdkRmNYVnBabUY0TVMwd0t3WURWUVFMRXlSRmNYVnBabUY0SUZObFkzVnlaU0JEWlhKMGFXWnBZMkYwWlNCQmRYUm9iM0pwZEhrd0hoY05NREl3TlRJeE1EUXdNREF3V2hjTk1UZ3dPREl4TURRd01EQXdXakJDTVFzd0NRWURWUVFHRXdKVlV6RVdNQlFHQTFVRUNoTU5SMlZ2VkhKMWMzUWdTVzVqTGpFYk1Ca0dBMVVFQXhNU1IyVnZWSEoxYzNRZ1IyeHZZbUZzSUVOQk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMnN3WVl6RDk5QmNqR2xaK1c5ODhiRGprY2JkNGtkUzhvZGhNK0toRHRnUHBUU0VIQ0lqYVdDOW1PU205QlhpTG5Uam9CYmRxZm5HazVzUmdwckR2Z09TSktBK2VKZGJ0Zy9PdHBwSEhtTWxDR0RVVW5hMllScEl1VDhyeGgwUEJGcFZYTFZEdmlTMkFlbGV0OHU1ZmE5SUFqYmtVK0JRVk5kbkFScU43Y3NpUnY4bFZLODNRbHo2Y0ptVE0zODZER1hIS1R1YlUxWHVwR2MxVjNzanMwbDQ0VStWY1Q0d3QvbEFqTnZ4bTVzdU9wRGtaQUxlVkFqbVJDdzcrT0M3UkhRV2E5azArYnc4SEhhOHNIbzlnT2VMNk5sTVRPZFJlSml2YlBhZ1V2VExyR0FNb1VnUng1YXN6UGVFNHV3YzJoR0tjZWVvV01QUmZ3Q3ZvY1d2aytRSURBUUFCbzRId01JSHRNQjhHQTFVZEl3UVlNQmFBRkVqbWFQa3IwcktWMTBmWUl5QVFUek9Za0ovVU1CMEdBMVVkRGdRV0JCVEFlcGhvalluN3F3VmtEQkY5cW4xbHVNck1UakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIvd1FFQXdJQkJqQTZCZ05WSFI4RU16QXhNQytnTGFBcmhpbG9kSFJ3T2k4dlkzSnNMbWRsYjNSeWRYTjBMbU52YlM5amNteHpMM05sWTNWeVpXTmhMbU55YkRCT0JnTlZIU0FFUnpCRk1FTUdCRlVkSUFBd096QTVCZ2dyQmdFRkJRY0NBUll0YUhSMGNITTZMeTkzZDNjdVoyVnZkSEoxYzNRdVkyOXRMM0psYzI5MWNtTmxjeTl5WlhCdmMybDBiM0o1TUEwR0NTcUdTSWIzRFFFQkJRVUFBNEdCQUhiaEVtNU9TeFlTaGpBR3NvRUl6L0FJeDhkeGZtYnV3dTNVT3gvLzhQRElUdFpET0xDNU1IMFkwRldEb21yTE5oR2M2RWhtbzIxL3VCUFVSLzZMV2x4ei9LN1pHeklaT0t1WE5CU3FsdExyb3h3VUNFbTJ1K1dSNzRNMjZ4MVdiOHJhdkhOamtPUi9lejRpeXowSDdWODRkSnpqQTFCT29hK1k3bUh5aEQ4UyJdfQ.eyJleHRlbnNpb24iOiJDWEF4OGdkenVoMmsiLCJhcGtDZXJ0aWZpY2F0ZURpZ2VzdFNoYTI1NiI6W10sImVycm9yIjoiaW50ZXJuYWxfZXJyb3IifQ.m74WEuoMrUMhXd8VwKrQk5Wdqn1zOYD-Fg-JePbBxXbrRtKDkEMM8sg3VCjZ-8NNbcynNiKUX9EnIdu8MoXSbI2Dl9jfxACZdrpEoUkNPzVh8FYwlJ4M-N3tXYsO8y4Z0ddUGhs_2_xA-vLAxLGZQbN0FJIdyId2WZW3m3M4TBA9krxaYlh1MefukcJJJ49wTa0tb3MKFbHiAhIEh2cB8AIkL_UUo2LmTtgHa43MM_-B_yFS3eehAClyC05aUjKbnP9IWQv27feqheZ89JGCMfmiobbBK9mt3-B1q85I9iFFS1iSq7J5aLv70usUH7qiQmc_ts4jWhvJ8_N1-21Y4Q&application_id=com.snapchat.android&req_token=930cd557787199c86e544deaf8ae15b467ed4d8119842a8ca9b42a14ddc5140b
stdClass Object
(
    [message] => Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)
    [status] => -103
    [logged] => 
)
RESULT: 1
My friends: PHP Warning:  Invalid argument supplied for foreach() in /Users/Pilo/Desktop/SC-API-master/src/snapchat.php on line 2271
PHP Stack trace:
PHP   1. {main}() /Users/Pilo/Desktop/SC-API-master/examples/exampleFunctional.php:0
PHP   2. Snapchat->getStoriesByUsername() /Users/Pilo/Desktop/SC-API-master/examples/exampleFunctional.php:45

Warning: Invalid argument supplied for foreach() in /Users/Pilo/Desktop/SC-API-master/src/snapchat.php on line 2271

Call Stack:
    0.0002     228512   1. {main}() /Users/Pilo/Desktop/SC-API-master/examples/exampleFunctional.php:0
    2.4775     768792   2. Snapchat->getStoriesByUsername() /Users/Pilo/Desktop/SC-API-master/examples/exampleFunctional.php:45

**Comment by mgp25** [comment]
Fixed in latest commits:
https://github.com/mgp25/SC-API/commit/f830a9ce79891ca2723ef17c7468d555ed3c6f77
https://github.com/mgp25/SC-API/commit/d6e5256806290b64df76a1022e239b86a4abf529

**Comment by emiliobasualdo** [comment]
thanks
