### ISSUE TITLE
New login issue

### ISSUE THREAD

**Issue by ghost** [mgp25/Snap-API#135]
Worked well until today. Now I'm getting this when I try to login:

``` html
<html><head><meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>401 UNAUTHORIZED</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: UNAUTHORIZED</h1>
</body></html>
```

**Comment by vasilywang** [comment]
The same

**Comment by mgp25** [comment]
Server is blocked or your account have been blocked, please try from another server/IP

Note: Remove your auth.dat and retry again

**Comment by ghost** [comment]
I highly doubt it is blocking issue. I tried different ips with different accounts, all the same. Actually even if you enter random username and password, you'll get the same error. Have you tried yours?

Yes, I did remove auth.dat and tried force login.

**Comment by Mxchael** [comment]
I got this with the latest update. Older versions work but take awhile to login (login failed error often)

**Comment by ghost** [comment]
@Spurlex which old version?

**Comment by ghost** [comment]
@mgp25 were you able to reproduce the error? Is there any plan to fix it? 

Thanks.

**Comment by ssbb** [comment]
Get the same issue. Looks like snapchat api was changed, because Objective-C implementation is not working too (with same error).

**Comment by idb-** [comment]
Also having the same issue. Any fix on the way?

**Comment by teknogeek** [comment]
we are working on it. will push it ASAP

**Comment by ryangurn** [comment]
@teknogeek Do you need help with it?

**Comment by teknogeek** [comment]
sure take a whack at it if you would like. i will keep going too

**Comment by ssbb** [comment]
Are you have ideas why it happens?

Official application still working without any updates, etc.

**Comment by teknogeek** [comment]
has to do with Google attestation from what I can tell

**Comment by mgp25** [comment]
Fixed in latest commits:
https://github.com/mgp25/SC-API/commit/f830a9ce79891ca2723ef17c7468d555ed3c6f77
https://github.com/mgp25/SC-API/commit/d6e5256806290b64df76a1022e239b86a4abf529

**Comment by ghost** [comment]
Awesome. Thanks!
