### ISSUE TITLE
Unable To Login

### ISSUE THREAD

**Issue by JudGithub** [mgp25/Snap-API#137]
``` php
<?php
include_once("snapchat.php");

/////////// DATA /////////////
$username = '';
$password = '';
$gEmail   = '';
$gPasswd  = '';
$debug    = true;
//////////////////////////////
// Login
$snapchat = new Snapchat($username, $gEmail, $gPasswd, $debug);

$snapchat->login($password);
?>
```

Debug Log:
http://pastebin.com/raw.php?i=04EFvjVN

I can't get my account to login. Any help would be appreciated, and yes I am filling in a valid gmail, gmail_pass, snapchat_usern, snapchat_pass

**Comment by mgp25** [comment]
@JudGithub are you using latest code? we have updated yesterday

**Comment by JudGithub** [comment]
Yes the first time I downloaded the API was a few hours ago.

**Comment by vasilywang** [comment]
@mgp25 I also can't login, I got a -103 error 

You have changed getAttestation implement in the latest code, I know an iOS app is still using the old implement and login works, but the protobuf of this app is different from SC-API.

**Comment by mgp25** [comment]
If you are using an iOS account it will give you issues, create a new account using android or using the API. Also remember to remove auth data (if you had it before)

**Comment by JudGithub** [comment]
I used bluestacks android emulator to create my account. I have tried creating an account using the api but I get an empty .rar file where the captcha is supposed to be of 0kb

**Comment by JudGithub** [comment]
```
REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/register_username
DATA: username=********%40hotmail.com&selected_username=********&timesta
mp=1434970725640&req_token=ef4f3872ef88f34610b9c437195170b99982c2497a05429bf517a
e47********
RESULT:

REQUEST TO: https://feelinsonice-hrd.appspot.com/bq/get_captcha
DATA: username=********&timestamp=1434970728525&req_token=ef42da7e793806c61
06dd9331457ae89fa8dc2417a7d529db5177c47********
RESULT:

You should have a file called 'captcha.zip' in your snap api folder, unzip it.
9 images. If there is a ghost in a image means 1, if not 0
The result should be like the following one: 110000101
After completion, the zip file will be deleted automatically.
```

Seems I'm also not getting a response when I'm trying to create an account too.

**Comment by vasilywang** [comment]
@mgp25 can you make it work for iOS app?

**Comment by mgp25** [comment]
iOS uses other stuff i havent worked on it yet

**Comment by vasilywang** [comment]
Thank you so much, I'm waiting for your implement for iOS

**Comment by teknogeek** [comment]
do you mean code it in objective-c? or use the iOS calls

**Comment by mgp25** [comment]
@teknogeek he wants iOS auth, so he can use his iOS account with the API

**Comment by idb-** [comment]
Not working for me either. 

```
REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id

Sent Request info: POST /loq/device_id HTTP/1.1
User-Agent: Snapchat/9.10.0.0 (HTC One; Android 4.4.2#302626.7#19; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: */*
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer <Redacted>
Content-Length: 101
Content-Type: application/x-www-form-urlencoded


DATA: timestamp=1.4350161039E+12&req_token=<Redacted>
RESULT: <html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>401 UNAUTHORIZED</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: UNAUTHORIZED</h1>
</body></html>
```

This lead to my server getting blocked temporarily :(

**Comment by mgp25** [comment]
@idb- thats because of your sever, not API

**Comment by idb-** [comment]
Could someone post the full header log for the getAttestation request? I'm trying to port this over to another language.

**Comment by idb-** [comment]
would it be possible for me to contact you on skype? i'm trying to port this to another language but am having some issues. I got the attestation request for posting to attest.casper.io working, but am still recieving a bad response when i submit all my data to /loq/login. 

The response I'm recieving is below.

``` json
{"message":"Oh no! Your login temporarily failed, so please try again later.
 If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)"
,"status":-103,"logged":false}
```

**Comment by mgp25** [comment]
@idb- you con contatc me via mail (profile page in github)

@JudGithub check if there is any .zip package called `captcha.zip`, inside will be 9 images, you can follow instructions here: https://github.com/mgp25/SC-API/wiki/Snap-API-Documentation#account-registration

Also remember that Snapchat can block your server, try in your localmachine. If you still have issues, send me a mail and i'll help you

Regards
