### ISSUE TITLE
Trouble with Bluestacks and Script

### ISSUE THREAD

**Issue by adamlooper** [mgp25/Snap-API#138]
Hi there, 

When I run my script I receive the following error. My script is simple; login and log-out. 

Warning: First parameter must either be an object or the name of an existing class in C:\xampp\htdocs\snap_api\src\snapchat_agent.php on line 428

Is there a fix?

And does this work with Bluestacks?

**Comment by teknogeek** [comment]
are you on the latest version and on at least PHP 5.4? also this is a PHP
API and bluestacks is an android emulator so they kinda have nothing to do
with each other...

**Comment by adamlooper** [comment]
I'm running PHP Version 5.6.8, and yep I know just wondering if bluestacks works cause I read iOS doesn't. And just tried again still the same issue...

**Comment by adamlooper** [comment]
Yeah I run the script, get the error, then snapchat (on bluestacks) says error connecting to server when trying to login?

**Comment by teknogeek** [comment]
that sounds like a problem with your network if bluestacks cant login to
snapchat

**Comment by adamlooper** [comment]
Yeah that issue could be my network but not the other one?

**Comment by adamlooper** [comment]
Anyone?

**Comment by mgp25** [comment]
@adamlooper This Snapchat API has nothing to do / related with Bluestacks or official app. We provide an access to the private API of Snapchat, which is different to the real app.

If Snapchat app doesn't work in bluestacks maybe you don't have any google account set correctly in there or as @teknogeek said, a problem with your network

If you have any issue with our API let me know, but not Bluestacks issues related

Regards
