### ISSUE TITLE
Problem send video

### ISSUE THREAD

**Issue by birnware** [mgp25/Snap-API#139]
When try to send video, it show `451 error ( INVALID FILE TYPE)` , witch format of video support the API ?

**Comment by mgp25** [comment]
mp4

**Comment by birnware** [comment]
Every resolution of video works or need a specific resolution? For example 454x313px  ?

**Comment by mgp25** [comment]
@birnware that will work, you can use any mobile resolution. But be careful with the video size, if its too big, maybe you will have to split it into multiple parts

**Comment by birnware** [comment]
@mgp25  i was try to upload this file "https://www.dropbox.com/s/c6lou04fcw7rl5d/IMG_1420.mp4?dl=0" but it shows me 

```
 code = 415;
        data = "<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>415 UNSUPPORTED_MEDIA_TYPE</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: UNSUPPORTED_MEDIA_TYPE</h1>\n</body></html>\n";
        test = 1;
    };
```

**Comment by mgp25** [comment]
@birnware use latest API code, it works perfectly from CLI. This is the code i used:

``` php
<?php

require_once('/Desktop/Snap-API/src/snapchat.php');

$username = '';
$password = '';
$gEmail = '';
$gPasswd = '';
$debug = true;

$snapchat = new Snapchat($username, $gEmail, $gPasswd, $debug);

$snapchat->login($password);

$path = "/Desktop/IMG_1420.mp4";
$to = ""; // to username


$snapchat->send($path, $to);
```

``` json
RESULT: {"snap_response":{"snaps":{"***":{"id":"413060436434505962","timestamp":1436434505962}},"success":true}}
```
