### ISSUE TITLE
Snapchat new feature: Add friends Nearby

### ISSUE THREAD

**Issue by lucasgerard** [mgp25/Snap-API#144]
Hi,

Yesterday a new feature got rolled out that looks very promising: you can now find friends nearby and add them. Hope you'll find a way to add this feature in this API ;)

Thank you very much for your work!

Lucas

**Comment by mgp25** [comment]
There you go: https://github.com/mgp25/SC-API/commit/2ccff7218f8c98d45d98d051adade75196e5f4af

Regards
