### ISSUE TITLE
Error: Unsupported_media_type

### ISSUE THREAD

**Issue by Derpolino** [mgp25/Snap-API#146]
Hello, when i send a snap with the terminal, it works, but when i use nginx, i got this error : 

Error: Unsupported_media_type

Please can u provide me some help ?

**Comment by mgp25** [comment]
@Nicocraft71 maybe because you need to install/activate dependencies in the server https://github.com/mgp25/SC-API/wiki/Dependencies

You will need php fileinfo too, check if you have everything

Not an API issue.

Regards
