### ISSUE TITLE
Undefined property: stdClass::$iter_token when running ->getSnaps()

### ISSUE THREAD

**Issue by Lilleengen** [mgp25/Snap-API#148]
Getting the following error 
`Notice: Undefined property: stdClass::$iter_token in /home/vagrant/Code/snapbot/vendor/mgp25/snapapi/src/snapchat.php on line 856` when running getSnaps() on a snapchat object. Full output:
https://gist.github.com/Lilleengen/d3ab3f8f71a7b8b655a1

**Comment by mgp25** [comment]
@Lilleengen Update your code, it should work with latest commits

Regards
