### ISSUE TITLE
[ErrorException] Undefined index: error

### ISSUE THREAD

**Issue by MatthewHallCom** [mgp25/Snap-API#149]
I've removed some private details for security sake, but here is the output I am getting.

It is happening on a login attempt. A valid snapchat and Google account details are provided. Using the 2.0 release from Github.

Please let me know if there is any other details I can provide.

```
REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id

Sent Request info: POST /loq/device_id HTTP/1.1
User-Agent: Snapchat/9.10.0.0 (HTC One; Android 4.4.2#302626.7#19; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: */*
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer TOKENREMOVEDFORSECURITY
Content-Length: 102
Content-Type: application/x-www-form-urlencoded


DATA: timestamp=1.43685188378E+12&req_token=930baf510ec10c386e24ddebfcad8614b2e04d8119d25a8a39b48d14d2c5198b
RESULT: <html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>401 UNAUTHORIZED</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: UNAUTHORIZED</h1>
</body></html>




  [ErrorException]        
  Undefined index: error  



Exception trace:
 () at /Users/matt/git/Side Projects/vendor/mgp25/snapapi/src/snapchat.php:350
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /Users/matt/git/Side Projects/vendor/mgp25/snapapi/src/snapchat.php:350
 Snapchat->login() at /Users/matt/git/Side Projects/app/Console/Commands/SyncSnapchat.php:46
 App\Console\Commands\SyncSnapchat->handle() at n/a:n/a
 call_user_func_array() at /Users/matt/git/Side Projects/vendor/laravel/framework/src/Illuminate/Container/Container.php:502
 Illuminate\Container\Container->call() at /Users/matt/git/Side Projects/vendor/laravel/framework/src/Illuminate/Console/Command.php:149
 Illuminate\Console\Command->execute() at /Users/matt/git/Side Projects/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /Users/matt/git/Side Projects/vendor/laravel/framework/src/Illuminate/Console/Command.php:135
 Illuminate\Console\Command->run() at /Users/matt/git/Side Projects/vendor/symfony/console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at /Users/matt/git/Side Projects/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Users/matt/git/Side Projects/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at /Users/matt/git/Side Projects/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:98
 Illuminate\Foundation\Console\Kernel->handle() at /Users/matt/git/Side Projects/artisan:36

```

**Comment by mgp25** [comment]
@nowned it seems your IP is blocked, use other IP/server, try removing you auth file data and try again, ifyou can't login then is your IP

**Comment by MatthewHallCom** [comment]
Hey @mgp25 

I have tried multiple IPs now and it's still happening. I have also tried clearing the auth file and installing a clean copy of SC-API, both dev-master and v2.1

It seems to be an issue with the API call done in getDeviceToken at the very start?

I am no longer even seeing a token listed in the "X-Snapchat-Client-Auth-Token: Bearer" call.

It isn't being called from a server but a home internet connection. I have tested with Snapchat on an Android device and it's working fine.

Any ideas?

**Comment by MatthewHallCom** [comment]
@mgp25

Have now tried on a half dozen IPs in a variety of locations with no luck. I have removed auth data files etc.

Possibly an issue with using it inside the Laravel framework?

**Comment by mgp25** [comment]
@nowned i don't know, have you tried in your own computer using php in terminal/cmd ?

**Comment by MatthewHallCom** [comment]
@mgp25 Yup, that has been the primary way that I have tested. It is a Command Line PHP script done through Laravel's Command interface.

I have just tried from another new location (Home Internet, not datacenter etc.) and their is no Bearer Token being set on the API call to https://feelinsonice-hrd.appspot.com/loq/device_id
