### ISSUE TITLE
Error with setProxyServer()

### ISSUE THREAD

**Issue by spartanz51** [mgp25/Snap-API#151]
Fatal error: Call to a member function setProxyServer() on a non-object in /***/index.php on line 6

Line 5/6: 

``` php
$myProxy = "http://45.64.99.160:8080";
$snapchat->setProxyServer($myProxy);
```

**Comment by mgp25** [comment]
Can you post the code before that part?

**Comment by spartanz51** [comment]
Ok, i have put "$myProxy = .." just before Snapchat Login, and now i have another error:

``` php
<?php
include_once("src/snapchat.php");



$username = "xxxt"; // Your snapchat username
$password = "xxx"; // Your snapchat password
$gEmail   = "xxx@gmail.com"; // Gmail account
$gPasswd  = xxx"; // Gmail account password
$debug = true; // Set this to true if you want to see all outgoing requests and responses from server

$snapchat = new Snapchat($username, $gEmail, $gPasswd, $debug);

$myProxy = "http://xxx:8080";
$snapchat->setProxyServer($myProxy);

//Login to Snapchat with your username and password

$snapchat->login($password);


$msga = ($snapchat->getSnaps());

var_dump ($msga);

echo("Ok");
?>
```

Error:

http://pastebin.com/vXqDLAwh

Thanks

**Comment by mgp25** [comment]
@spartanz51 it seems your server / proxy its blocked try in your local machine if it works, if it works you know the problem

Regards

**Comment by spartanz51** [comment]
Thanks !
And if i'm blocked, i cant do what? (Sorry i'm french)

**Comment by mgp25** [comment]
@spartanz51 if you are blocked you know what problem is, try different server or in localhost

**Comment by spartanz51** [comment]
With another proxy i'll be blocked ? 
It's on a vps, i can't change ip, but i can change proxy
Thanks
