### ISSUE TITLE
Trying to get property of non-object in on line 873 when calling getSnaps

### ISSUE THREAD

**Issue by KirovAir** [mgp25/Snap-API#156]
It happens when getSnaps calls `$conversations = $this->getConversations();`

On this line:

``` php
$offset = end($updates['data']->conversations_response)->iter_token;
```

Not an issue, just something to mention. Thanks for your great library. :)

Edit: I'm using the latest master.

**Comment by mgp25** [comment]
@KirovAir will check it later, thanks for noticing

**Comment by mgp25** [comment]
@KirovAir can you try latest commit? https://github.com/mgp25/SC-API/commit/28f0c40601fd6970324c2d7193780a5b5ed2f291

**UPDATE:** It seems to be solved now, but if you still face this issue (make sure you use latest code), post your debug log and feel free to open this issue again

Regards

**Comment by KirovAir** [comment]
I can confirm the fix works, thanks mgp25!
