### ISSUE TITLE
Getting all conversations

### ISSUE THREAD

**Issue by marank** [mgp25/Snap-API#16]
Is there a way to get all my conversations at once?

afaik, `conversations_response` only holds the latest 20 conversations.

**Comment by mgp25** [comment]
@marank we havent updated that yet, but soon we'll have full support for it.

Regards

**Comment by marank** [comment]
Awesome, thank you!

**Comment by KyleBoyer** [comment]
Fixed with:
https://github.com/mgp25/Snap-API/pull/78

**Comment by mgp25** [comment]
Fixed with https://github.com/mgp25/Snap-API/commit/1928554e8c81fcec65d3500bfa2d14eb70721f81

Regards
