### ISSUE TITLE
Error when running script to get friends

### ISSUE THREAD

**Issue by kkai4u** [mgp25/Snap-API#160]
When i run a simple script to get friends , I get the error
`
Warning: First parameter must either be an object or the name of an existing class in C:\xampp\htdocs\kappa\vendor\mgp25\snapapi\src\snapchat_agent.php on line 428
`

**Comment by mgp25** [comment]
@kkai4u post full debug log

**Comment by kkai4u** [comment]
`REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id DATA: timestamp=1438012423532&req_token=930ed751b93142786e1815e2ffa6a064d1ea4d89199caa84a9b4b214d6c51d5b RESULT: REQUEST TO: https://android.clients.google.com/auth Array ( [device_country] => us [operatorCountry] => us [lang] => en_US [sdk_version] => 19 [google_play_services_version] => 7097038 [accountType] => HOSTED_OR_GOOGLE [Email] =>xyz@gmail.com [service] => audience:server:client_id:694893979329-l59f3phl42et9clpoo296d8raqoljl6p.apps.googleusercontent.com [source] => android [androidId] => 378c184c6070c26c [app] => com.snapchat.android [client_sig] => 49f6badb81d89a9e38d65de76f09355071bd67e7 [callerPkg] => com.snapchat.android [callerSig] => 49f6badb81d89a9e38d65de76f09355071bd67e7 [EncryptedPasswd] => AFcb4KRwAiijSuVw6bY7xO_O58EaKcBU5jNMknZzIoLcB0JaGpsBnaDF42Q76-4XoBVxYMaSiW0l25eot7VsQ0JtXMSeYxobtMBk8ozseY9MPqAlWVYb4lCcRCVIefgKzMygq-yLbJ0zp2nmvy3eQFESc56i6oijyaOuf-emoFzqZ7daXg== ) DATA: 1 RESULT: Auth=eyJhbGciOiJSUzI1NiIsImtpZCI6ImUxZjUxMDIwNDA0ZjM5ZWYyMmRhNTI0NGNjODEyOTVlYTMxZmM5NjYifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwic3ViIjoiMTE0NDQ4ODg4OTkyMTQ1MTk1Mjk0IiwiYXpwIjoiNjk0ODkzOTc5MzI5LXFnMGkwdTg4dDBobThrNmsxbWJyYm5zdWoxMDFoNzN2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJra2FpNHVAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF1ZCI6IjY5NDg5Mzk3OTMyOS1sNTlmM3BobDQyZXQ5Y2xwb28yOTZkOHJhcW9samw2cC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImlhdCI6MTQzODAxMjQyNiwiZXhwIjoxNDM4MDE2MDI2LCJuYW1lIjoieWFzaCBtYW5kaHlhbiIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vLU5FU2kyTTZtRlZjL0FBQUFBQUFBQUFJL0FBQUFBQUFBR01zL0FRVHE0VnZ1Q1pVL3M5Ni1jL3Bob3RvLmpwZyIsImdpdmVuX25hbWUiOiJ5YXNoIiwiZmFtaWx5X25hbWUiOiJtYW5kaHlhbiJ9.Bfpdmj6-uVQTasLjn2dU-KnjxH6JJ0ZVBzfxQmmsgIsqHyYAcVSLeily4TzbPlNHf9R25_BdU15xVvYCYZvFfDutwT81W2vfofPGsyYzsTm0DPJDWZRhx5um4s810gcB8TN-fIvWrXNYGmL_tTwfmgUuo13Li1i_xNn1BJyykXqsVZ0XWSOS4UMZnpL19iMs-95C-n0RtDFQGUh42kQk7HNZ0ycnujusy9lXdXKmtIc5JBA9auCzXuWVCDxWu7Nwnu0fyhkoFveBd5P1lfR0VY-qb636HnMQWESuoAi0ryx67jbCKZXwHBuw9iLX1z72atW7egkbAEk4jVhOtecb_A issueAdvice=auto Expiry=1438016026 storeConsentRemotely=1 REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/login DATA: username=xyz&password=xyz&height=1280&width=720&max_video_height=640&max_video_width=480&dsig=91023da24b56513d9b1e&dtoken1i=00001%3AQ48362o0SXSlwk7e%2BJETZl5qrC3JIx%2BWAtYMo1%2FIad3Xq5gSdZY4Zsb8MiItAzBo&ptoken=ie×tamp=1438012424647&attestation=eyJhbGciOiJSUzI1NiIsIng1YyI6WyJNSUlFZmpDQ0EyYWdBd0lCQWdJSUpSQWpzN1lXcEE4d0RRWUpLb1pJaHZjTkFRRUZCUUF3U1RFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBb1RDa2R2YjJkc1pTQkpibU14SlRBakJnTlZCQU1USEVkdmIyZHNaU0JKYm5SbGNtNWxkQ0JCZFhSb2IzSnBkSGtnUnpJd0hoY05NVFF3T1RJeU1Ea3dPVEEwV2hjTk1UVXdPVEl5TURrd09UQTBXakJzTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNBd0tRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCd3dOVFc5MWJuUmhhVzRnVm1sbGR6RVRNQkVHQTFVRUNnd0tSMjl2WjJ4bElFbHVZekViTUJrR0ExVUVBd3dTWVhSMFpYTjBMbUZ1WkhKdmFXUXVZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3RFNWUmM5NXBYSytLUWdRNTU4YUpCdUtaa0t2WjVZVWJDZG94ZWZpbHo5STlWRlhHQnhhWjlBaDgvWmg0QU9mSiszdTFOS1hZMzNlRUdPbHdsVGpSYTA2UFBtS050ekVkdW4wciswTTJpMGJlYlVXTHRnZU00N2k1bUZKVDhyVlh6ZWVCWkZQU1ptaGNDT21yeUJBaHZzbHdKejU5K215R0ZRMHY2K0FXRGNEQ3drQlVjdlNsZ1p1VU1sK05aU0tMK2ZOWDdhNkdDelFHWWp2TVdnVVptN3JyUGVYMG5GVTFqVEtzdW9PT1FScldoUlpOQ1dvVEI0UEFsSU9UZ3JIOWZwVWVsU2hEbzltSmo3a0VJcW9ZVXdKQmw5Z2dqQjNNbWwxdzhiVlJVVTJnRUhobXlCUWxiWkVQbVVVQ0ZiSzRqcFdvdW5XcEVxSzZKdjlid3BCSlFJREFRQUJvNElCUlRDQ0FVRXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUIwR0ExVWRFUVFXTUJTQ0VtRjBkR1Z6ZEM1aGJtUnliMmxrTG1OdmJUQm9CZ2dyQmdFRkJRY0JBUVJjTUZvd0t3WUlLd1lCQlFVSE1BS0dIMmgwZEhBNkx5OXdhMmt1WjI5dloyeGxMbU52YlM5SFNVRkhNaTVqY25Rd0t3WUlLd1lCQlFVSE1BR0dIMmgwZEhBNkx5OWpiR2xsYm5Sek1TNW5iMjluYkdVdVkyOXRMMjlqYzNBd0hRWURWUjBPQkJZRUZMT2F4S0x1anVlNEp3UWtpY1B1a3M3OFFnRHBNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVTdDBHRmh1ODltaTFkdldCdHJ0aUdycGFnUzh3RndZRFZSMGdCQkF3RGpBTUJnb3JCZ0VFQWRaNUFnVUJNREFHQTFVZEh3UXBNQ2N3SmFBam9DR0dIMmgwZEhBNkx5OXdhMmt1WjI5dloyeGxMbU52YlM5SFNVRkhNaTVqY213d0RRWUpLb1pJaHZjTkFRRUZCUUFEZ2dFQkFISlVOZWZYOVFKVVRTOXNrUkFhbDBIU21kRi9DaG5XUW1IVzM0aHhReHNlQmRFT1UzcVZkZWZKRi95b09RSmpBWTJvclhDTmFGVXpTK09jLzVrWCt5RG5PbVA5TDhmQ2hTMzhnbmZrZTB6ZVd6MWRnZGhiazJhUUNUWi9NV0IyMFptc1pWeEI2d0xEVjFOS0M4STZwOVY0aytQTENydUxUMFFiN2xkUnFTdDNLSERTSCt0TThVZi9CVjJXbjZzTEZtYTliZ1FnUXIyaElYay83MXBWWnZMUDFHQnJmWDF4cW5UbTc3dXFUNWlUeW5taGd0SXVrUmJLNVN3aXphc0U2dytJd2RMTWYwZFRLWHBXS1FIZ3JDQklkKzlldnNEUjBFN3VOL3BzZjNaVkNmLzM3UzhrUXZaS3NaV0JSblJLeExQZFVDV0g1VUErK0txcS9JdGNtUVU9IiwiTUlJRDhEQ0NBdGlnQXdJQkFnSURBanAyTUEwR0NTcUdTSWIzRFFFQkJRVUFNRUl4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MUhaVzlVY25WemRDQkpibU11TVJzd0dRWURWUVFERXhKSFpXOVVjblZ6ZENCSGJHOWlZV3dnUTBFd0hoY05NVE13TkRBMU1UVXhOVFUxV2hjTk1UWXhNak14TWpNMU9UVTVXakJKTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNoTUtSMjl2WjJ4bElFbHVZekVsTUNNR0ExVUVBeE1jUjI5dloyeGxJRWx1ZEdWeWJtVjBJRUYxZEdodmNtbDBlU0JITWpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSndxQkhkYzJGQ1JPZ2FqZ3VEWVVFaThpVC94R1hBYWlFWis0SS9GOFluT0llNWEvbUVOdHpKRWlhQjBDMU5QVmFUT2dtS1Y3dXRaWDhiaEJZQVN4RjZVUDd4YlNEajBVL2NrNXZ1UjZSWEV6L1JURGZSSy9KOVUzbjIrb0d0dmg4RFFVQjhvTUFOQTJnaHpVV3gvL3pvOHB6Y0dqcjFMRVFUcmZTVGU1dm44TVhIN2xOVmc4eTVLcjBMU3krckVhaHF5ekZQZEZVdUxIOGdaWVIvTm5hZytZeXVFTldsbGhNZ1p4VVlpK0ZPVnZ1T0FTaERHS3V5Nmx5QVJ4em1aRUFTZzhHRjZsU1dNVGxKMTRyYnRDTW9VL000aWFyTk96MFlEbDVjRGZzQ3gzbnV2UlRQUHVqNXh0OTcwSlNYQ0RUV0puWjM3RGhGNWlSNDN4YStPY21rQ0F3RUFBYU9CNXpDQjVEQWZCZ05WSFNNRUdEQVdnQlRBZXBob2pZbjdxd1ZrREJGOXFuMWx1TXJNVGpBZEJnTlZIUTRFRmdRVVN0MEdGaHU4OW1pMWR2V0J0cnRpR3JwYWdTOHdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdOUVlEVlIwZkJDNHdMREFxb0NpZ0pvWWthSFIwY0RvdkwyY3VjM2x0WTJJdVkyOXRMMk55YkhNdlozUm5iRzlpWVd3dVkzSnNNQzRHQ0NzR0FRVUZCd0VCQkNJd0lEQWVCZ2dyQmdFRkJRY3dBWVlTYUhSMGNEb3ZMMmN1YzNsdFkyUXVZMjl0TUJjR0ExVWRJQVFRTUE0d0RBWUtLd1lCQkFIV2VRSUZBVEFOQmdrcWhraUc5dzBCQVFVRkFBT0NBUUVBSjR6UDZjYzd2c0J2NkphRSs1eGNYWkRrZDl1TE1tQ2JaZGlGSnJXNm54N2VaRTRmeHNnZ1d3bWZxNm5nQ1RSRm9tVWxOejEvV204Z3pQbjY4UjJQRUF3Q09zVEpBWGFXdnB2NUZkZzUwY1VEUjNhNGlvd3gxbURWNUkvYitqekcxWmdvK0J5UEY1RTB5OHRTZXRIN09pRGs0WWF4MkJnUHZ0YUhaSTNGQ2lWQ1VlK3lPTGpnSGREaC9PYjByMGE2NzhDL3hiUUY5WlIxRFA2aXZnSzY2b1piK1RXelp2WEZqWVdoR2lOM0doa1hWQk5nbnd2aHRKd29Ldm11QWpSdEpaT2NncWdYZS9HRnNOTVBXT0g3c2Y2Y29hUG8vY2svOU5keDNMMk1wQm5nSVNNalZST1BwQllDQ1g2NXIrN2JVMlM5Y1MrNU9jNHd0N1M4Vk9CSEJ3PT0iLCJNSUlEZlRDQ0F1YWdBd0lCQWdJREVydm1NQTBHQ1NxR1NJYjNEUUVCQlFVQU1FNHhDekFKQmdOVkJBWVRBbFZUTVJBd0RnWURWUVFLRXdkRmNYVnBabUY0TVMwd0t3WURWUVFMRXlSRmNYVnBabUY0SUZObFkzVnlaU0JEWlhKMGFXWnBZMkYwWlNCQmRYUm9iM0pwZEhrd0hoY05NREl3TlRJeE1EUXdNREF3V2hjTk1UZ3dPREl4TURRd01EQXdXakJDTVFzd0NRWURWUVFHRXdKVlV6RVdNQlFHQTFVRUNoTU5SMlZ2VkhKMWMzUWdTVzVqTGpFYk1Ca0dBMVVFQXhNU1IyVnZWSEoxYzNRZ1IyeHZZbUZzSUVOQk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMnN3WVl6RDk5QmNqR2xaK1c5ODhiRGprY2JkNGtkUzhvZGhNK0toRHRnUHBUU0VIQ0lqYVdDOW1PU205QlhpTG5Uam9CYmRxZm5HazVzUmdwckR2Z09TSktBK2VKZGJ0Zy9PdHBwSEhtTWxDR0RVVW5hMllScEl1VDhyeGgwUEJGcFZYTFZEdmlTMkFlbGV0OHU1ZmE5SUFqYmtVK0JRVk5kbkFScU43Y3NpUnY4bFZLODNRbHo2Y0ptVE0zODZER1hIS1R1YlUxWHVwR2MxVjNzanMwbDQ0VStWY1Q0d3QvbEFqTnZ4bTVzdU9wRGtaQUxlVkFqbVJDdzcrT0M3UkhRV2E5azArYnc4SEhhOHNIbzlnT2VMNk5sTVRPZFJlSml2YlBhZ1V2VExyR0FNb1VnUng1YXN6UGVFNHV3YzJoR0tjZWVvV01QUmZ3Q3ZvY1d2aytRSURBUUFCbzRId01JSHRNQjhHQTFVZEl3UVlNQmFBRkVqbWFQa3IwcktWMTBmWUl5QVFUek9Za0ovVU1CMEdBMVVkRGdRV0JCVEFlcGhvalluN3F3VmtEQkY5cW4xbHVNck1UakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIvd1FFQXdJQkJqQTZCZ05WSFI4RU16QXhNQytnTGFBcmhpbG9kSFJ3T2k4dlkzSnNMbWRsYjNSeWRYTjBMbU52YlM5amNteHpMM05sWTNWeVpXTmhMbU55YkRCT0JnTlZIU0FFUnpCRk1FTUdCRlVkSUFBd096QTVCZ2dyQmdFRkJRY0NBUll0YUhSMGNITTZMeTkzZDNjdVoyVnZkSEoxYzNRdVkyOXRMM0psYzI5MWNtTmxjeTl5WlhCdmMybDBiM0o1TUEwR0NTcUdTSWIzRFFFQkJRVUFBNEdCQUhiaEVtNU9TeFlTaGpBR3NvRUl6L0FJeDhkeGZtYnV3dTNVT3gvLzhQRElUdFpET0xDNU1IMFkwRldEb21yTE5oR2M2RWhtbzIxL3VCUFVSLzZMV2x4ei9LN1pHeklaT0t1WE5CU3FsdExyb3h3VUNFbTJ1K1dSNzRNMjZ4MVdiOHJhdkhOamtPUi9lejRpeXowSDdWODRkSnpqQTFCT29hK1k3bUh5aEQ4UyJdfQ.eyJub25jZSI6Ilg0T05BaG5YN3RLWkNrTVMybWlFcS9ZVWVsUm9WWWZSQlFHRXpQdEl4aEk9IiwidGltZXN0YW1wTXMiOjE0MzgwMTI0Mjc1NzksImFwa1BhY2thZ2VOYW1lIjoiY29tLnNuYXBjaGF0LmFuZHJvaWQiLCJhcGtEaWdlc3RTaGEyNTYiOiJKSlNoS09MSDRZWWpXWmxKUTcxQTJkUFRjbXhiYU1ib3lmbzBuc0tZIiwiY3RzUHJvZmlsZU1hdGNoIjpmYWxzZSwiZXh0ZW5zaW9uIjoiQ1NQZnM4djVaa09hIiwiYXBrQ2VydGlmaWNhdGVEaWdlc3RTaGEyNTYiOlsiTHh5cS9LSHRNTkMwNDRoajd2cStvT2dWY1Ira3ozbTRJbEdhZ2xuWldsZz0iXX0.avxY1Iyl_-WeRNke_TnxOfAhYzoytCBUBKB0dxVzgqrT6HYoOi6LVpPGXciQwcZ8n4CJP07BYWusOFQNZGI1YtlTUxbD2vPeEEPM04Ma_oRIv97zT2Pedo0qg-46MCZb62yykzgqlGhS6eSTCa8xv6Heue2HpC_wAu8SZj2rAPE7utqTaYlFHMRjk_493uClfPslQK-aiU3A1E6cGk1QMPSd_5yplGJCQ_ha_85waLIfF7aRDVgT3IoHrK7s2eVLuipkqY6253v3ktvHdO9ghcrF9mlomOrM9mV-KdfvFfu0s4MZrUbe8B8YdhXoadluu-7ct0PKCPohW6S7-SjMcw&sflag=1&application_id=com.snapchat.android&req_token=9301e6588d11d6586e997ee3f8a6ae44e4ec4d87198eaa8f49b4ce14dbc5130b RESULT: 1
Warning: First parameter must either be an object or the name of an existing class in C:\xampp\htdocs\kappa\vendor\mgp25\snapapi\src\snapchat_agent.php on line 428
My friends:`
@mgp25 Thanks for helping in advance :)
I removed a few credentials from the code only

**Comment by kkai4u** [comment]
Also it does login to my account I think, it kicks me out of snapchat whenever it does.

**Comment by mgp25** [comment]
@kkai4u then your IP is blocked. Try from different IP or different server and it should work, is working in here :smile:

Try it, and if you need anything else just tell me

Regards

**Comment by kkai4u** [comment]
@mgp25 
Hey, 
I am hosting it on local server and I have a dynamic IP, I just tried after changing it, but it didn't work. What should I do now? 
Thanks :)

**Comment by mgp25** [comment]
@kkai4u contact me via mail and send me your script, ill try on my side

**Comment by kkai4u** [comment]
@mgp25  I am using the exampleFunctional script with every method commented except get friends and print

**Comment by mgp25** [comment]
@kkai4u i mean with your data, sometimes there are local issues, its working on my side btw

**Comment by kkai4u** [comment]
@mgp25 Just sent you an email, please reply with anything you need, I'll reply asap :)

**Comment by kkai4u** [comment]
@mgp25  I managed to fix it by selecting the dev-master package when using the packagist site, but now the Myfriends page is empty, any ideas why?
Thanks again :)

**Comment by LanchaBasualdo** [comment]
@kkai4u  how did you solve it?
