### ISSUE TITLE
Can received snaps be reposted into story automatically?

### ISSUE THREAD

**Issue by emiliobasualdo** [mgp25/Snap-API#162]
Can the bot be programed to repost to its one stories received snaps automatically?

its not an issue though, sorry

**Comment by LanchaBasualdo** [comment]
$dir = "/Users/Pilo/Desktop/SC-API-master/src/snaps/";

// Open a known directory, and proceed to read its contents
if (is_dir($dir)) {
    if ($dh = opendir($dir)) {
        while (($file = readdir($dh)) !== false) {
        	// echo dirname("/Users/Pilo/Desktop/SC-API-master/src/snaps/"). "/snaps/". "$file". "\n";
        	$imagePath = dirname("/Users/Pilo/Desktop/SC-API-master/src/snaps/"). "/snaps/". "$file";
        	// snaps a pilo de prueba
			$snapchat->send($imagePath,"pilobasualdo", "sorry ahora paro de fasear", 5);
        	// Set a story
			// $snapchat->setStory($imagePath);
        }
        closedir($dh);
    }
}

**Comment by emiliobasualdo** [comment]
done sorry and thanks for this amazing api

**Comment by emiliobasualdo** [comment]
for those intrested

``` php
while(1) {

    // deletes auth
    unlink("/Users/Pilo/Desktop/SC-API-master/src/authData/auth-sasstv.dat");

    $snapchat = new Snapchat($username, $gEmail, $gPasswd, $debug);

    //Login to Snapchat with your username and password
    $snapchat->login($password);
    // download snaps
    $snapchat->getSnaps(true);
    $snapchat->clearFeed();
    $files = glob('/Users/Pilo/Desktop/SC-API-master/src/snaps/*.{jpg,mp4}', GLOB_BRACE);
    if ((count($files)) >0 ) {

        foreach($files as $file) {
            $imagePath = $file;
            // echo $imagePath;
            //$snapchat->setStory($imagePath);
            // test con pilo basualdo
            $snapchat->send($imagePath,"pilobasualdo", "Hola perras", 1);
            unlink($imagePath);
        }

        //mail('your@email.com','McDonalds Stock','Stock Price: '.$mcdonalds,'From:you@example.com'); 


        $snapchat->closeAppEvent();
    } else {
        echo "NO snaps". "\n";
    }
sleep(120);
}
```
