### ISSUE TITLE
Strange error- I think failed to login 

### ISSUE THREAD

**Issue by alalm3i** [mgp25/Snap-API#164]
Hi, It doesn't work for me. I think it doesn't login successfully, therefore, all the following request return the following error messages `Warning: Invalid argument supplied for foreach()` and `Warning: First parameter must either be an object or the name of an existing class in C:\wamp\www\SC-API-master\src\snapchat_agent.php on line 428`
Anyone can help us to fix this issue

Here is the debug result 

REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id DATA: timestamp=1438198486571&req_token=930c5d5c751167e86e4213edf2a795f4a4eb4d87193f3a8219b42d14d7c5191b RESULT: REQUEST TO: https://android.clients.google.com/auth Array ( [device_country] => us [operatorCountry] => us [lang] => en_US [sdk_version] => 19 [google_play_services_version] => 7097038 [accountType] => HOSTED_OR_GOOGLE [Email] => nab....boly@gmail.com [service] => audience:server:client_id:694893979329-l59f3phl42et9clpoo296d8raqoljl6p.apps.googleusercontent.com [source] => android [androidId] => 378c184c6070c26c [app] => com.snapchat.android [client_sig] => 49f6badb81d89a9e38d65de76f09355071bd67e7 [callerPkg] => com.snapchat.android [callerSig] => 49f6badb81d89a9e38d65de76f09355071bd67e7 [EncryptedPasswd] => AFcb4KQhtIQg916l6kNtyHMB1LRF7gZPZn2mssZUnDdgopN9iDYLJKg26zB3FZTUuFk_QtvqDGalaAnzoysm2D-_5C-WqPNFSVd91-kKlbdF6_GuyyOfouNfGopFxC0330VJDCNzsrnTMa-nkJ5VSlu2MmAh3KtZ6WHzERrT8-assZLAbQ== ) DATA: 1 RESULT: Auth=eyJhbGciOiJSUzI1NiIsImtpZCI6ImExYTk4NWE1OTI1NmQwMjZlMjUyZDViNWZhZGRmOWI2YjQxZTMyZTMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwic3ViIjoiMTE3MDkyMzYyMTkxMDU5MjI4NTE3IiwiYXpwIjoiNjk0ODkzOTc5MzI5LXFnMGkwdTg4dDBobThrNmsxbWJyYm5zdWoxMDFoNzN2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJuYWJlZWwuYWxhbG1haUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiaWF0IjoxNDM4MTk4NDg5LCJleHAiOjE0MzgyMDIwODksIm5hbWUiOiJuYWJlZWwgYWxhbG1haSIsInBpY3R1cmUiOiJodHRwczovL2xoNi5nb29nbGV1c2VyY29udGVudC5jb20vLUpDTjRyTUxaUVY4L0FBQUFBQUFBQUFJL0FBQUFBQUFBV01nL19WQ1FvblE3YkM0L3M5Ni1jL3Bob3RvLmpwZyIsImdpdmVuX25hbWUiOiJuYWJlZWwiLCJmYW1pbHlfbmFtZSI6ImFsYWxtYWkifQ.SEqBlF-xe809m6aGd09sq8OkcN2qZxdcj3RBs0vqU6XzpYHULGGQO-27H3MyLMWZ7BhnLk5E72-X_6bGMI_A2N7Qy6k_47kC-Akl7eR_FkpCdGXUCq_YNsm6nIh4ad2x6sqFOqkXbMfVzpJOQv-WT6cUXLCLSxyrhEuv_j0Cs2IyHswM5zFMwRiZr1RKeFZSmQYuU9G0JhYnhPN1JnKXMKn02PukehR27JW7WwAjSIYV_MvpHIfZqzamImZM0a0GnOcSJcicZ3O_b7Ey1IJulvm-5cZqBcBldO2oMlg888N7x1R9DZ5F_mtLh9Eqgvah9b0CEWuMkCGwHKyWqFqvgw issueAdvice=auto Expiry=1438202089 storeConsentRemotely=1 REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/login DATA: username=nabboly&password=123456&height=1280&width=720&max_video_height=640&max_video_width=480&dsig=157d4b31da3c3c2bcc64&dtoken1i=00001%3AibgGsfhJRkeNQGVJESWrEOvWS6QN0ZtupPpSkJDJY3gkAoHpnrnHzJwgYayDUKzu&ptoken=ie×tamp=1438198488830&attestation=eyJhbGciOiJSUzI1NiIsIng1YyI6WyJNSUlFZmpDQ0EyYWdBd0lCQWdJSUpSQWpzN1lXcEE4d0RRWUpLb1pJaHZjTkFRRUZCUUF3U1RFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBb1RDa2R2YjJkc1pTQkpibU14SlRBakJnTlZCQU1USEVkdmIyZHNaU0JKYm5SbGNtNWxkQ0JCZFhSb2IzSnBkSGtnUnpJd0hoY05NVFF3T1RJeU1Ea3dPVEEwV2hjTk1UVXdPVEl5TURrd09UQTBXakJzTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNBd0tRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCd3dOVFc5MWJuUmhhVzRnVm1sbGR6RVRNQkVHQTFVRUNnd0tSMjl2WjJ4bElFbHVZekViTUJrR0ExVUVBd3dTWVhSMFpYTjBMbUZ1WkhKdmFXUXVZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3RFNWUmM5NXBYSytLUWdRNTU4YUpCdUtaa0t2WjVZVWJDZG94ZWZpbHo5STlWRlhHQnhhWjlBaDgvWmg0QU9mSiszdTFOS1hZMzNlRUdPbHdsVGpSYTA2UFBtS050ekVkdW4wciswTTJpMGJlYlVXTHRnZU00N2k1bUZKVDhyVlh6ZWVCWkZQU1ptaGNDT21yeUJBaHZzbHdKejU5K215R0ZRMHY2K0FXRGNEQ3drQlVjdlNsZ1p1VU1sK05aU0tMK2ZOWDdhNkdDelFHWWp2TVdnVVptN3JyUGVYMG5GVTFqVEtzdW9PT1FScldoUlpOQ1dvVEI0UEFsSU9UZ3JIOWZwVWVsU2hEbzltSmo3a0VJcW9ZVXdKQmw5Z2dqQjNNbWwxdzhiVlJVVTJnRUhobXlCUWxiWkVQbVVVQ0ZiSzRqcFdvdW5XcEVxSzZKdjlid3BCSlFJREFRQUJvNElCUlRDQ0FVRXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUIwR0ExVWRFUVFXTUJTQ0VtRjBkR1Z6ZEM1aGJtUnliMmxrTG1OdmJUQm9CZ2dyQmdFRkJRY0JBUVJjTUZvd0t3WUlLd1lCQlFVSE1BS0dIMmgwZEhBNkx5OXdhMmt1WjI5dloyeGxMbU52YlM5SFNVRkhNaTVqY25Rd0t3WUlLd1lCQlFVSE1BR0dIMmgwZEhBNkx5OWpiR2xsYm5Sek1TNW5iMjluYkdVdVkyOXRMMjlqYzNBd0hRWURWUjBPQkJZRUZMT2F4S0x1anVlNEp3UWtpY1B1a3M3OFFnRHBNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVTdDBHRmh1ODltaTFkdldCdHJ0aUdycGFnUzh3RndZRFZSMGdCQkF3RGpBTUJnb3JCZ0VFQWRaNUFnVUJNREFHQTFVZEh3UXBNQ2N3SmFBam9DR0dIMmgwZEhBNkx5OXdhMmt1WjI5dloyeGxMbU52YlM5SFNVRkhNaTVqY213d0RRWUpLb1pJaHZjTkFRRUZCUUFEZ2dFQkFISlVOZWZYOVFKVVRTOXNrUkFhbDBIU21kRi9DaG5XUW1IVzM0aHhReHNlQmRFT1UzcVZkZWZKRi95b09RSmpBWTJvclhDTmFGVXpTK09jLzVrWCt5RG5PbVA5TDhmQ2hTMzhnbmZrZTB6ZVd6MWRnZGhiazJhUUNUWi9NV0IyMFptc1pWeEI2d0xEVjFOS0M4STZwOVY0aytQTENydUxUMFFiN2xkUnFTdDNLSERTSCt0TThVZi9CVjJXbjZzTEZtYTliZ1FnUXIyaElYay83MXBWWnZMUDFHQnJmWDF4cW5UbTc3dXFUNWlUeW5taGd0SXVrUmJLNVN3aXphc0U2dytJd2RMTWYwZFRLWHBXS1FIZ3JDQklkKzlldnNEUjBFN3VOL3BzZjNaVkNmLzM3UzhrUXZaS3NaV0JSblJLeExQZFVDV0g1VUErK0txcS9JdGNtUVU9IiwiTUlJRDhEQ0NBdGlnQXdJQkFnSURBanAyTUEwR0NTcUdTSWIzRFFFQkJRVUFNRUl4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MUhaVzlVY25WemRDQkpibU11TVJzd0dRWURWUVFERXhKSFpXOVVjblZ6ZENCSGJHOWlZV3dnUTBFd0hoY05NVE13TkRBMU1UVXhOVFUxV2hjTk1UWXhNak14TWpNMU9UVTVXakJKTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNoTUtSMjl2WjJ4bElFbHVZekVsTUNNR0ExVUVBeE1jUjI5dloyeGxJRWx1ZEdWeWJtVjBJRUYxZEdodmNtbDBlU0JITWpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSndxQkhkYzJGQ1JPZ2FqZ3VEWVVFaThpVC94R1hBYWlFWis0SS9GOFluT0llNWEvbUVOdHpKRWlhQjBDMU5QVmFUT2dtS1Y3dXRaWDhiaEJZQVN4RjZVUDd4YlNEajBVL2NrNXZ1UjZSWEV6L1JURGZSSy9KOVUzbjIrb0d0dmg4RFFVQjhvTUFOQTJnaHpVV3gvL3pvOHB6Y0dqcjFMRVFUcmZTVGU1dm44TVhIN2xOVmc4eTVLcjBMU3krckVhaHF5ekZQZEZVdUxIOGdaWVIvTm5hZytZeXVFTldsbGhNZ1p4VVlpK0ZPVnZ1T0FTaERHS3V5Nmx5QVJ4em1aRUFTZzhHRjZsU1dNVGxKMTRyYnRDTW9VL000aWFyTk96MFlEbDVjRGZzQ3gzbnV2UlRQUHVqNXh0OTcwSlNYQ0RUV0puWjM3RGhGNWlSNDN4YStPY21rQ0F3RUFBYU9CNXpDQjVEQWZCZ05WSFNNRUdEQVdnQlRBZXBob2pZbjdxd1ZrREJGOXFuMWx1TXJNVGpBZEJnTlZIUTRFRmdRVVN0MEdGaHU4OW1pMWR2V0J0cnRpR3JwYWdTOHdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdOUVlEVlIwZkJDNHdMREFxb0NpZ0pvWWthSFIwY0RvdkwyY3VjM2x0WTJJdVkyOXRMMk55YkhNdlozUm5iRzlpWVd3dVkzSnNNQzRHQ0NzR0FRVUZCd0VCQkNJd0lEQWVCZ2dyQmdFRkJRY3dBWVlTYUhSMGNEb3ZMMmN1YzNsdFkyUXVZMjl0TUJjR0ExVWRJQVFRTUE0d0RBWUtLd1lCQkFIV2VRSUZBVEFOQmdrcWhraUc5dzBCQVFVRkFBT0NBUUVBSjR6UDZjYzd2c0J2NkphRSs1eGNYWkRrZDl1TE1tQ2JaZGlGSnJXNm54N2VaRTRmeHNnZ1d3bWZxNm5nQ1RSRm9tVWxOejEvV204Z3pQbjY4UjJQRUF3Q09zVEpBWGFXdnB2NUZkZzUwY1VEUjNhNGlvd3gxbURWNUkvYitqekcxWmdvK0J5UEY1RTB5OHRTZXRIN09pRGs0WWF4MkJnUHZ0YUhaSTNGQ2lWQ1VlK3lPTGpnSGREaC9PYjByMGE2NzhDL3hiUUY5WlIxRFA2aXZnSzY2b1piK1RXelp2WEZqWVdoR2lOM0doa1hWQk5nbnd2aHRKd29Ldm11QWpSdEpaT2NncWdYZS9HRnNOTVBXT0g3c2Y2Y29hUG8vY2svOU5keDNMMk1wQm5nSVNNalZST1BwQllDQ1g2NXIrN2JVMlM5Y1MrNU9jNHd0N1M4Vk9CSEJ3PT0iLCJNSUlEZlRDQ0F1YWdBd0lCQWdJREVydm1NQTBHQ1NxR1NJYjNEUUVCQlFVQU1FNHhDekFKQmdOVkJBWVRBbFZUTVJBd0RnWURWUVFLRXdkRmNYVnBabUY0TVMwd0t3WURWUVFMRXlSRmNYVnBabUY0SUZObFkzVnlaU0JEWlhKMGFXWnBZMkYwWlNCQmRYUm9iM0pwZEhrd0hoY05NREl3TlRJeE1EUXdNREF3V2hjTk1UZ3dPREl4TURRd01EQXdXakJDTVFzd0NRWURWUVFHRXdKVlV6RVdNQlFHQTFVRUNoTU5SMlZ2VkhKMWMzUWdTVzVqTGpFYk1Ca0dBMVVFQXhNU1IyVnZWSEoxYzNRZ1IyeHZZbUZzSUVOQk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMnN3WVl6RDk5QmNqR2xaK1c5ODhiRGprY2JkNGtkUzhvZGhNK0toRHRnUHBUU0VIQ0lqYVdDOW1PU205QlhpTG5Uam9CYmRxZm5HazVzUmdwckR2Z09TSktBK2VKZGJ0Zy9PdHBwSEhtTWxDR0RVVW5hMllScEl1VDhyeGgwUEJGcFZYTFZEdmlTMkFlbGV0OHU1ZmE5SUFqYmtVK0JRVk5kbkFScU43Y3NpUnY4bFZLODNRbHo2Y0ptVE0zODZER1hIS1R1YlUxWHVwR2MxVjNzanMwbDQ0VStWY1Q0d3QvbEFqTnZ4bTVzdU9wRGtaQUxlVkFqbVJDdzcrT0M3UkhRV2E5azArYnc4SEhhOHNIbzlnT2VMNk5sTVRPZFJlSml2YlBhZ1V2VExyR0FNb1VnUng1YXN6UGVFNHV3YzJoR0tjZWVvV01QUmZ3Q3ZvY1d2aytRSURBUUFCbzRId01JSHRNQjhHQTFVZEl3UVlNQmFBRkVqbWFQa3IwcktWMTBmWUl5QVFUek9Za0ovVU1CMEdBMVVkRGdRV0JCVEFlcGhvalluN3F3VmtEQkY5cW4xbHVNck1UakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIvd1FFQXdJQkJqQTZCZ05WSFI4RU16QXhNQytnTGFBcmhpbG9kSFJ3T2k4dlkzSnNMbWRsYjNSeWRYTjBMbU52YlM5amNteHpMM05sWTNWeVpXTmhMbU55YkRCT0JnTlZIU0FFUnpCRk1FTUdCRlVkSUFBd096QTVCZ2dyQmdFRkJRY0NBUll0YUhSMGNITTZMeTkzZDNjdVoyVnZkSEoxYzNRdVkyOXRMM0psYzI5MWNtTmxjeTl5WlhCdmMybDBiM0o1TUEwR0NTcUdTSWIzRFFFQkJRVUFBNEdCQUhiaEVtNU9TeFlTaGpBR3NvRUl6L0FJeDhkeGZtYnV3dTNVT3gvLzhQRElUdFpET0xDNU1IMFkwRldEb21yTE5oR2M2RWhtbzIxL3VCUFVSLzZMV2x4ei9LN1pHeklaT0t1WE5CU3FsdExyb3h3VUNFbTJ1K1dSNzRNMjZ4MVdiOHJhdkhOamtPUi9lejRpeXowSDdWODRkSnpqQTFCT29hK1k3bUh5aEQ4UyJdfQ.eyJub25jZSI6IlFBVTNRWUszZVpVZkhnMTVVUzQrZGZXYVREa0FvZkdxYVhGWlhoUHp4TFE9IiwidGltZXN0YW1wTXMiOjE0MzgxOTg0OTA3MjEsImFwa1BhY2thZ2VOYW1lIjoiY29tLnNuYXBjaGF0LmFuZHJvaWQiLCJhcGtEaWdlc3RTaGEyNTYiOiJKSlNoS09MSDRZWWpXWmxKUTcxQTJkUFRjbXhiYU1ib3lmbzBuc0tZIiwiY3RzUHJvZmlsZU1hdGNoIjpmYWxzZSwiZXh0ZW5zaW9uIjoiQ1RWL2I1MzYwN3d6IiwiYXBrQ2VydGlmaWNhdGVEaWdlc3RTaGEyNTYiOlsiTHh5cS9LSHRNTkMwNDRoajd2cStvT2dWY1Ira3ozbTRJbEdhZ2xuWldsZz0iXX0.B4Uz4g8Pvd5xQjg-NT4WuPudG6tqBLmrM3fLzQDtrT1ga318hKoKWR-3xKCrAiB_T7_2AVPMriNAkfbq3hEu_-Adx1l0dGwzKYpHZZ5EQI4hQeEv1vW1wC-auYlIMjSMj9WE8KPw55dYwiE7Z_dCHvglFlAbpkf6peFrkdiMIqWpVQ79k2OZ_p-Zy2qqiNvvK581VpRw5ElKqqA9nwpzDFXOKsoNImYTgeJTq9jJ-8WTWzdlVfiBkqCPMKG7LYpHGu03_JlyfdnsfWQvoyDxtTvBeptMgmgVWXq7TlTfBgdvNpAjRN4c7gDxpZAk5ZNR9xqyG4Z7tl61ZDuLrvtlJA&sflag=1&application_id=com.snapchat.android&req_token=9308125bb1f1f5886ee7d0e7f7a023c4cfef4d8e1969ca8819b44514d3c5160b RESULT: 1 

here I got 
( ! ) Warning: First parameter must either be an object or the name of an existing class in C:\wamp\www\SC-API-master\src\snapchat_agent.php on line 428

then
( ! ) Warning: Invalid argument supplied for foreach() in C:\wamp\www\SC-API-master\src\snapchat.php on line 2389

then
( ! ) Notice: Trying to get property of non-object in C:\wamp\www\SC-API-master\src\snapchat.php on line 795

finally I got
( ! ) Warning: Invalid argument supplied for foreach() in C:\wamp\www\SC-API-master\src\snapchat.php on line 795

You have to add username as a friend first!

**Comment by mgp25** [comment]
@nabboly seems your IP is blocked, you did not get any result in the first request, so something with blocked IP

**Comment by emiliobasualdo** [comment]
@mgp25 I having this same issue, thus my IP is blocked, What would you recommend me to solve this?
same as : https://github.com/mgp25/SC-API/issues/160 , https://github.com/mgp25/SC-API/issues/140,

**Comment by LanchaBasualdo** [comment]
@nabboly How did you solve it?

**Comment by emiliobasualdo** [comment]
@mgp25 please, any suggestions I have tried Googles public DNS(8.8.8.8) tried DHCP and other Dyanmic IPs, But the problem persists.
