### ISSUE TITLE
Text does not move to carry on one line under

### ISSUE THREAD

**Issue by emiliobasualdo** [mgp25/Snap-API#167]
When running something like this:
`$snapchat->send($imagePath, "pilobasualdo", "hell guys this is a test :D and i´m testing this because separated lines are not created, how could we fix this?", 10);`
or 
`$snapchat->send($imagePath, "pilobasualdo", "", 10);`
this is sent
![img_5978](https://cloud.githubusercontent.com/assets/12802164/9024292/1008e38c-389e-11e5-9f0a-bc6750cd78a8.PNG)
![img_5979](https://cloud.githubusercontent.com/assets/12802164/9024293/100b3e20-389e-11e5-88a9-ec4ad30a80f7.PNG)

how could it be changed so that text is separated or the white line do not appears?

**Comment by emiliobasualdo** [comment]
further more, i noticed the backgroud image is turned arround

**Comment by mgp25** [comment]
@LanchaBasualdo if you dont want to set text, just put `null`. If you want another line, we haev to do some modiffications, but that only additional, leave this link here: https://github.com/mgp25/SC-API/blob/master/src/func.php

If you want to modify it and send a pull request, that would be nice :smile: 

Regards

**Comment by emiliobasualdo** [comment]
@mgp25 thanks. 
The API is working great. 
Thanks again for your time and creation.
