### ISSUE TITLE
Oh no! Your login temporarily failed

### ISSUE THREAD

**Issue by qqqqb** [mgp25/Snap-API#168]
Properly snap block the Gmail account, I tried to create many Gmail accounts and it does block it after 25 requests.
I script works very well, but I'll be glade if you find solution for this issue :+1:

**Comment by mgp25** [comment]
@Tartoob thats server issue, not API code. Snapchat blocks many servers and IPs, and locking account being logging in from there. You can use a proxy, localmachine or other servers.

Regards
