### ISSUE TITLE
No Account data

### ISSUE THREAD

**Issue by KyleNBurke** [mgp25/Snap-API#170]
When I use this library and run this standard code:

``` php
include_once('src/snapchat.php');
$username = "XXX"; // Your snapchat username
$password = "XXX"; // Your snapchat password
$gEmail   = "XXX"; // Gmail account
$gPasswd  = "XXX"; // Gmail account password
$debug = true; // Set this to true if you want to see all outgoing requests and responses from server
$snapchat = new Snapchat($username, $gEmail, $gPasswd, $debug);
$snapchat->login($password);
var_dump($snapchat->getFriends());
```

It returns an empty array and I'm not sure why because I have plenty of friends linked to that account. Upon login no errors are reported, a var_dump() of the login() function returns this:

`array(2) { ["error"]=> int(0) ["data"]=> NULL }`

There are also no snaps returned by the getSnaps() function. Why isn't any of my account data (friends snaps, etc...) showing up?

**Comment by mgp25** [comment]
@CasualKyle can you post your debug log?

**Comment by KyleNBurke** [comment]
@mgp25 Sure can!
http://pastebin.com/raw.php?i=XXWRsyi6

**Comment by KyleNBurke** [comment]
Is it possible my IP has been blocked?

**Comment by Lambik** [comment]
I have the same issue. I changed line 428 to read

`if (is_object($jsonResult) && property_exists($jsonResult, "status") && $jsonResult->status == '-103')`

but other than that, I have the same result (empty friends array).

The return value of the login() function is quite empty too:

```
Array
(
    [error] => 0
    [data] =>
)
```

**Comment by alalm3i** [comment]
I have the same issue too, I have posted it before and @mgp25 said it is possible that my IP has been blocked. 
I'm using my local machine to run it, but it doesn't work. when I try to login using my android mobile connected to my wireless network it works. 
I think it is the same IP address for my network, 
Do you think there is some other reason for this issue?
Thank you

**Comment by faris-tech-lab** [comment]
Same thing here, not sure what's going on.

**Comment by mgp25** [comment]
Yes, it is because of the IP, if you don't get any result when logging in, then you are blocked, you should get a lot of info and updates.

Regards

**Comment by faris-tech-lab** [comment]
But I'm running it on localhost, so it'd my local IP that is blocked? Pretty sure I can login from a phone using the same network.

**Comment by mgp25** [comment]
@Voiceeeeee try with the latest code
