### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by transitive-bullshit** [mgp25/Snap-API#173]
I've created a nodejs port of SC-API / SnapchatKit and for the most part everything's working without issue.

I believe the trouble I'm running into is due to Snapchat rate limiting requests originating from some combination of my IP, account, and/or auth token.  What I'm seeing in practice is that if I run all of my unit tests individually, they pass fine, but if I try to run them back-to-back, after 10 or so successful calls all the subsequent ones start failing with 401 errors.

I was wondering if anyone here knows more detail about Snapchat's rate limiting and/or general bot detection strategies.

**Comment by teknogeek** [comment]
......401 is not a rate limit. please read what the error is

**Comment by teknogeek** [comment]
401 is unauthorized. your auth token or bearer is wrong

**Comment by transitive-bullshit** [comment]
I understand that a 401 is unauthorized, but the issue only repros when I run a large batch of requests in quick succession, and once one fails they all fail subsequently.  It's not inconceivable that Snapchat is returning a 401 here instead of something more reasonable like 503 in this case since we can all agree they don't exactly have their shit together.  When the tests are run individually or with timeouts inbetween, everything works fine.

If anyone has run into something like this before or knows any details w.r.t. Snapchat's rate limiting, I'm eager to know.

Thanks!

**Comment by teknogeek** [comment]
can you do one or more of the following things for me please:
- share your code with me (privately or publicly)
- show me the flow/order that you are doing that produces this problem
- try that same flow/order using the PHP API and see if the problem persists

**Comment by transitive-bullshit** [comment]
Sure -- appreciate the help!

https://github.com/fisch0920/snapchat (mostly a port of SnapchatKit)

To repro the issue, you'll need to checkout the repo and have node/npm installed, set the 4 required account environment variables (username/pw, gmail/gmailpw), and then run `npm install -g tape standard` and `npm install` to install some dependencies. Then finally `npm run test` which'll kick off all of the unit tests under `test/*`.

If you run a single set of tests with, for instance, `tape test/friends.js` which'll signin and then test friends-related API routes, they'll work fine, but when trying to run all of the different tests back-to-back, I run into the problem described above.  Maybe it's due to logging in multiple times too quickly?

I'll try to repro the issue using the PHP API, but for now it's off to bed.

**Comment by mgp25** [comment]
I close this issue, as it is not an API issue. You can continue this conversation and we will help

Regards
