### ISSUE TITLE
Bad Auth

### ISSUE THREAD

**Issue by ibennz** [mgp25/Snap-API#174]
No matters what I try, i keep getting :  `DATA: 1 RESULT: Error=BadAuthentication NULL`
from the getAuthtoken function.

doubt its my server since i recently got a new.

**Comment by mgp25** [comment]
@ibennz probably it's your server, try it in localhost, it works in my side

Regards

**Comment by ibennz** [comment]
Yes, something is wrong on my side. Thanks.
