### ISSUE TITLE
whats is STDIN parameter in examples 

### ISSUE THREAD

**Issue by beljk** [mgp25/Snap-API#175]
sorry but i am newer in php and i don't know what is STDIN parameter ???

**Comment by teknogeek** [comment]
that is when you enter text into the console

**Comment by beljk** [comment]
but i don't use console so what to use it by browser as url @teknogeek

**Comment by teknogeek** [comment]
err well if you were to use it in your browser you would need to use `$_GET["variablename"]` where variablename is like this `yourscript.php?variablename=value`

**Comment by beljk** [comment]
can you help me give me sample php code to registr new number

**Comment by teknogeek** [comment]
well this is kinda difficult to port over to the method you want without a bit of work. the registerTool.php needs more data partway through it after you do the captcha

**Comment by beljk** [comment]
``` php
include_once("../src/snapchat.php");


echo "\n\nUsername: ";
$username = '***';

echo "\nPassword: ";
$password = '****';

echo "\nEmail: ";
$email = '****@live.com';

echo "\nBirthday (yyyy-mm-dd): ";
$birthday = '****-**-01';

echo "\nGmail address: ";
$gMail = '*****@gmail.com';

echo "\nGmail password: ";
$gPasswd = 'ahmxxxxxxxxxxxxxxxxx';

$snapchat = new Snapchat($username, $gMail, $gPasswd, true);


$id = $snapchat->register($username, $password, $email, $birthday);

echo "\nYou should have a file called '{$id}' in your snap api folder, unzip it.\n";
echo "9 images. If there is a ghost in a image means 1, if not 0\n";
echo "The result should be like the following one: 110000101\n";
echo "After completion, the zip file will be deleted automatically.\n\n";

echo "\nResult: ";
$result = trim(fgets(STDIN));

$result = $snapchat->sendCaptcha($result, $id);
unlink(__DIR__."{$id}");
if ($result == null)
{
    echo "Account successfully created\n";
    echo "\nUsername: $username\n";
    echo "Password: $password\n";
    echo "Email: $email\n";
}
else {
    echo "There was an error registering your account\n";
    echo "Error code: " . $result['code'];
}
```

i get `403 forbidden request`
http://localhost/SC-API-master/examples/registerTool.php

**Comment by beljk** [comment]
i get 403 forbidden request

**Comment by teknogeek** [comment]
403 after which request?

**Comment by beljk** [comment]
we fire this url   `http://localhost/SC-API-master/examples/registerTool.php` i add this data inside `registertool.php` and fire the above link

**Comment by teknogeek** [comment]
that means you probably arent running something correctly with your local webserver. also it still needs to get STDIN for the captcha result. try running it from your console

**Comment by teknogeek** [comment]
i will take a screenshot for what it would look like as an example

**Comment by teknogeek** [comment]
that means you probably arent running something correctly with your local webserver. also it still needs to get `STDIN` for the captcha result. try running it from your console

i will take a screenshot for what it would look like as an example

![image](http://i.imgur.com/5QdLMt0.png)

**Comment by beljk** [comment]
sorry but how to run it from console :D i only have xampp and dreamwaver

**Comment by teknogeek** [comment]
there's more output after that but does that help show you how the `STDIN` works?

`STDIN` and `STDOUT` are `UNIX` terms that are very common. `STDIN` just means input from the command line, and `STDOUT` is output to the command line 

try running CMD as administrator and write

`C:\xampp\php path\to\registerTool.php`

**Comment by teknogeek** [comment]
try running CMD as administrator and write

C:\xampp\php path\to\registerTool.php

**Comment by beljk** [comment]
this command open the file

**Comment by teknogeek** [comment]
it should run it in your command line

**Comment by beljk** [comment]
![runnn](https://cloud.githubusercontent.com/assets/9088199/9473274/37ffdd2c-4b5a-11e5-9ac7-d8da453f8454.png)

look i write this command  in the first image 
`start localhost/SC-API-master/examples/registertool.php`

**Comment by beljk** [comment]
look i write this command  in the first image 
start "localhost/SC-API-master/examples/registertool.php"

**Comment by teknogeek** [comment]
no you have to put the `C:\xampp\php.exe` before it. what you should put into your command window is:

`C:\xampp\php.exe C:\xampp\htdocs\SC-API-master\examples\registertool.php`

**Comment by beljk** [comment]
i get confirmation email from 20 min and i confirmed my account
second 
![runnn](https://cloud.githubusercontent.com/assets/9088199/9473524/8e2fb22a-4b5b-11e5-934b-fe9453fff1e2.png)

i run xampp

**Comment by beljk** [comment]
i run xampp

**Comment by teknogeek** [comment]
oh sorry. you need to cd there first. so the whole thing you should type is this:

`cd C:\xampp\htdocs\SC-API-master\examples; C:\xampp\php.exe registertool.php`

**Comment by beljk** [comment]
![pp](https://cloud.githubusercontent.com/assets/9088199/9474389/b4b587a8-4b60-11e5-9c29-7a9d1283da59.png)

**Comment by teknogeek** [comment]
you had a typo in your command. you did `C:\xampp\php\php.exe` and it should be `C:\xampp\php.exe`
