### ISSUE TITLE
Open story after downloading?

### ISSUE THREAD

**Issue by DummyAccount12345** [mgp25/Snap-API#177]
How do I open a story after downloading ti to view the actual content (images/videos)?

**Comment by mgp25** [comment]
@DummyAccount12345 once you have downloaded the snap/story you have the media saved in `/stories` and `/snaps` folders

Regards

**Comment by DummyAccount12345** [comment]
Yes I know that, but what is the way to view the content of the story? What is it's file type? How do I view all the images/videos in it? What do I open it as?

**Comment by mgp25** [comment]
@DummyAccount12345 basically `.jpg` images and `.mov` or `.avi` filetypes
