### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by emiliobasualdo** [mgp25/Snap-API#180]
When log in process is runned. 
I received this message :
 `You're using a version of Snapchat or operating system that's no longer supported. Please upgrade your device's operating system and update to the newest app version to use Snapchat. Thanks!`

I have tried with 1 other account, same problem.
Here´s the debug
## removed for security

<img width="1399" alt="screen shot 2015-08-31 at 17 08 07" src="https://cloud.githubusercontent.com/assets/12802164/9589172/e5a93584-5002-11e5-9f32-2b880633ff18.png">

I have submited a pull request
https://github.com/mgp25/SC-API/pull/179

**Comment by Chiggins** [comment]
Just so you know, you included your password in that dump!

**Comment by teknogeek** [comment]
fixed that for ya

**Comment by emiliobasualdo** [comment]
@Chiggins  Believe me I don´t care it´s just a testing Account.
@teknogeek Thanks

**Comment by teknogeek** [comment]
anyways, im updating it right now to be on the latest version

**Comment by teknogeek** [comment]
fixed in fc02c6b8449afe1e418f2e048bfca3ba26fc7922

**Comment by emiliobasualdo** [comment]
Thanks
