### ISSUE TITLE
Login issue?

### ISSUE THREAD

**Issue by ghost** [mgp25/Snap-API#181]
If I use the new 9.14.2.0 agent string, both of my accounts shows "unauthorized" when trying to login. If I use the old 9.10.0.0, old account can still login without issue, but new account shows this message: "You're using a version of Snapchat or operating system that's no longer supported. Please upgrade your device's operating system and update to the newest app version to use Snapchat. Thanks!"

**Comment by teknogeek** [comment]
pull the latest version from the git please. it isn't just a user agent change

**Comment by ghost** [comment]
That's what I did. I downloaded the latest version and tried before I post.

**Comment by teknogeek** [comment]
can you delete the auth.dat file for you account and try again

**Comment by ghost** [comment]
I did that, too. I also turned on force login flag.

**Comment by teknogeek** [comment]
something must be wrong on your side then. i just verified that it works perfectly fine on a brand new instance. fresh clone, fresh PHP script to login with SC-API and it worked fine. here was my code,

``` php
<?php
require_once("SC-API/src/snapchat.php");

$gmail = "xxxxxxx@gmail.com";
$gPasswd = "xxxxxxx";
$username = "xxxxxxx";
$password = "xxxxxxx";

$snapchat = new Snapchat($username, $gmail, $gPasswd, true);
$snapchat->login($password);
```

**Comment by ghost** [comment]
Do you want to try my accounts? I can email the info to you.

**Comment by teknogeek** [comment]
sure. **redacted**

**Comment by ghost** [comment]
Thank you! Email sent.

**Comment by teknogeek** [comment]
i was able to login using both of those accounts you sent me with the same code i posted here

**Comment by ghost** [comment]
I looked closely of my error output it appears that getClientToken failed because of the new https. I fixed that and everything's working now! Sorry about the false alarm.

**Comment by teknogeek** [comment]
aha! all good :)
