### ISSUE TITLE
Log in not working

### ISSUE THREAD

**Issue by mzahlag** [mgp25/Snap-API#183]
I am trying to use exampleFunctional.php that was working untill just few days ago, full output I get is: 

```
PHP Notice:  Undefined index: signature in C:\php\snappy\src\snapchat.php on line 431

Notice: Undefined index: signature in C:\php\snappy\src\snapchat.php on line 431
PHP Notice:  Undefined index: error in C:\php\snappy\src\snapchat.php on line 438

Notice: Undefined index: error in C:\php\snappy\src\snapchat.php on line 438
My friends:
```

Seems like authentication is broken, please note that I can log in via phone with no problems at all, meaning my account is not banned.

**Comment by mgp25** [comment]
@mzahlag it's working :) make sure you have all last commits and dependencies, also try a new fresh account because mine was having issues too (maybe it was blocked), but newer accounts works just fine

Regards

**Comment by mzahlag** [comment]
I re-downloaded php and latest version of SC-API and created new account but I still have the same problem. 
It started after the "client token request uses SSL now" commit, are there any additional dependencies besides those on wiki, no idea what else could be problem ?
