### ISSUE TITLE
Login issue again

### ISSUE THREAD

**Issue by ghost** [mgp25/Snap-API#184]
None of my accounts can login now this morning. It keeps showing this message:

`Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)`

**Comment by vasilywang** [comment]
I also got the same message.

**Comment by mzahlag** [comment]
Exactly the same problem on my side aswell.

**Comment by Chiggins** [comment]
This might help shine some light https://www.facebook.com/casper4snapchat/posts/1613207642278824

**Comment by mgp25** [comment]
Thanks @Chiggins 

`it appears it's a change by Google to prevent the workaround authentication to bypass Snapchat's login security`

Use your `auth dat` files so you dont have to relogin again.

It will be fixed as soon as possible. The API will be automatically operative again when this is fixed, no changed required

Regards

**Comment by emiliobasualdo** [comment]
Sorry. I don't understand. Was it fixed?

**Comment by emiliobasualdo** [comment]
@Mgp25

**Comment by teknogeek** [comment]
@LanchaBasualdo no.

**Comment by modsfabio** [comment]
When is this going to be fixed?

**Comment by KirovAir** [comment]
Hi mgp25,
Is there any explanation which values the authData.dat holds next to the Bearer token? As a temp workaround we might be able to inject values using a valid app login and sniffing those values.

**Comment by mgp25** [comment]
@KirovAir of course, if you sniff you auth data, paste it where the `authData.dat` is, and it will work!

It is what i do when i want to use my iOS account for example. Also is explained in the wiki already: https://github.com/mgp25/SC-API/wiki/How-to-use-proxy

**Comment by KirovAir** [comment]
Got it working! Using Android with this xposed module to disable SSL pinning from Snapchat:
https://github.com/Fuzion24/JustTrustMe

**Comment by modsfabio** [comment]
@KirovAir I don't understand how to use this. Can you explane what you did?

**Comment by emiliobasualdo** [comment]
@Mgp25 hey, by sniffing the auth data with proxy. Will de auth data expire at around 50min as before? Or will it be different?

**Comment by mgp25** [comment]
@LanchaBasualdo you can be logged in forever (actually the SC API does the same)

**Comment by emiliobasualdo** [comment]
Shut. Thanks!!

**Comment by vasilywang** [comment]
Casper has updated

**Comment by teknogeek** [comment]
@jerry317 i am aware as i work closely with the developer and worked with him on fixing the problem. i will be implementing a fix into this API within the next couple hours

**Comment by vasilywang** [comment]
@teknogeek thanks a lot, I'm glad to hear that

**Comment by teknogeek** [comment]
no problem :)

**Comment by teknogeek** [comment]
fixed in b6576561ca2ae40ac5b72ac33c5339de65815780
