### ISSUE TITLE
PHP Warning at line 1333

### ISSUE THREAD

**Issue by KirovAir** [mgp25/Snap-API#185]
Hi mgp25,

Not really a bug but some lines I see in my snapchat log:

```
PHP Notice:  Undefined property: stdClass::$is_shared_story in /var/www/snapapi/snapchat.php on line 1333
```

Fixed it by with changing line 1333 to:

``` php
if ((!is_array($friend->name)) && (isset($friend->is_shared_story) && $friend->is_shared_story != 0))
```

Not sure if this is a correct fix since PHP is not my main language.

Keep it up! I am learning a lot from this library btw, can't thank you enough. :)

**Comment by mgp25** [comment]
@KirovAir i'll check in a while, remember to quote the code and output (i already did for you)

Regards
