### ISSUE TITLE
New issues. Video orverlying

### ISSUE THREAD

**Issue by emiliobasualdo** [mgp25/Snap-API#186]
After getting latest update.
Images are downloaded perfectly. but
1) When downloading video snaps files are created but with no extension and zero data.  Debug is returns infinite stuff like this. `?????U????m_SX?j?C???=F:~u??^?x??|??)#?=??{??ؿq{qs˹??8??>Zf?(S??j?Pei?9ǵL??֘)?@?$(??)??O#A'֝????@` From past experience I relate this to png file being not written into files therefore outputting data, probably the video overlay as text or filter in PNG format.
At the same time debug shows `Undefined variable: newFile in .../.../..../SC-API-master/src/snapchat.php on line 1918`which is the `writeToFile($path, $data)`.

Here's the complete debug https://www.dropbox.com/s/7pvivezy72mnvvm/debug.rtf?dl=0
I know there are passwords. don't care.

**Comment by mgp25** [comment]
@LanchaBasualdo can you check the mime type of the file that is causing you that error? For now we are only taking consideration for this mime types:

``` php
            case "image/jpeg":
                $ext = ".jpg";
                break;
            case "image/png":
                $ext = ".png";
                break;
            case "video/mp4";
                $ext = ".mp4";
```

If you notice a new one, let me know

Regards

**Comment by emiliobasualdo** [comment]
@mgp25 mime tiype is `text/plain` probably because of empty file. Thing is that some image files, I belive PNGs, are ouputed at debug like `U????m_SX?j?C???=F:~u??^?x??|??`
