### ISSUE TITLE
Help with Login please

### ISSUE THREAD

**Issue by ghost** [mgp25/Snap-API#188]
`Fatal error: Uncaught exception 'Exception' with message 'getAttestation Exception: HTTP Status Code != 200'`

It's not working for me. What am I doing wrong?

**Comment by wikizhao** [comment]
Is the Casper service down? I'm getting this:

``` json
    {
        "code": 503,
        "message": "DroidGuard Service Unavailable"
    }
```

**Comment by mgp25** [comment]
@modsfabio @wikizhao remove your auth files from the `authData` folder, and try to login. It should be everything ok, its working for me.

Regards

**Comment by emiliobasualdo** [comment]
@mgp25 how often or in which period of time should I update de auth.dat?

**Comment by wikizhao** [comment]
Oh @mgp25 I think it's a bug of casper service. There is a '#' in my password. And the '#' will cause a 503 error. The post fields should be url encoded. : )

**Comment by mgp25** [comment]
@LanchaBasualdo you dont' need to update the auth, you can keep it always

**Comment by emiliobasualdo** [comment]
Ok. Thanks. Thing is I remember from last version that I had yo update de auth every 50min more or less.

**Comment by emiliobasualdo** [comment]
@mgp25 I'm sorry but if I keep the auth.data fiel for more than 50 minutes a `trying to get object from...` message shows up, therefore not logging in

**Comment by ghost** [comment]
Still not working for me. I deleted the Auth dat files
