### ISSUE TITLE
Getting syntax error running exampleFunctional.php

### ISSUE THREAD

**Issue by flyize** [mgp25/Snap-API#19]
When I plug in my credentials, I'm getting the following error:

PHP Parse error:  syntax error, unexpected '[' in /home/ec2-user/scripts/snapchat/src/snapchat.php on line 179

Any idea what I'm doing wrong?

**Comment by mgp25** [comment]
@flyxx have you downloaded latests code? its working for me.

**Comment by flyize** [comment]
Yes, its fresh as of a few minutes before I posted the issue.

**Comment by mgp25** [comment]
@flyxx are you running it locally? If so, have you installed the dependencies? https://github.com/mgp25/Snap-API/wiki/Dependencies

Im going to check the code anyway.

**Comment by flyize** [comment]
Yes, all dependencies are installed.  BTW, if you want to add the commands for RHEL/Centos/Amazon, they are:

yum install php-gd
yum install php-curl
yum install php-mcrypt
yum install php-zip

**Comment by ghost** [comment]
@flyxx What is your PHP version?

**Comment by flyize** [comment]
5.3

**Comment by sallaben** [comment]
https://github.com/mgp25/Snap-API/compare/master...sallaben:patch-1 fixes this error

**Comment by mgp25** [comment]
@sallaben thanks

Fixed: https://github.com/mgp25/Snap-API/commit/4891213d5f99ae648e17b34d21cbe57e10053372
