### ISSUE TITLE
Log in problem

### ISSUE THREAD

**Issue by emiliobasualdo** [mgp25/Snap-API#190]
`PHP Warning:  substr() expects parameter 1 to be string, array given in /home/pilo/Desktop/Dropbox/SC-API-General/src/snapchat.php on line 2049
PHP Notice:  Trying to get property of non-object in /home/pilo/Desktop/Dropbox/SC-API-General/src/snapchat.php on line 1548
PHP Notice:  Trying to get property of non-object in /home/pilo/Desktop/Dropbox/SC-API-General/src/snapchat.php on line 1549
PHP Warning:  Invalid argument supplied for foreach() in /home/pilo/Desktop/Dropbox/SC-API-General/src/snapchat.php on line 1551`
WHat do you relate this to?

**Comment by mgp25** [comment]
@LanchaBasualdo what you were trying to do? (login, getting snap...)

**Comment by emiliobasualdo** [comment]
login and get snaps, Fro previous usage of the appi I relate `Trying to get property of non-object in` to a problem in the login process

**Comment by mgp25** [comment]
@LanchaBasualdo then you are not logged in, so its not API problem its because you are not login correctly

**Comment by emiliobasualdo** [comment]
nono, the exact same code sometimes works and sometimes doesn´t.

**Comment by mgp25** [comment]
@LanchaBasualdo Force login then: https://github.com/mgp25/SC-API/blob/master/src/snapchat.php#L442

**Comment by emiliobasualdo** [comment]
I´ll try, what will the difference be?
