### ISSUE TITLE
account locked when trying to send a video since today

### ISSUE THREAD

**Issue by plopinou** [mgp25/Snap-API#194]
Hello,

It's more a story that an issue, but I'm wondering what is the raisonable limit to respect in order to not get an account locked when sending videos.

Here's what happened to me :
I created a bot using your wonderfull API that does those simple things.
- every 3 mn I list all the friends I have with the `getFriends()` function
- every 1mn I list all the friends that added Me with the `getAddedFriends()` function
- if a new friend added me I add them back width the `addFriend()`. I use a simple `array_diff($addedFriends, $friends);`
- then if this friend sends me a specific keyword message, I add them in a local DB as subscriber to a limited video newsletter.
- then, every week day between 5PM and 6PM, I send a 9s 250KB video too all the friends in the DB every 1mn to 2mn (I only have 42 subscribers ATM) using `send()`, followed by a message using `sendMessage()`.
- the video newlestter is supposed to end in a few weeks.

Everything's was fine for 2 weeks, but today, no video were sent, only the message, and I received an account lock email.
I could not add friends anymore, but was still able to send text message.
After some test and unlocking the account on the snapchat website, I can add friends again, but sending a single video that already worked yesterday to my personnal snapchat account only, get the account instantly locked again.
So I guess that the account has been "flagged", and that I'm not able to send videos anymore.

I don't think I did any mistakes in the process, but it's surprising to get locked with this few contacts.
That's not too bad though, the client was already warned it could happen.

Still, I wanted to share this story in case there is in fact a change in the way snapchat handle videos.
Any confirmation of this ?

Just in case, here's what's happening :

```

REQUEST TO: https://feelinsonice-hrd.appspot.com/ph/upload

Sent Request info: POST /ph/upload HTTP/1.1
User-Agent: Snapchat/9.10.0.0 (HTC One; Android 4.4.2#302626.7#19; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: */*
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsIm...
X-Timestamp: 0
Content-Type: multipart/form-data; boundary=Boundary+0xAbCdEfGbOuNdArY
Content-Length: 185932
Expect: 100-continue


DATA: 185932 byte data
RESULT:

REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/send

Sent Request info: POST /loq/send HTTP/1.1
User-Agent: Snapchat/9.10.0.0 (HTC One; Android 4.4.2#302626.7#19; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: */*
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsIm...
Content-Length: 246
Content-Type: application/x-www-form-urlencoded


DATA: media_id=USERNAME%7E3DE9AA61-5187-001A-0009-0381806D6B62&zipped=0&recipients=%5B%22FRIENDNAME%22%5D&username=USERNAME&time=10&timestamp=1441821114144&features_map=%7B%7D&req_token=6ba0bad9d3ae48e5129b123386d6723d7bb78a03a1451e61b378916035bddf9d
RESULT: {"snap_response":{"success":true}}

```

Thanks again anyway for this very usefull API !

**Comment by mgp25** [comment]
@plopinou seems fine, make sure you are sending to all your subscribers with only one request, don't do a request per user, that will flag your account.

Remember `send()` allows you to pass an array of recipients:

```
     * @param array $recipients
     *   An array of recipient usernames.
```
