### ISSUE TITLE
Retrieve Private messages

### ISSUE THREAD

**Issue by emiliobasualdo** [mgp25/Snap-API#195]
This is no issue, just a question.
Which of the functions should I use to retrieve chat messages?
I tired with
`$friends = $snapchat->getFriends();`
`getConversationInfo($friends)` 
But I get an enormous stdClass mixed with arrays.

**Comment by LanchaBasualdo** [comment]
solved:
`$friends = $snapchat->getFriends();
$conversationInfo= $snapchat->getConversationInfo($friends);
//print_r($conver);
//echo "/////////////////////////////////////////////////////////////"."\n";
//print_r($conver["0"]["sasstv"]->conversation_messages);
$conversation ="";
foreach ($conversationInfo as $A) {
 	foreach ($A as $B) {
 		if(!isset($B->conversation_messages->messages))
  		{
   			break;
  		} 
  		$C=$B->conversation_messages->messages; 
 		foreach($C as $D) {
 			if(!isset($D->chat_message->header->from))
  			{
   				break;
  			} 
 			$conversation .= "From: ";
 			$conversation .= ($D->chat_message->header->from)."\n";
 			$conversation .= "To: ";
 				foreach ($D->chat_message->header->to as $E) {
 					$conversation .=$E."\n";
 				}
 			$conversation .="Message: ";
 			$conversation .= ($D->chat_message->body->text)."\n"."\n";
     	}
	}
}
return $conversation;`

**Comment by emiliobasualdo** [comment]
solved in https://github.com/mgp25/SC-API/pull/196

**Comment by emiliobasualdo** [comment]
@mgp25 hey, I need some help to make this function better, were is the right place for me to get some help from you?

**Comment by mgp25** [comment]
@LanchaBasualdo email
