### ISSUE TITLE
Finding friends by number

### ISSUE THREAD

**Issue by mzahlag** [mgp25/Snap-API#197]
Function "findFriends" is not working.

**Comment by mgp25** [comment]
If you dont post debug log, ill close this issue

**Comment by mzahlag** [comment]
Here is the debug log

https://gist.github.com/anonymous/370c2ce2ed60b631886a

**Comment by mgp25** [comment]
can you proxy the request with your device (android)?

**Comment by mzahlag** [comment]
Request:
https://gist.github.com/mzahlag/650027fdd06d1c7e6e3f

Response:
https://gist.github.com/mzahlag/55b3e19598a8d5b4d9d3

Response is 400 aka "Bad Request" no matter what numbers and sent, and how many of them (1, 30, or anything between)

Tried with multiple snapchat/google accounts

**Comment by mzahlag** [comment]
Hi,
Any updates on progress so far ?

**Comment by mgp25** [comment]
@mzahlag its now working
