### ISSUE TITLE
error -103

### ISSUE THREAD

**Issue by algethamy** [mgp25/Snap-API#198]
I tried to login into my account and i got the following message:

```
stdClass Object
(
    [message] => Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)
    [status] => -103
    [logged] =>
)
RESULT: 1
```

i changed my google email, create a new account in SnapChat, and tried the application in different server. all these tries and still failed :(

can you help me?

my PHP code : 

``` PHP
        //////////// CONFIG ////////////
        $username = "xx"; // Your snapchat username
        $password = "xx"; // Your snapchat password
        $gEmail = "xx@gmail.com"; // Gmail account
        $gPasswd = "xx"; // Gmail account password
        $debug = true; // Set this to true if you want to see all outgoing requests and responses from server
        ////////////////////////////////


        $snapchat = new Snapchat($username, $gEmail, $gPasswd, $debug);

        $snapchat->login($password);

        $snapchat->closeAppEvent();
```

**Comment by mgp25** [comment]
@efrontsa make sure you have latest API code and it's not registered with an iOS. You can also register accounts using this API.

The login is working (just tried it). Make sure you have everything updated and you are using android only for this case.

Regards
