### ISSUE TITLE
How to know the status of a snap sent? And know opened received snaps?

### ISSUE THREAD

**Issue by ghost** [mgp25/Snap-API#199]
Hello,

When I use getSnaps(), I have only NOT opened  received snaps.
It's to have all snaps received (also snaps allready opened)?

And, I would like know if it's possible to know status of a snap sent?
Because getSnaps() not get sent snaps.

Thanks!

**Comment by mgp25** [comment]
`getSnaps()` get the snaps you have received from other users

**Comment by ghost** [comment]
I want get status of snaps sent.
Not possible?

**Comment by emiliobasualdo** [comment]
I think you can. Check the array of results info that is retrieved when a conversation is generated with a sent snap. 
Do so by setting debug to true

**Comment by ghost** [comment]
I have already check array, but I don't see snap sent.
I see only snaps received from other users and not seen.

**Comment by emiliobasualdo** [comment]
Search in the debug for: pending or delivered or opened

**Comment by ghost** [comment]
I don't see this...
After getConversation(), there don't are delivered and opened (var_dump).
