### ISSUE TITLE
401 Unauthorised

### ISSUE THREAD

**Issue by ddaddy** [mgp25/Snap-API#2]
Hi, I keep getting a 401 Unauthorised error with any of the appspot.com requests.

**Comment by mgp25** [comment]
@ddaddy post your code so i can help you.

Regards

**Comment by ddaddy** [comment]
I just used the example project. Could my IP be blocked?

**Comment by mgp25** [comment]
@ddaddy have you edit the file and put your data (username, password, path...) ? Set debug to true for more information

**Comment by ddaddy** [comment]
Yes, although I get Unauthorised for the very first part of login which doesn't send any params `getDeviceToken()`

**Comment by mgp25** [comment]
@ddaddy thats weird, if you want send me an email and im going to help you in fixing that.

Regards
