### ISSUE TITLE
Get attestation issue

### ISSUE THREAD

**Issue by emiliobasualdo** [mgp25/Snap-API#201]
Did anybody else started to get the `PHP Fatal error:  Uncaught exception 'Exception' with message 'getAttestation Exception: HTTP Status Code != 200' in` message again?
It was working fine until todays afternoon.
Snapchat has launched a new version of the app, with the face recognition stuff.

**Comment by teknogeek** [comment]
LITERALLY DO YOU HAVE A PROBLEM 24/7 HOLY SHIT. The fucking API is down momentarily for upscaling. Calm your goddamn titties. KTHXBYE

**Comment by emiliobasualdo** [comment]
Man, I was just asking

**Comment by liamcottle** [comment]
Hiya,

My API gateway server was undergoing an upscale. This is because of the increased traffic.

It's all back up and running again.

Cheers,
Liam Cottle

**Comment by liamcottle** [comment]
I'd suggest liking my Facebook page. I post announcements when the API is going to be offline etc.
https://www.facebook.com/casper4snapchat/posts/1617303168535938

**Comment by teknogeek** [comment]
_gasp_ is that......LOGIC??????

**IMPOSSIBLE!!!!**

**Comment by teknogeek** [comment]
gonna go smash my head against a wall now brb
