### ISSUE TITLE
Finding other users Snapcodes

### ISSUE THREAD

**Issue by robertbodley** [mgp25/Snap-API#210]
HI,

In the newest Snapchat it is possible to view other peoples Snapcodes. Would it be possible to make this accessible in SC-API?

Thanks

**Comment by mgp25** [comment]
If you tell me how i can view other people's Snapcodes, i'll add this feature

**Comment by robertbodley** [comment]
Okay great. 

If you open Snapchat and go to the screen where you can see all the snaps you have received/sent. Swipe on a chat and it should bring up the screen where you can send that contact a message. Now in the top left of the screen you will see the 3 horizontal lines. Click this and their profile will slide out from the side and their Snapcode will be there.

Hope I explained it enough.
Thanks!

**Comment by mgp25** [comment]
@robertbodley right now we can't add that feature, maybe in the future, we need to implement a lot of things yet to get some specific data 

Regards

**Comment by tyronedougherty** [comment]
The newest update (out today) allows you to tap and hold on a user in your friends list or in the stories list to see their snapcode. Is it possible to implement an API that is able to take advantage of this and get the snapcode of a user now?

Thanks

**Comment by nayanbhana** [comment]
request:

```
endpoint: /bq/snaptag_download
form data = 
req_token: eg. 'ac860da80b2bb8b47860ffbf1cdf38e553a4639fb383307754e04f9a195d841a'
timestamp: eg. '1444800886884'
type: 'SVG'
user_id: user_id of friends snaptag you want to download. eg. '2e34e0b5-f940-49fe-8757-c05657b1f345'
username: your snapchat username
```

response:

```
json object
imageData (String)
qrPath (String)
```
