### ISSUE TITLE
AtTestStation Not Currently Functional

### ISSUE THREAD

**Issue by pcrumm** [mgp25/Snap-API#211]
It appears that @liamcottle's AtTestStation isn't currently functional:

`PHP Warning:  file_get_contents(http://attest.casper.io/attestation): failed to open stream: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /Users/phil/Development/snapcorgi-mk2/vendor/mgp25/snapapi/src/snapchat.php on line 164`

This occurs during authentication, preventing any other functionality from working.

**Comment by teknogeek** [comment]
_sigh_ that is not an issue on his end. that means you have no connection or an error within your connection on your machine. [here you go i'll fucking google it for you](http://lmgtfy.com/?q=+nodename+nor+servname+provided%2C+or+not+known)

REGARDLESS that isn't a problem that is even relevant since that URL isn't even used in our API anymore. please at least try _some_ things before complaining

**Comment by pcrumm** [comment]
Er, yes, that is exactly what it means... Because attest.casper.io
currently resolves to a server that any responding on port 80. Did you try
it?

On Sunday, September 20, 2015, Joel Margolis notifications@github.com
wrote:

> Closed #211 https://github.com/mgp25/SC-API/issues/211.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mgp25/SC-API/issues/211#event-414357844.

## 

Sent from mobile

**Comment by teknogeek** [comment]
do i need to write you a step by step guide on how to debug a simple problem?

**Comment by liamcottle** [comment]
@pcrumm It looks like you haven't downloaded the latest version of the library. The http://attest.casper.io server url hasn't been used for quite a while now. It has been changed, and also the structure of the requests have changed.

If you grab the latest version of the lib, it'll be fine.

**Comment by pcrumm** [comment]
Currently rocking 9.14.2.0 via composer--looks like that's what's most
recent on packagist also. I see that develop has changed significantly
since then; I'll give that a try. Thank you for your help.

On Sunday, September 20, 2015, Liam Cottle notifications@github.com wrote:

> @pcrumm https://github.com/pcrumm It looks like you haven't downloaded
> the latest version of the library. The http://attest.casper.io server url
> hasn't been used for quite a while now. It has been changed, and also the
> structure of the requests have changed.
> 
> If you grab the latest version of the lib, it'll be fine.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mgp25/SC-API/issues/211#issuecomment-141880573.

## 

Sent from mobile

**Comment by liamcottle** [comment]
Cool as! I don't maintain the library so not too sure how to update, other than downloading via the ZIP link. I just own and maintain the Casper system.
Which the library uses for getting Attestations and Client Auth Tokens.

**Comment by pcrumm** [comment]
All right, working now.

For anyone who stumbles across this in the future:

The current release on packagist (and thus made available via composer, per the installation instructions), `9.14.2.0`, is out of date. Provisionally, you can just pull from the `master` branch directly until a new release is made. You can do so by placing the following in `composer.json`:

```
{
    "repositories": [
        {
                "type": "vcs",
                "url": "https://github.com/mgp25/SC-API"
        }
    ],
    "require": {
        "mgp25/snapapi": "dev-master"
    }
}```

**Comment by LanchaBasualdo** [comment]
@pcrumm so the zip version of the file I'm downloading is out of date??
