### ISSUE TITLE
Sending Message problem

### ISSUE THREAD

**Issue by emiliobasualdo** [mgp25/Snap-API#212]
Each time a friend is added I want to send a message to him. 
This is the code I'm running:

``` php
$snapchat->sendMessage($FriendsToAdd, "text");
```

Where `$FiendsToAdd` is an array.

this is, each time I run the code I get the following error:

```
 PHP Notice:  Undefined property: stdClass::$NameofTheAccount in... the line 
$seq_num = $convoInfo[0][$to]->conversation_state->user_sequences->$name;
```

 of the `SendMessage` function.

I have googled it, but as this a non general problem I found no fix.
Is any one else having this problem? 
What do you think It might be causing it?

**Comment by mgp25** [comment]
@LanchaBasualdo it's working perfectly. Please, next time quote your code, its easier for us to read it.

Remember that you can only send messages to people already added and accepted by the user.

**Comment by emiliobasualdo** [comment]
Ok, do you have any idea what might be causing it?
