### ISSUE TITLE
clear conversation / clear feed

### ISSUE THREAD

**Issue by Thesmily** [mgp25/Snap-API#214]
how I can to clear conversation and snaps after save it 
I tried `clearfeed()` and `clearConvo()` but not working 
and sometimes when put `clearfeed()` after getmedia , remove the snap without save the snap 
how I can to use it and where I should be to put it to make them as read for certain conversation?

**Comment by mgp25** [comment]
Use this:

`public function markSnapViewed($id, $time = 1)`
