### ISSUE TITLE
Login Error - Casper

### ISSUE THREAD

**Issue by kripsbro** [mgp25/Snap-API#222]
Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login + used proxy server  89.28.121.179:8080

**Comment by liamcottle** [comment]
Hi, are you using the most recent version of this library? We pushed some changes earlier.

**Comment by kripsbro** [comment]
Yes i used  last https://github.com/mgp25/SC-API

**Comment by teknogeek** [comment]
please try a different gmail

**Comment by kripsbro** [comment]
With another gmail i get 

`Accept-Encoding: gzip DATA: username=jonatan.ive&password=123456cat&height=1280&width=720&max_video_height=640&max_video_width=480&dsig=3452e18712b360d63dca&dtoken1i=00001%3A5r%2Bh8GEYS3WIzQcbTa8ud0txr3RwkvJ1iFi%2FdRS1w9pu3UT0Ch0gwqnS0LVoLu41&ptoken=ie×tamp=1444502751752&attestation=eyJhbGciOiJSUzI1NiIsIng1YyI6WyJNSUlFZmpDQ0EyYWdBd0lCQWdJSVZaeDlNZDVhb3JVd0RRWUpLb1pJaHZjTkFRRUxCUUF3U1RFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBb1RDa2R2YjJkc1pTQkpibU14SlRBakJnTlZCQU1USEVkdmIyZHNaU0JKYm5SbGNtNWxkQ0JCZFhSb2IzSnBkSGtnUnpJd0hoY05NVFV3T0RNeE1qQXpOalE0V2hjTk1UWXdPRE13TURBd01EQXdXakJzTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNBd0tRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCd3dOVFc5MWJuUmhhVzRnVm1sbGR6RVRNQkVHQTFVRUNnd0tSMjl2WjJ4bElFbHVZekViTUJrR0ExVUVBd3dTWVhSMFpYTjBMbUZ1WkhKdmFXUXVZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzaWpVemNKOHl3NmhlYnpiQTRYbDJsOTM0dG96SFYyNWdJZ2VMNnU0eWVNNE4yMTh4WitPMWhkelBLbmR6bjArc1VuUHNTekl6SWZiMzV3Nk9xRDlxLysydlk5OUN3T2c0RXF2QXU2OTV1ZjVibzFjNk4rcHpNOWRWMDZIR3dSdUUxUE1OY2Y4Y01CUEJDZy9jWmo2bUlsbFdGVXFERlFmVE5tL25vU0lucmg2WUpUOWhvdUJ6U2d5ZE1Kb2NsYnZEdjlEcThFQ1lWUVhFanA4Z00yVWNnOTNTZXhjb2xmZCtLVUFrNXdkaVBTeXhINFVRaDFvV25iMFR1bzJzeUpQZHh1cWQ3MVRFd1NweE5wcDZxZEFicy9XNE8vZ2swMVVxWEVqbFZvaFhmSE1sbHZsZEd5dWhEM0Z0dFIzOEFEb0dRaWVUVnlzK2VaZWY3ZXYzem9uNFFJREFRQUJvNElCUlRDQ0FVRXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUIwR0ExVWRFUVFXTUJTQ0VtRjBkR1Z6ZEM1aGJtUnliMmxrTG1OdmJUQm9CZ2dyQmdFRkJRY0JBUVJjTUZvd0t3WUlLd1lCQlFVSE1BS0dIMmgwZEhBNkx5OXdhMmt1WjI5dloyeGxMbU52YlM5SFNVRkhNaTVqY25Rd0t3WUlLd1lCQlFVSE1BR0dIMmgwZEhBNkx5OWpiR2xsYm5Sek1TNW5iMjluYkdVdVkyOXRMMjlqYzNBd0hRWURWUjBPQkJZRUZIVGh6cHVGbTNYcGs5c2xScDlRLzNSTGVNK2NNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVTdDBHRmh1ODltaTFkdldCdHJ0aUdycGFnUzh3RndZRFZSMGdCQkF3RGpBTUJnb3JCZ0VFQWRaNUFnVUJNREFHQTFVZEh3UXBNQ2N3SmFBam9DR0dIMmgwZEhBNkx5OXdhMmt1WjI5dloyeGxMbU52YlM5SFNVRkhNaTVqY213d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFENkxLN25UZlhaUzZEMTg1ZlQvencxVGp0SUxOditrYlE3bVJZT2Z6dzY5bW1xWGNaeFppZllsNXRsdWVNZ0xzWFNFOWJQRXNKZk9hZzJLSnFiTVhXUUpGR1F5cmJ1OGszeDZXNDEvNWkzdUl6ZWsvTm5hZ00yV2hmK2lYcWcrdkxmakgyVlJoRmtQQ2k4Z21DTDZneEZidm5ldUd5UlpyMEErS3NOUUxMMW1SQ3RjLzZRYWF0ZWV5Uy9TMmVGcVJaT2NJN2hpak95QTdvRUo4ZDNJMnlOZXdJSmlWd2dMZDNmYWRyekpwVmFyN1ZRR2ljRnJUK0doVnpHSld4U1E0VEQzdUhZY0hHZTAwR2VYUVoxMms3SEtEWDRpRUNrek9jMEtXbG1WVXNXMXRrMTJnTitXQXlkM0QrVkdhV1lwQjNYeWd4VytTd3JrSkZoalpOaURBRkE9IiwiTUlJRDhEQ0NBdGlnQXdJQkFnSURBanFETUEwR0NTcUdTSWIzRFFFQkN3VUFNRUl4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MUhaVzlVY25WemRDQkpibU11TVJzd0dRWURWUVFERXhKSFpXOVVjblZ6ZENCSGJHOWlZV3dnUTBFd0hoY05NVE13TkRBMU1UVXhOVFUyV2hjTk1UWXhNak14TWpNMU9UVTVXakJKTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNoTUtSMjl2WjJ4bElFbHVZekVsTUNNR0ExVUVBeE1jUjI5dloyeGxJRWx1ZEdWeWJtVjBJRUYxZEdodmNtbDBlU0JITWpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSndxQkhkYzJGQ1JPZ2FqZ3VEWVVFaThpVC94R1hBYWlFWis0SS9GOFluT0llNWEvbUVOdHpKRWlhQjBDMU5QVmFUT2dtS1Y3dXRaWDhiaEJZQVN4RjZVUDd4YlNEajBVL2NrNXZ1UjZSWEV6L1JURGZSSy9KOVUzbjIrb0d0dmg4RFFVQjhvTUFOQTJnaHpVV3gvL3pvOHB6Y0dqcjFMRVFUcmZTVGU1dm44TVhIN2xOVmc4eTVLcjBMU3krckVhaHF5ekZQZEZVdUxIOGdaWVIvTm5hZytZeXVFTldsbGhNZ1p4VVlpK0ZPVnZ1T0FTaERHS3V5Nmx5QVJ4em1aRUFTZzhHRjZsU1dNVGxKMTRyYnRDTW9VL000aWFyTk96MFlEbDVjRGZzQ3gzbnV2UlRQUHVqNXh0OTcwSlNYQ0RUV0puWjM3RGhGNWlSNDN4YStPY21rQ0F3RUFBYU9CNXpDQjVEQWZCZ05WSFNNRUdEQVdnQlRBZXBob2pZbjdxd1ZrREJGOXFuMWx1TXJNVGpBZEJnTlZIUTRFRmdRVVN0MEdGaHU4OW1pMWR2V0J0cnRpR3JwYWdTOHdEZ1lEVlIwUEFRSC9CQVFEQWdFR01DNEdDQ3NHQVFVRkJ3RUJCQ0l3SURBZUJnZ3JCZ0VGQlFjd0FZWVNhSFIwY0RvdkwyY3VjM2x0WTJRdVkyOXRNQklHQTFVZEV3RUIvd1FJTUFZQkFmOENBUUF3TlFZRFZSMGZCQzR3TERBcW9DaWdKb1lrYUhSMGNEb3ZMMmN1YzNsdFkySXVZMjl0TDJOeWJITXZaM1JuYkc5aVlXd3VZM0pzTUJjR0ExVWRJQVFRTUE0d0RBWUtLd1lCQkFIV2VRSUZBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcXZxcElNMXFaNFB0WHRSKzNoM0VmK0FsQmdERkpQdXB5QzF0ZnQ2ZGdtVXNnV00wWmo3cFVzSUl0TXN2OTErWk9tcWNVSHFGQll4OTBTcEloTk1KYkh6Q3pUV2Y4NEx1VXQ1b1grUUFpaGNnbHZjcGpacE55NmplaHNnTmIxYUhBMzBEUDl6NmVYMGhHZm5JT2k5UmRvekhRWkp4anlYT04vaEtUQUFqNzhRMUVLN2dJNEJ6ZkUwMExzaHVrTllRSHBtRWN4cHc4dTFWRHU0WEJ1cG43akxyTE4xbkJ6LzJpOEp3M2xzQTVyc2IwellhSW14c3NEVkNiSkFKUFpQcFpBa2lEb1VHbjhKeklkUG1YNERrallVaU9uTURzV0NPcm1qaTlENlg1MkFTQ1dnMjNqclc0a09WV3plQmtvRWZ1NDNYclZKa0ZsZVcyVjQwZnNnMTJBPT0iXX0.eyJub25jZSI6InZiOTQvNzhleE9IVTRYM0J1bGRoUEhJdnVVVDRoMlJOOXhVaTJXakI0Znc9IiwidGltZXN0YW1wTXMiOjE0NDQ1MDI3NTYyODQsImFwa1BhY2thZ2VOYW1lIjoiY29tLnNuYXBjaGF0LmFuZHJvaWQiLCJhcGtEaWdlc3RTaGEyNTYiOiJ3eUkxZ1dMS1MxMkZyQjBZMGJ4TzVtMktVQXl0ZER4UnprUmRwbUpTMXpNPSIsImN0c1Byb2ZpbGVNYXRjaCI6ZmFsc2UsImV4dGVuc2lvbiI6IkNmcWtoU1dEYjQzbCIsImFwa0NlcnRpZmljYXRlRGlnZXN0U2hhMjU2IjpbIkx4eXEvS0h0TU5DMDQ0aGo3dnErb09nVmNSK2t6M200SWxHYWdsblpXbGc9Il19.rnpWKu8a9KwiOVaDQO_c18yiIRnmLnfCJ_DgLyjEK7GA16ClhpPxuLSBD0kcymRlkWXdMlkpE6_kyJwgq33BruAr_0c_mPhV-4b77glaqrWF5jIrX1BKvvZnUp9yfUaQv4vZKVExX7HAfwO00nWKDiOZY9mi_brB6i8BI-7HzMOI9wdNHfwyy0DIhGroeHtHPiqIdWy7VBrvyUoQRlpZt0J52FqxYQH1cbSo1IO6eeW_RX7wQJyzhIqaHtEmqMlgpkjjnEav6bwpNj3P0TZki-hDDjp6OXcrQ5xYfgFjKlTz0SKqw85lnhFCclmKvHSHjb0hRnY9zlqHR_jQziMNRg&sflag=1&application_id=com.snapchat.android&req_token=930d8f5b6841afd86e0a86eefda3d1747bed4d81198d1a8599b4ce14d6c510eb RESULT: 1 
Warning: First parameter must either be an object or the name of an existing class in /home/u909049881/public_html/src/snapchat_agent.php on line 443`

**Comment by teknogeek** [comment]
proxy is probably banned

**Comment by kripsbro** [comment]
how maximum request a can make until SnapChat will block my ip ?

**Comment by hanschen123** [comment]
Hi, liamcottle
How to pay for increasing your API Rate Limit. I need to buy pro

**Comment by teknogeek** [comment]
it's not a maximum request thing. it's probably the IP is blacklisted

**Comment by liamcottle** [comment]
@hanschen123 Hiya, I got your email. I'm just in the process of setting up the payments page. Cheers.

**Comment by umbreon222** [comment]
I get the same long error as posted by kripsbro but only when I use one snapchat account, when I use another snapchat account it logs in just fine.

**Comment by umbreon222** [comment]
Nevermind, I used a different IP and then both accounts could login. I just find it weird that even if the IP was blacklisted how could one account still login while another couldn't?

**Comment by mgp25** [comment]
you had the auth already...

**Comment by emiliobasualdo** [comment]
@devinwendt of course, the ip is blocked for a certain account, not for all account in the ip.
I have the same problem, can’t figure out how to get unblocked though. Tried VPNs, DHCPs and othe Dynamic ips, no success.

> On 3/11/2015, at 21:16, Devin Wendt notifications@github.com wrote:
> 
> I get the same long error as posted by kripsbro but only when I use one snapchat account, when I use another snapchat account it logs in just fine.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/mgp25/SC-API/issues/222#issuecomment-153531309.

Pilo Basualdo

**Comment by umbreon222** [comment]
@mgp25 It can't be that I had the auth already considering I tried with and without deleting the auth file. The problem is still persisting with only one account working and the other not being able to login. Considering I tried on 2 different machines with different IP addresses with and without various IP anonymizers, are we even sure they are blocking through IP? I ran the bot from a chroot on my phone and it couldn't login but when I used the casper app it could(both using same IP). Forgive me if I'm just being an idiot, but is it possible they ban by device code from the user-agent for specific accounts?

**Comment by HW73** [comment]
Check the username and password is correct, sounds silly but I had that issue a while ago.

**Comment by umbreon222** [comment]
It's definitely not a username password issue either. I find it confusing how snapchat can use a simple IP ban that only works on this PHP script. The account works fine using the same IP from either the casper or snapchat app. I only suspect it to be a user-agent thing because I am guessing that the script sends in as an HTC one and the apps send in as a galaxy S5
