### ISSUE TITLE
Uncaught exception 'CasperException' with message 'error setting certificate verify locations

### ISSUE THREAD

**Issue by tucogit** [mgp25/Snap-API#223]
Hello,

I've just got this error : 

`Fatal error: Uncaught exception 'CasperException' with message 'error setting certificate verify locations: CAfile: ../ca_bundle.crt CApath: none' in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php:163 Stack trace: #0 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php(73): CasperAgent->request('/snapchat/attes...', Array) #1 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAPI.php(73): CasperAgent->get('/snapchat/attes...') #2 C:\inetpub\wwwroot\src\snapchat.php(151): CasperAPI->getSnapchatAttestation('qN2NRC/kQLfBm86...') #3 C:\inetpub\wwwroot\src\snapchat.php(362): Snapchat->getAttestation('logiiiiin', 'password', 1444501775145) #4 C:\inetpub\wwwroot\script\all\lounaaxx.php(126): Snapchat->login('password') #5 {main} thrown in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php on line 163`

Can someone explain it to me ? Because i've the right files at the right place. So what is wrong ? Thanks a lot to provide us this really nice services and support.

**Comment by tucogit** [comment]
Fix: IP banned, need a proxy

**Comment by teknogeek** [comment]
it seems that you have removed the ca_bundle.crt from that parent directory. that file is used to try to fix SSL errors

**Comment by tucogit** [comment]
But my files is present : http://puu.sh/kFoeL/42237b9f2f.png

**Comment by teknogeek** [comment]
ahhh. sec i have to make a code change...

**Comment by tucogit** [comment]
Okey thanks a lot!

**Comment by teknogeek** [comment]
try now

**Comment by teknogeek** [comment]
using the latest commit

**Comment by tucogit** [comment]
exactly the same error with the latest commit

**Comment by tucogit** [comment]
it should work i don't understand

**Comment by teknogeek** [comment]
pull again, just redid the commit

**Comment by tucogit** [comment]
Same error with the latest commit 

``` php
curl_setopt($ch, CURLOPT_CAINFO, __DIR__."..".DIRECTORY_SEPARATOR."ca_bundle.crt");
```

the error : 

`Fatal error: Uncaught exception 'CasperException' with message 'error setting certificate verify locations: CAfile: C:\inetpub\wwwroot\src\Casper-API-PHP..\ca_bundle.crt CApath: none' in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php:163 Stack trace: #0 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php(73): CasperAgent->request('/snapchat/attes...', Array) #1 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAPI.php(73): CasperAgent->get('/snapchat/attes...') #2 C:\inetpub\wwwroot\src\snapchat.php(151): CasperAPI->getSnapchatAttestation('7tv/T7JPeMbVIUZ...') #3 C:\inetpub\wwwroot\src\snapchat.php(362): Snapchat->getAttestation('loggg', 'passw', 1444502906778) #4 C:\inetpub\wwwroot\script\all\lounaa.php(126): Snapchat->login('password') #5 {main} thrown in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php on line 163`

**Comment by tucogit** [comment]
it works fine if I put the fullpath : 

curl_setopt($ch, CURLOPT_CAINFO, "C:\inetpub\wwwroot\src\ca_bundle.crt");

**Comment by teknogeek** [comment]
ok pull one more time xD

**Comment by liamcottle** [comment]
yolo

**Comment by tucogit** [comment]
it's fixed now aha, great job and thanks a loooot :p

**Comment by teknogeek** [comment]
no problemo :+1:
