### ISSUE TITLE
Error 403 ! Help please

### ISSUE THREAD

**Issue by Derpolino** [mgp25/Snap-API#225]
Hello, i have an error, how to resolve it ?

```
[message] => The network you are connected to has been temporarily blocked because of suspicious activity. If you are connected to a VPN, retry after disconnecting from it.
[status] => 403
[logged] =>
```

Help please :/

**Comment by liamcottle** [comment]
The message tells you what the issue is lol.

**Comment by Derpolino** [comment]
There's a way to solve this?

**Comment by Derpolino** [comment]
A vpn might work?

**Comment by mgp25** [comment]
Your profile picture makes perfect sense with this issue.

`[message] => The network you are connected to has been temporarily blocked because of suspicious activity. If you are connected to a VPN, retry after disconnecting from it.`

Means Snapchat has blocked your server/proxy/vpn ip.
