### ISSUE TITLE
Casper.io registration error

### ISSUE THREAD

**Issue by HW73** [mgp25/Snap-API#226]
Hi, when I attempt to create a casper.io account I get the following error.
'An Internal error occurred while sending an Email'

I tried to login to see if the account was created and received another error 'Please click the Activation link sent to your Email Address.'

It's been an hour or so since and haven't received the email, should I keep waiting or is there something over at casper's end?

**Comment by mgp25** [comment]
@HW73 try creating/logging in with the account

**Comment by HW73** [comment]
@mgp25 Hi yeah I've tried this which I mentioned above. I'm not sure what I can do, tried making another account but had the same issue.

**Comment by Chiggins** [comment]
I am also not getting any emails regarding activation.

**Comment by liamcottle** [comment]
Sorry, my mail server wend down while I was sleeping.

I have fixed this issue, and have resent emails to you all.

Sorry for the inconvenience.

**Comment by Chiggins** [comment]
Yup, I got mine maybe an hour or two after I made the comment here. Now if I can just get my python library working, I'll be all set!

**Comment by liamcottle** [comment]
Cool! This could be helpful: https://github.com/teknogeek/Casper-API-Python

**Comment by teknogeek** [comment]
^ i can confirm that my python library works 100% :)

**Comment by HW73** [comment]
Thanks guys, @liamcottle it works now. I forgot to reply sooner. I'll check out the casper api, thank you :)

**Comment by emiliobasualdo** [comment]
@Liamcottle I have not received the activation email.
