### ISSUE TITLE
Uncaught exception 'CasperException' with message... (the cURL request fails)

### ISSUE THREAD

**Issue by emiliobasualdo** [mgp25/Snap-API#228]
Hello guys I understand the both the API and the repository are fully working right now and I truly thank you all for this amazing project, but nevertheless I'm having this problem while downloading snaps using the latest version of the repository.
The account I´m using currently has more than 1300 friends, just clarifying because of possible data limit issues.
I have obtained the API Key and the API Secret and have copied them perfectly.
`$snapchat->getSnaps(true);` this is the code I´m running.
and this is the error I'm getting (the cURL request fails):
`PHP Fatal error:  Uncaught exception 'CasperException' with message 'Operation timed out after 10002 milliseconds with 0 bytes received' in /Users/Pilo/Desktop/SC-API-master/src/Casper-API-PHP/CasperAgent.php:163`

`Stack trace:`

`#0 /Users/Pilo/Desktop/SC-API-master/src/Casper-API-PHP/CasperAgent.php(95): CasperAgent->request('/snapchat/attes...', NULL, Array, true)`
`#1 /Users/Pilo/Desktop/SC-API-master/src/Casper-API-PHP/CasperAPI.php(92): CasperAgent->post('/snapchat/attes...', NULL, Array)`
`#2 /Users/Pilo/Desktop/SC-API-master/src/snapchat.php(152): CasperAPI->getSnapchatAttestation('VuEFQhnAfbn8pJL...')`
`#3 /Users/Pilo/Desktop/SC-API-master/src/snapchat.php(363): Snapchat->getAttestation('xXUserNXx', 'xXPasswdXx, 1444680736999)`
`#4 /Users/Pilo/Desktop/SC-API-master/examples/exampleFunctional.php(22): Snapchat->login('xXPaswdXx')`
`#5 {main}
  thrown in /Users/Pilo/Desktop/SC-API-master/src/Casper-API-PHP/CasperAgent.php on line 163`

Where do think this problem might come from?

**Update:**

I'm sorry, is it possible that I have to upgrade my API Rate Limit?
because messages are sent succesfully, but snaps are not downloaded.

PS  I am now getting: 
`Uncaught exception 'CasperException' with message 'Failed to decode response!' in ..../SC-API-General/src/Casper-API-PHP/CasperAgent.php:169`

**Comment by LanchaBasualdo** [comment]
I'm sorry, is it possible that I have to upgrade my API Rate Limit?
because messages are sent succesfully, but snaps are not downloaded.

**Comment by LanchaBasualdo** [comment]
@liamcottle

**Comment by mgp25** [comment]
@LanchaBasualdo have you logged in more than 120 times in an hour?

**Comment by emiliobasualdo** [comment]
no, since it stopped working on friday I haven't fully used it. Just today probably tried to login a max of 13 times. 
why?

**Comment by Chiggins** [comment]
If you're going to be logging in that much, I recommend you just keep the
auth token and use that. That way no login necessary.

**Comment by emiliobasualdo** [comment]
@chiggins I haven't

**Comment by liamcottle** [comment]
@LanchaBasualdo are you still getting this error if you try now?

**Comment by emiliobasualdo** [comment]
one sec, let me try it

**Comment by liamcottle** [comment]
I've just downloaded the latest version of the library, entered my details and it logs in. Just checking server logs, there doesn't seem to be any downtime while I was out.

**Comment by emiliobasualdo** [comment]
@liamcottle Dude, I'm completely sure its a problem on my end. Thing is you guys might know what it is causing it.
Tried on two different computer with same set up and same accounts and now both have different errors.
Computer 1
`PHP Warning:  First parameter must either be an object or the name of an existing class in /home/pilo/Desktop/Dropbox/SC-API-General/src/snapchat_agent.php on line 443`
Computer 2
`PHP Notice:  Trying to get property of non-object in /Users/Pilo/Desktop/SC-API-master/src/snapchat.php on line 3079`
`PHP Warning:  Invalid argument supplied for foreach() in /Users/Pilo/Desktop/SC-API-master/src/snapchat.php on line 3080`
`PHP Warning:  Attempt to modify property of non-object in /Users/Pilo/Desktop/SC-API-master/src/snapchat.php on line 904`
`PHP Notice:  Trying to get property of non-object in /Users/Pilo/Desktop/SC-API-master/src/snapchat.php on line 907`
`PHP Warning:  Invalid argument supplied for foreach() in /Users/Pilo/Desktop/SC-API-master/src/snapchat.php on line 1039`

**Update:**

Errors vary through time
now I get `PHP Fatal error:  Uncaught exception 'CasperException' with message 'Failed to decode response!' in /home/pilo/Desktop/Dropbox/SC-API-General/src/Casper-API-PHP/CasperAgent.php:169`

**Comment by LanchaBasualdo** [comment]
Errors vary through time
now I get the `PHP Fatal error:  Uncaught exception 'CasperException' with message 'Failed to decode response!' in /home/pilo/Desktop/Dropbox/SC-API-General/src/Casper-API-PHP/CasperAgent.php:169`error

**Comment by Chiggins** [comment]
I've actually been randomly getting that in my Python implementation as
well.

**Comment by liamcottle** [comment]
If you could log the HTTP Code, and the response data at line [166](https://github.com/mgp25/SC-API/blob/master/src/Casper-API-PHP/CasperAgent.php#L166) just before it throws the Exception at line [169](https://github.com/mgp25/SC-API/blob/master/src/Casper-API-PHP/CasperAgent.php#L169) that'd be great.

I can't replicate this error on my end, so if you could do a log like below, for me that would help me out!

``` php
$json = json_decode($result);
if($json == null){
  $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
  echo "Code: ". $code;
  echo "Result: " . $result;
  curl_close($ch);
  throw new CasperException("Failed to decode response!");
}
```

**Comment by liamcottle** [comment]
Also, if you could log the Endpoint it's making the request to :)

**Comment by emiliobasualdo** [comment]
Outputs:

This is the link to the following error:
https://www.dropbox.com/s/bizo0m09ygpvhvx/Output.rtf?dl=0
`Code: 500Result: PHP Fatal error:  Uncaught exception 'CasperException' with message 'Failed to decode response!' in /Users/Pilo/Desktop/Dropbox/SC-API-master/src/Casper-API-PHP/CasperAgent.php:172`

This link has no error, but functions are not accomplished:
https://www.dropbox.com/s/78bda6l56e7ffln/output2.txt?dl=0

**Comment by liamcottle** [comment]
Okay. The response code is 500.

Can you add the parameter "_debug" to your request to my server.

Just add it to the Params array in the `getSnapchatAttestation` `getSnapchatClientAuth` methods.

**Comment by liamcottle** [comment]
You could do this instead.

Change line [43](https://github.com/mgp25/SC-API/blob/master/src/Casper-API-PHP/CasperAPI.php#L43)

From:

```
$response = parent::post("/snapchat/clientauth/signrequest", null, array(
```

To:

```
$response = parent::post("/snapchat/clientauth/signrequest?_debug", null, array(
```

Change line [43](https://github.com/mgp25/SC-API/blob/master/src/Casper-API-PHP/CasperAPI.php#L43)

From:

```
$response = parent::post("/snapchat/clientauth/signrequest", null, array(
```

To:

```
$response = parent::post("/snapchat/clientauth/signrequest?_debug", null, array(
```

**Comment by liamcottle** [comment]
Wrong button... Sorry.

**Comment by LanchaBasualdo** [comment]
@liamcottle  ok, used the line changing method. I'll request a couple of times from different computers.

**Comment by emiliobasualdo** [comment]
@liamcottle  ok, used the line changing method. I'll request a couple of times from different computers.

**Update:**

I'm now getting the first error: `Fatal error: Uncaught exception 'CasperException' with message 'Operation timed out after 10003 milliseconds with 0 bytes received' in /Users/Pilo/Desktop/Dropbox/SC-API-master/src/Casper-API-PHP/CasperAgent.php on line 163`

`CasperException: Operation timed out after 10003 milliseconds with 0 bytes received in /Users/Pilo/Desktop/Dropbox/SC-API-master/src/Casper-API-PHP/CasperAgent.php on line 163
`

**Comment by LanchaBasualdo** [comment]
@liamcottle please tell me if you are receiving the debug

**Comment by liamcottle** [comment]
I can run this all fine, so if you're getting timeout issues, it's an issue on your end as the server is running fine.

However, if you get the previous error, with the Code 500, I'd like to see the response with the added `_debug` param.

**Comment by liamcottle** [comment]
The `_debug` param just outputs the error in the response. I can't see it unless you post it here.

**Comment by emiliobasualdo** [comment]
I'm sorry, my PHP is rusty, how should I do so?

**Comment by liamcottle** [comment]
Exactly the same as this: https://github.com/mgp25/SC-API/issues/228#issuecomment-147555035 But you need to add the `_debug` param to your requests first.

**Comment by emiliobasualdo** [comment]
https://www.dropbox.com/s/z5mei9soo4bv7zs/Output.txt?dl=0
I have added the `_debug`parameter the in line 43

**Comment by liamcottle** [comment]
There's no errors in there.

**Comment by emiliobasualdo** [comment]
Sorry, look at it again

**Comment by liamcottle** [comment]
The server isn't providing the error response, but it should when you give it that param... I'm not sure how to fix this for you dude. Since it's all working fine on the servers I've tested it on just now.

**Comment by emiliobasualdo** [comment]
@liamcottle dam, I understand.
Is it possible that the problem comes from the size of the account as it has more than 1300 friends?
because messages are sent succesfully, but snaps are not downloaded.

**Comment by liamcottle** [comment]
Looking at the stacktrace, the issue is that my server is responding to your request with a `500 Internal Server` error.

This exception is happening before the code makes any requests to Snapchat.

Because it's working fine for everyone else, the data being sent to the server from you must be invalid or something...

... it's not possible for me to know what the issue is without seeing the debug data from the server.

I've made some server changes which should now log these errors on my end.

So could you try again?

**Comment by LanchaBasualdo** [comment]
I'm, it is weird thow that I can successfully log in and send messages and retrieve the list of friends but I can not download the snaps.

**Comment by emiliobasualdo** [comment]
I am, it is weird thow that I can successfully log in and send messages and retrieve the list of friends but I can not download the snaps.

**Update:**

JAJA LOL
problem solved by changing:
from

``` php
$casperKey      = "XXXXXX";
$casperSecret   = "XXXXXXX";
```

to

``` php
$casperKey      = 'XXXXXX';
$casperSecret   = 'XXXXXXX';
```

da fuck

**Comment by emiliobasualdo** [comment]
Thanks @liamcottle for the time, and I'm sorry for the stupidity of the problem

**Comment by liamcottle** [comment]
I don't understand how that would cause it, but glad it's fixed.

**Comment by emiliobasualdo** [comment]
Believe me, neither do I

**Comment by emiliobasualdo** [comment]
Error started to appear again, there is al ready an open issue on this topic so I wont re open it. But please might taking a look at it?

**Comment by abood1001** [comment]
Hello i have bug :(
i still can't logging
 Fatal error: Uncaught exception 'CasperException' with message 'API Response: [503] Attestation Service Unavailable' in ///public_html/SC-API-master/src/Casper-API-PHP/CasperAgent.php:179 Stack trace: #0 /home4//public_html/SC-API-master/src/Casper-API-PHP/CasperAgent.php(95): CasperAgent->request('/snapchat/attes...', NULL, Array, true) #1 /home4/abdullah/public_html/SC-API-master/src/Casper-API-PHP/CasperAPI.php(92): CasperAgent->post('/snapchat/attes...', NULL, Array) #2 /home4//public_html/SC-API-master/src/snapchat.php(152): CasperAPI->getSnapchatAttestation('pJB/+nrPLynIc2U...') #3 /home4//public_html/SC-API-master/src/snapchat.php(363): Snapchat->getAttestation('xxxxxxxx', 'xxxxxx', 1.xxxxxxxx+12) #4 /home4/abdullah/public_html/SC-API-master/examples/exampleBots/friendBot.php(17): Snapchat->login('xxxxx') #5 {main} thrown in /home4//public_html/SC-API-master/src/Casper-API-PHP/CasperAgent.php on line 179

i do everything good but i am still to fix it 

:(
i can't 
/
also i need to make bypass in .vbnet

/
i do this coded 
by me
<?
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,"https://api.casper.io/snapchat/attestation/attest");
curl_setopt($ch, CURLOPT_POST, 1);

curl_setopt($ch, CURLOPT_POSTFIELDS,$vars);  //Post Fields
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$headers = array();
$headers[] = 'X-Casper-API-Key:xxxxxxxx';
$headers[] = 'X-Casper-xxxxx:xxxxxxxx';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8';
$headers[] = 'Accept-Encoding: gzip, deflate';
$headers[] = 'Accept-Language: en-US,en;q=0.5';
$headers[] = 'Cache-Control: no-cache';
$headers[] = 'Content-Type: application/x-www-form-urlencoded; charset=utf-8';
$headers[] = 'Host: https://api.casper.io/snapchat/attestation/attest';
$headers[] = 'Casper-API-PHP/1.0.0';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$alajman_output = curl_exec ($ch);
curl_close ($ch);
echo  $alajman_output ;
?>

you need to add curl to vrif  SSL

**Comment by abood1001** [comment]
also
Fatal error: Uncaught exception 'CasperException' with message 'API Response: [401] Invalid X-Casper-Signature' in /home4//public_html/SC-API-master/src/Casper-API-PHP/CasperAgent.php:179 Stack trace: 
i get this msg

 [401] Invalid X-Casper-Signature
i am sure all info
crrert
