### ISSUE TITLE
Failed to decode response in Casper

### ISSUE THREAD

**Issue by tucogit** [mgp25/Snap-API#229]
Hello.

I've got this error half the time when i try to send a new story.. There is no way to solve it ? If I buy a premium account on the API or something.. Coz it's pretty shitting when I try to make a good schedule etc

```
Fatal error: Uncaught exception 'CasperException' with message 'Failed to decode response!' in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php:169 
Stack trace: #0 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php(95): CasperAgent->request('/snapchat/attes...', NULL, Array, true) 
#1 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAPI.php(92): CasperAgent->post('/snapchat/attes...', NULL, Array) 
#2 C:\inetpub\wwwroot\src\snapchat.php(151): CasperAPI->getSnapchatAttestation('J7eKe0A50q/2mrB...') 
#3 C:\inetpub\wwwroot\src\snapchat.php(362): Snapchat->getAttestation('loging', 'snappw', 1444746547783) 
#4 C:\inetpub\wwwroot\script\all\lisa.php(200): Snapchat->login('snapsnap') #5 {main} thrown in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php on line 169
```

**Comment by tucogit** [comment]
Fatal error: Uncaught exception 'CasperException' with message 'Failed to decode response!' in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php:169 Stack trace: #0 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php(95): CasperAgent->request('/snapchat/attes...', NULL, Array, true) #1 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAPI.php(92): CasperAgent->post('/snapchat/attes...', NULL, Array) #2 C:\inetpub\wwwroot\src\snapchat.php(151): CasperAPI->getSnapchatAttestation('J7eKe0A50q/2mrB...') #3 C:\inetpub\wwwroot\src\snapchat.php(362): Snapchat->getAttestation('loging', 'snappw', 1444746547783) #4 C:\inetpub\wwwroot\script\all\lisa.php(200): Snapchat->login('snapsnap') #5 {main} thrown in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php on line 169

**Comment by emiliobasualdo** [comment]
Got the same error today, several times

**Comment by tucogit** [comment]
Yes Lancha It's pratically impossible to send story with the API today

**Comment by mgp25** [comment]
I dont know what you are doing, but its working perfectly for me

**Comment by Chiggins** [comment]
@mgp25 I think it's an issue with Liam's set up. I've gotten it randomly
before on my Python implementation. I'm not at a computer now to do any
debugging to get more information though.

**Comment by tucogit** [comment]
3 new try, 3 new fails with this error..

**Comment by tucogit** [comment]
Can we have some news about this issus ?

**Comment by emiliobasualdo** [comment]
@Tucogiy @chiggins Have you guys received the activation email from the casper api when creating an account?

**Comment by LanchaBasualdo** [comment]
Sorry, @tucogit

**Comment by tucogit** [comment]
@LanchaBasualdo Yes absolutly, I've activate it

**Comment by liamcottle** [comment]
Just checked over the server logs I enabled yesterday, I have found the issue causing this, and have patched it. Cheers.

**Comment by emiliobasualdo** [comment]
Thanks

**Comment by tucogit** [comment]
Thanks a lot @liamcottle, and thx for your amazing API!

**Comment by liamcottle** [comment]
@tucogit So you're happy to have me hurry up and fix issues for you, but you still want to bypass the Rate Limiting by breaking my ToS? Thanks...

**Comment by emiliobasualdo** [comment]
@Liamcottle , I'm getting the exception thrown at line 176, buy with code 200 this time. 

Ps: I have not received the email for activation of the account. Maybe it something to do with that?

**Comment by liamcottle** [comment]
I'm out for lunch, will sort this when I get back :)

**Comment by LanchaBasualdo** [comment]
Lol I'm at dinner. Of course, when you can

**Comment by liamcottle** [comment]
Should be fixed now :)

**Comment by emiliobasualdo** [comment]
@liamcottle thanks.
But I m getting this now:

`Uncaught exception 'CasperException' with message 'Operation timeout after 10000 milliseconds with 0 bytes received'` `... in CasperAgent line 167`

Is this mine?

**Comment by teknogeek** [comment]
**YOUR INTERNET IS FUCKED. PLZ FIX INSTEAD OF COMPLAINING THXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX**

**Comment by emiliobasualdo** [comment]
This would be the line. : `throw new CasperException($error)`  under `if the curl request fails, return FALSE`

**Comment by teknogeek** [comment]
so. why would a curl request fail, do tell

**Comment by emiliobasualdo** [comment]
Thanks @teknogeek for telling me that my internet is fucked. That is the only thing I was needed to be told, since my debug only displayed that error. 
And thanks @liamcottle for your time. It is an amazing API you have created.

**Comment by teknogeek** [comment]
you're welcome. that's all you should need to know. if the curl request failed for you...and it worked for everyone else...and the connection timed out.....plz do the math
