### ISSUE TITLE
"Your login temporarily failed"...

### ISSUE THREAD

**Issue by md726** [mgp25/Snap-API#23]
Since last night I'm getting that when logging in to Snapchat:

```
Array
(
    [error] => 0
    [data] => stdClass Object
        (
            [message] => Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)
            [status] => -103
            [logged] =>
        )
)
```

I already changed my IP address (it's now in a completly different range) and I used a new user account, but still the same error. Is it still working on your computers or do you have any ideas what I could try?

Thanks,
Mand

**Comment by Howardno** [comment]
I am seeing the same issue.

Howard

**Comment by mands72** [comment]
I temporary switched to https://github.com/martinp/pysnap and everything is working fine there, so I guess it's really not my IP and not my account. Since it was working for about 2 weeks and stopped without any change on my side, I'm pretty sure they did something on their side.

**Comment by Mxchael** [comment]
Same issue here is occurring. Also tried changing IP and using different accounts.

Seems Snapchat is detecting how we login.

**Comment by Klievan** [comment]
Seems like they've added a couple more checks on android since they mention google accounts. Might have to switch the header over to iOS?

**Comment by mgp25** [comment]
@IvanTheBuilder Yes, im going to post a solution soon.

Regards

**Comment by mgp25** [comment]
Send me an email with your login data, and ill see if it works from my side.

Regards

**Comment by mgp25** [comment]
Issue #21

**Comment by mgp25** [comment]
Fixed: https://github.com/mgp25/Snap-API/commit/a0222d6d82fc4e9ca4f16e07b92ddc737a7a4a2e

**Comment by md726** [comment]
After your fix 2 days before it was working until yesterday evening. Now I'm getting the same error again :(

**Comment by mgp25** [comment]
I know, we are working on this

Regards

**Comment by Mxchael** [comment]
For people impatient you can log the account token by creating a google account on an android device (or logging into one) then update this line https://github.com/mgp25/Snap-API/blob/master/src/snapchat.php#L140 which will temporarily fix it.

**Comment by mgp25** [comment]
Working again

Regards

**Comment by NotTo60** [comment]
I didnt understand what to do...

**Comment by Boy300** [comment]
@mgp25 please what's your email let me send mine. I need sit urgently

**Comment by Boy300** [comment]
I couldn't log in for weeks
