### ISSUE TITLE
Videos fail to post

### ISSUE THREAD

**Issue by HW73** [mgp25/Snap-API#230]
Hi, I've got a bot set up to post snaps on it's story which have been sent to the account. I've had a problem for the last week where videos won't post. Some videos will post but some won't, I think it's because it doesn't recognise the format, any help would be great as I have to manually view them to let the user post again. 

Another issue I have which happened a few hours ago is that the snaps stop posting even though I have the script set up to run every 5 minutes, I had to manually write "curl http://..domain/snapstory/bot.php" for it to work. 

Thanks guys, really appreciate the work you've done.

**Comment by mgp25** [comment]
Seems to be an issue at your end, not API issue

Regards

**Comment by HW73** [comment]
I assumed so, didn't know if you had come across this issue before and had a solution. If I find a solution I'll write it in this issue for others

Thanks
