### ISSUE TITLE
Issue for Tekno

### ISSUE THREAD

**Issue by liamcottle** [mgp25/Snap-API#231]
Hai.

**Comment by teknogeek** [comment]
YOU FUCKING FUCK SHIT FUCKER FUCK FUCK

**Comment by teknogeek** [comment]
LET'S MAKE A STEP BY STEP GUIDE ON HOW TO DEBUG.

# MKAY?

**Comment by teknogeek** [comment]
# STEP 1
DAMN WHAT'S MY PROBLEM? OH SOMETHING ISN'T WORKING, OKAY

**Comment by teknogeek** [comment]
# STEP 2
WHERE IS THE PROBLEM OCCURRING? HMMMMMMMMMMMMMMMMMMMMMMMMMMMMM LET'S GO TO THE CODE SHALL WE

**Comment by teknogeek** [comment]
# STEP 3
OH HEY THERE'S THE FUCKING LINE OF CODE WHERE IT ISN'T WORKING. I WONDER

##### WHAT THE FUCK

## CALLS THAT CODE

# HUH.

**Comment by teknogeek** [comment]
# STEP 4
OH OK WE'VE USED OUR SUPERB BRAINPOWER TO UNCOVER THE MAGICAL SECRETS OF FUCKING CTRL+F AND FOUND WHERE IT'S BEING CALLED

**Comment by Chiggins** [comment]
I'm sure that you guys are frustrated with the numbers of the same issues and such, but I'm sure there are better ways to go about it than this. This is pretty unprofessional and doesn't exactly reflect well.

**Comment by teknogeek** [comment]
# STEP 5
OK OK SO BASICALLY SOMETHING IS CALLING THIS AND IT ISN'T WORKING.

### THAT MEANS...
### THAT SOMETHING..
### IN THERE...





### IS FUCKED UP

**Comment by liamcottle** [comment]
I'm not worried, I enjoy helping. However, I enjoy pissing @teknogeek off much more.

**Comment by teknogeek** [comment]
# STEP 6
#### DEBUG.
#### THE FUCKING.
## VARIABLES

**Comment by teknogeek** [comment]
# STEP 7
***WOW*** NOW WE KNOW WHAT'S GOING ON USING SOME CREATIVE THINKING AND EDUCATED GUESSES

**Comment by teknogeek** [comment]
# STEP 8
## TADAAAAAAAAAAAAA
YOU SUCCESSFULLY JUST FUCKING SOLVED YOUR OWN PROBLEM

**Comment by teknogeek** [comment]
# STEP 9
you're welcome :) guide provided free of charge

**Comment by liamcottle** [comment]
;)

**Comment by teknogeek** [comment]
;)
