### ISSUE TITLE
Having issues creating Ham Sandwich

### ISSUE THREAD

**Issue by jladuval** [mgp25/Snap-API#232]
Hi guys,

I'm following the instructions I found at http://www.foodnetwork.com/recipes/food-network-kitchens/ultimate-ham-sandwich-recipe.html and I'm having a few issues.

My Application uses Avocado as well as mayonnaise so I have to spread it on the outside of the sandwich. This works fine except now I have Avocado everywhere and my dog keeps hopping up onto the bench to eat it. It's incredibly unhygienic. Do you guys have any ideas on how to solve this? Thanks.

**Comment by teknogeek** [comment]
sure Jacob! Personally, i have found that the easiest way to fix this problem is to teleport to the 4th dimension, Xalgrag, because there are no dogs there. Just make sure you take your ingredients with you because it's a one way trip! :wink: Let me know how it turns out! :smile:

**Comment by jladuval** [comment]
Cheers tekno, I'll give that a try. If it works I'll submit a PR.

**Comment by teknogeek** [comment]
Sounds good!
