### ISSUE TITLE
When requesting stories the story_id is fetched correctly but the blob is not

### ISSUE THREAD

**Issue by hueypeard** [mgp25/Snap-API#233]
I noticed my of my output files were junk and had a quick look. Traced it down to line `2529` in `snapchat.php`. `/bq/story_blob` seems to return the following data (but the `story_id` is valid)

``` html
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>404 NOT_FOUND</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: NOT_FOUND</h1>
</body></html>
```

If any more information is required please let me know.
Thanks!

**Comment by mgp25** [comment]
@hueypeard post full debug log please

**Comment by hueypeard** [comment]
Is there anywhere I can post the log privately? Thanks

**Comment by mgp25** [comment]
@hueypeard send mail

**Comment by mgp25** [comment]
@hueypeard im going to check it later today

Regards

**Comment by mgp25** [comment]
Works perfectly

Regards
