### ISSUE TITLE
Unauthorised errror give me

### ISSUE THREAD

**Issue by pank123** [mgp25/Snap-API#234]
I have applied valid credential of casper but still its give me error.
Its give me anauthorised error and give me below error.

```
Warning: Invalid argument supplied for foreach() in D:\Xampp\htdocs\snapchtapi\src\snapchat.php on line 3080
```

```
REQUEST TO: https://sc-analytics.appspot.com/post_events
```

 DATA:

``` json
 {"common_params":{"user_id":"feae75feec7683338a95a34d0fd9cf2b5b2cac4da8b71a94c52da9d03214d0b2","city":"Unimplemented","sc_user_agent":"Snapchat\/9.16.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip)","session_id":"00000000-0000-0000-0000-000000000000","region":"Unimplemented","latlon":"Unimplemented","friend_count":-1,"country":"Unimplemented"},"events":[{"event_name":"APP_OPEN","event_timestamp":1444937177263,"event_params":{"open_state":"NORMAL","intent_action":"null"}}],"batch_id":"9e84288e-0c58-0007-0000-64da5d1c702c-Snapchat91620HTCOneAndroid502482424221gzip1444937177263"} 
```

**Comment by mgp25** [comment]
@pank123 post full debug log please

**Comment by kkai4u** [comment]
Try deleting Auth files

**Comment by pank123** [comment]
I am facing follwing error when get the friend list. last time it was work but currenlty give me this error. please give me solution on this.

in REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/all_updates Sent Request info: POST /loq/all_updates HTTP/1.1 User-Agent: Snapchat/9.16.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip) Host: feelinsonice-hrd.appspot.com Accept: _/_ Accept-Language: en Accept-Locale: en_US X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ4OWZjMDdhNWUxY2VmYjg3N2NmNWY5OWJkNGIzNjUwNmNiYjQxMzcifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTEwNzAwMjgxMjM2MDc5MTY3MjYyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoia2V5dXIyMzM4M0BnbWFpbC5jb20iLCJpYXQiOjE0NDUwMTcxMDQsImV4cCI6MTQ0NTAyMDcwNCwibmFtZSI6ImtleXVyIHBhdGVsIiwicGljdHVyZSI6Imh0dHBzOi8vbGg1Lmdvb2dsZXVzZXJjb250ZW50LmNvbS8tRms0UktUUmQ0cW8vQUFBQUFBQUFBQUkvQUFBQUFBQUFBOTAvcFFDSzdzMDVEcG8vczk2LWMvcGhvdG8uanBnIiwiZ2l2ZW5fbmFtZSI6ImtleXVyIiwiZmFtaWx5X25hbWUiOiJwYXRlbCJ9.IkP_7pim_NhtGHr6ZWxXygTtlryvh-XUpjqRFECslf5qLHscv2epDTF8qrchorudlSgLKldXOiG6_aQuHs0S8g4b9-IWxZCf-KIccbCUBY-WkMiiIhPNAoVUScmmgtdOnHNRCYoduABo7pC7hhAWc1h4tE2Coj5hbVYSCdDzkkYx4GaT0w61RTsmdxBoJDxseGbLhr-vGQmNLTGGbyKnpJZSt6FYJlvBbmNvo9q1HwICR9Vtt6dgY7MDt5yRJkheG3mklEa5pjNKdsd1GRt79D8RNk7eL1r92lqAhVcRlJf-eRim2w45fW6wiDggyzgBnwDRGws-agrEAukBa6UPYw Content-Length: 181 Content-Type: application/x-www-form-urlencoded DATA: timestamp=1445017101088&username=keyur23383&height=1280&width=720&max_video_height=640&max_video_width=480&req_token=171c32847041d20b7ab3b86ba5225b31213e09398edf5c1e7c58835cd015165c RESULT:
Error: UNAUTHORIZED

Notice: Trying to get property of non-object in D:\Xampp\htdocs\snapchtapi\src\snapchat.php on line 3079

Warning: Invalid argument supplied for foreach() in D:\Xampp\htdocs\snapchtapi\src\snapchat.php on line 3080
REQUEST TO: https://sc-analytics.appspot.com/post_events DATA: {"common_params":{"user_id":"feae75feec7683338a95a34d0fd9cf2b5b2cac4da8b71a94c52da9d03214d0b2","city":"Unimplemented","sc_user_agent":"Snapchat\/9.16.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip)","session_id":"00000000-0000-0000-0000-000000000000","region":"Unimplemented","latlon":"Unimplemented","friend_count":-1,"country":"Unimplemented"},"events":[{"event_name":"APP_OPEN","event_timestamp":1445017101088,"event_params":{"open_state":"NORMAL","intent_action":"null"}}],"batch_id":"f21a65cc-9a24-0000-03cc-161a0bb69602-Snapchat91620HTCOneAndroid502482424221gzip1445017101088"} REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/all_updates Sent Request info: POST /loq/all_updates HTTP/1.1 User-Agent: Snapchat/9.16.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip) Host: feelinsonice-hrd.appspot.com Accept: _/_ Accept-Language: en Accept-Locale: en_US X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ4OWZjMDdhNWUxY2VmYjg3N2NmNWY5OWJkNGIzNjUwNmNiYjQxMzcifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTEwNzAwMjgxMjM2MDc5MTY3MjYyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoia2V5dXIyMzM4M0BnbWFpbC5jb20iLCJpYXQiOjE0NDUwMTcxMDQsImV4cCI6MTQ0NTAyMDcwNCwibmFtZSI6ImtleXVyIHBhdGVsIiwicGljdHVyZSI6Imh0dHBzOi8vbGg1Lmdvb2dsZXVzZXJjb250ZW50LmNvbS8tRms0UktUUmQ0cW8vQUFBQUFBQUFBQUkvQUFBQUFBQUFBOTAvcFFDSzdzMDVEcG8vczk2LWMvcGhvdG8uanBnIiwiZ2l2ZW5fbmFtZSI6ImtleXVyIiwiZmFtaWx5X25hbWUiOiJwYXRlbCJ9.IkP_7pim_NhtGHr6ZWxXygTtlryvh-XUpjqRFECslf5qLHscv2epDTF8qrchorudlSgLKldXOiG6_aQuHs0S8g4b9-IWxZCf-KIccbCUBY-WkMiiIhPNAoVUScmmgtdOnHNRCYoduABo7pC7hhAWc1h4tE2Coj5hbVYSCdDzkkYx4GaT0w61RTsmdxBoJDxseGbLhr-vGQmNLTGGbyKnpJZSt6FYJlvBbmNvo9q1HwICR9Vtt6dgY7MDt5yRJkheG3mklEa5pjNKdsd1GRt79D8RNk7eL1r92lqAhVcRlJf-eRim2w45fW6wiDggyzgBnwDRGws-agrEAukBa6UPYw Content-Length: 131 Content-Type: application/x-www-form-urlencoded DATA: type=android×tamp=1445017103410&username=keyur23383&req_token=171bdf88e641bbfb7a099d60a4237e21d63509338e5e2c1bcc58705cd615108c RESULT:

**Comment by mgp25** [comment]
@pank123 wrong auth, remove auth data, if running in server, ip could be blocked thats it

**Comment by emiliobasualdo** [comment]
1 question regarding that @liamcottle:
How is the log in rate counted?
Per auth.data created? Or per log in using the same auth?

**Comment by pank123** [comment]
But how can i delete the auth data can you please guide me

**Comment by emiliobasualdo** [comment]
Read the wiki. It in the auth folder inside src.

**Comment by pank123** [comment]
ok thanks
