### ISSUE TITLE
Not receiving snaps from friends

### ISSUE THREAD

**Issue by Chiggins** [mgp25/Snap-API#235]
I know this isn't exactly a bug/issue with SC-API but I figure that I'll post this here since it'll be seen by a handful of knowledgeable people.

I have a Snapchat account of somewhere around 6,000 friends. Lately I've been hearing from some people that even though we're both friends with each other, they'll send me a snap and I never end up receiving it, and to them it looks like it will go on unopened. Has anyone else experienced this and been able to find a way to fix this? It has been becoming fairly annoying.

Thanks!

**Comment by mgp25** [comment]
@Chiggins if you dont receive the snap, is clearly not an API related issue, anyway, you should be able to retrieve using the API the data and get the snap, keep in mind that with such amount of friends, the snap queue will be big.

You can check all the info of your account using get updated

Regards

**Comment by Chiggins** [comment]
Yeah, I know it's not an API issue at all. I've logged into the official snapchat app and had people send me snaps while they're with me and I just 100% don't receive them. It's like some people are shadow-banned from my account or something. Just thought I'd post here and see if anyone knew of anything like this or anything.

**Comment by mgp25** [comment]
@Chiggins im not sure, but maybe Snapchat rises flags in the server depending the acitvities and behaviour of your account.

I added the `info` tag

**Comment by LanchaBasualdo** [comment]
@Chiggis could you give me your email?

**Comment by Chiggins** [comment]
@LanchaBasualdo It's under my profile
