### ISSUE TITLE
Unauthorised error

### ISSUE THREAD

**Issue by sraboni** [mgp25/Snap-API#236]
Hello
I can login with Snapchat API, but when I am trying add a new friend , I am getting unauthorized error. Can you please explain why.

I am using latest API with Casper API key and secret. But still  it is showing error.
Need help on this. Please.

**Comment by mgp25** [comment]
Please post debug log...

**Comment by sraboni** [comment]
Please check the log below:

REQUEST TO: https://feelinsonice-hrd.appspot.com/bq/friend

Sent Request info: POST /bq/friend HTTP/1.1
User-Agent: Snapchat/9.16.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: _/_
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ4OWZjMDdhNWUxY2VmYjg3N2NmNWY5OWJkNGIzNjUwNmNiYjQxMzcifQ
.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmF
xb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTA1OTE4MjQ0OTI0NDAwODc1MTcyIiwiZW1haWxfdmV
yaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2d
sZXVzZXJjb250ZW50LmNvbSIsImhkIjoibXlwaHBkZXZlbG9wZXJzLmNvbSIsImVtYWlsIjoic3JhYm9uaWNoYWtyYWJvcnR5LnN
ickBteXBocGRldmVsb3BlcnMuY29tIiwiaWF0IjoxNDQ1MDAyMDExLCJleHAiOjE0NDUwMDU2MTEsIm5hbWUiOiJTcmFib25pIENoYWtyYWJvcnR5IiwiZ2l2ZW5fbmFtZSI6IlNyYWJvbmkiLCJmYW1pbHlfbmFtZSI6IkNoYWtyYWJvcnR5In0
.Z0_zg_QGJK0bZZpTrgFoVwHirp3AQgdRyi1dBNFmsml5z0JwSjgxTmIboFPJZ--faBHGk-_K4WNXjiRgSLgJzE-Kzbxeiw4ll-2
RF_YR96UcqfNp2LaltSeShilb3pjDXijpmJ156LFShHxguEdQ42s8xbd-I0viwtxkORIhnneu-otlt1HwfYu0oJVM0UAWgPhXHRw
EDhOxHf2XzVwnjIEvHjX0qgfG_SqLZPDo3IVWRnUvgP_37U0v9EQvswb0gGQAR9kP1v6VUU9PWWGBj0oQxqGy1RPPZT1ugt1CvJnqUPX9nXlXBP0m4ZNZ1KBcfsl7SMnXQbluyVRk5X_OfA

Content-Length: 185
Content-Type: application/x-www-form-urlencoded

DATA: action=add&friend=rimliroy&timestamp=1445002026792&username=sraboni.mca%40gmail.com&added_by=ADDED_BY_USERNAME
&req_token=15704ea9f1563f1d051c1e6fc3594b79b5282e6af14b918514ab5888f7684385
RESULT: <html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 FORBIDDEN</title>
</head>
<body text=#000000 bgcolor=#ffffff>

<h1>Error: FORBIDDEN</h1>

</body></html>

**Comment by mgp25** [comment]
@sraboni post  full debug log

**Comment by mgp25** [comment]
@sraboni remove auth data, try again, if running in a server, ip could be blocked.

For further support, post a pastebin or gist with full debug log

Regards
