### ISSUE TITLE
How to upload video via snap chat api I am facing issue.

### ISSUE THREAD

**Issue by pank123** [mgp25/Snap-API#237]
``` php
$videoPath = $_FILES['file']['tmp_name'];   //This is my video tmp name
 $snapchat->setStory($videoPath);
$snapchat->setStory($videoPath, 10, "This is my story")
```

Please help me how to upload video file when i am upload by above code its not work for me.
I am uplading mp4 file.

**Comment by mgp25** [comment]
@pank123 quote the code please.

This a programming issue, i recommend you to see what really `$_FILES['file']['tmp_name']` returns you. There are examples in the wiki.

Regards
