### ISSUE TITLE
Casper API down for Server Updgrades

### ISSUE THREAD

**Issue by liamcottle** [mgp25/Snap-API#239]
Hi all,

The Casper server (*.casper.io) will be completely offline for the next 30 minutes.

I am upgrading the RAM, and a few other things.

Due to the increase in API usage, I've seen that during certain hours 7AM-11:30AM (NZDST) (the requests time out, or take longer than the 10 seconds), this is caused by the server not having enough memory to handle all the requests.

During the time the server is offline for maintenance, you will not be able to get any Attestation or ClientAuth signatures. You'll need to wait until the server is back online.

You will most likely know when it's all completed, since the API will start responding again, however I will update you all when it's done.

Cheers.

**Comment by Chiggins** [comment]
You're the dude. If I was over in NZ I'd buy you a beer or twelve!

**Comment by nshung** [comment]
oh.. that's why I am getting all these errors!

**Comment by emiliobasualdo** [comment]
@liamcottle thanks. Respect for you man
Cheers

**Comment by liamcottle** [comment]
Everything should be working as expected now.

**Comment by SergioCantero** [comment]
I LOVE YOUU!!! THANKS FOR CREATE THIS AWESOME APP THANK YOU A LOT.
