### ISSUE TITLE
video upload issue mp4

### ISSUE THREAD

**Issue by pank123** [mgp25/Snap-API#240]
Hello 
I am trying to upload mp4 video size is around 2 mb but somehow its not upload in user story.
Images is working fine.
Video upload behaviour is abnormaly. Sometime its upload and sometime not.
is there any way to know media is upload or not on api like any status from api .?
Please let me know if you need any

Thanks

**Comment by mgp25** [comment]
@pank123 debug log?

**Comment by pank123** [comment]
http://prntscr.com/8u09hq
http://prntscr.com/8u09p5

Please find the attachment my log screenshot.
for video upload its not working

**Comment by mgp25** [comment]
@pank123 can you use pastebin or similar and post text instead of image? Also, post full debug log so i can see where does the error occur

**Comment by pank123** [comment]
I cant upload text file here can u please send me your email address so i can send you text log there
video upload behaviour is totally different.

**Comment by mgp25** [comment]
@pank123 use this: https://gist.github.com/

**Comment by pank123** [comment]
is there any limit for video upload
i cant upload video more than 1 mb. there is any limitation ?

**Comment by mgp25** [comment]
@pank123 yes, there is limitation make sure its under 10 seconds durations, If its longer you can always split it into multiple parts

Regards

**Comment by pank123** [comment]
I know about 10 second.
I am asking about size there is limitation for size i cant able to upload more than 1 mb video on snapchat api.

Thanks

**Comment by liamcottle** [comment]
@pank123 You will need to create MP4's of multiple sizes, and test this for yourself. We don't know what the limits are.

**Comment by liamcottle** [comment]
@pank123 Please refrain from posting duplicate questions and creating duplicate issues.
