### ISSUE TITLE
Login Problem using Casper API

### ISSUE THREAD

**Issue by kripsbro** [mgp25/Snap-API#241]
[message] => Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :) [status] => -103 [logged] =>

**Comment by hako** [comment]
It works on my end, could you please try again? If the error still persists, please submit a debug log.

**Comment by kripsbro** [comment]
REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id

Sent Request info: POST /loq/device_id HTTP/1.1
User-Agent: Snapchat/9.16.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: _/_
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZhMWJkYjlkZjVkMTAxZDg0NDI1NWE3MGQ1MzI2NTNhMzAxNDUwMDQifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTE4MTczNjg4MTk4MDkzMTIxMzU0IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoibGFzZGthc3Frd3dxa2VAZ21haWwuY29tIiwiaWF0IjoxNDQ1NzE1OTczLCJleHAiOjE0NDU3MTk1NzN9.Yr1CCx1ZcuSVvNUklSNJCNW7YU_CwqA-lNHT_ErMLE5-rgq-Q_rQLfeoQxRMoF9LNv4wCHuz7RjKxpm-k0NnIUvobmA6qqhy5udCq4fzd3ylGRDhEe_s3CwiUlmxJmesx1IflBUV5eWpeWsPhWEd-2D4QaEKmlZbWg9rBLMiLFl8OYAWyHstYNiFbKWnzr5O3MniicjKh8qghO_3J_mQVwB2PeC22v1Zfabb7hPpqnCdGotP5jd2dHAWFNnr2iLpp4Hh9NjXpSyNMfZgQOQNGfvfu0kkTzjf1xWyEluqUts-97XIi0K07puQVOiWdCZm7PKIlAJB124FYoe3-VlEog
Content-Length: 98
Content-Type: application/x-www-form-urlencoded

DATA: timestamp=1445715988437&req_token=9305b158d4e1b7386ee50aeff4ad878412e14d841935ca8e29b49d14d4c5125b
RESULT: {"dtoken1i":"00001:C9729/CPTHOkGeqYd7A9pTBkgwL6UpqxIJhCn4MpxKWlN7go7g2o7HH2n8kULRwA","dtoken1v":"7y59rd2gwZCmSo5mrZT5KfSuxnMFgmyJChBwAMrwlaY\u003d"}

REQUEST TO: https://android.clients.google.com/auth
Array
(
    [device_country] => us
    [operatorCountry] => us
    [lang] => en_US
    [sdk_version] => 19
    [google_play_services_version] => 7097038
    [accountType] => HOSTED_OR_GOOGLE
    [Email] => lasdkasqkwwqke@gmail.com
    [service] => audience:server:client_id:694893979329-l59f3phl42et9clpoo296d8raqoljl6p.apps.googleusercontent.com
    [source] => android
    [androidId] => 378c184c6070c26c
    [app] => com.snapchat.android
    [client_sig] => 49f6badb81d89a9e38d65de76f09355071bd67e7
    [callerPkg] => com.snapchat.android
    [callerSig] => 49f6badb81d89a9e38d65de76f09355071bd67e7
    [EncryptedPasswd] => AFcb4KR8QmuDMe1bZhK6oS5iTtUIP9XUgLu7is6X-pNngfFNyqbEtdOmGw6eCrup5Ii6UctbZxNUFKD5PmNYxqs762b0_iwHonkFf_Nv3nc8-GYD28LpqohOyLhrm5XyXDWIFfwX7dHpHmPc3X5sEb417b7NS90sMib7glgskv8x-Pqxfw==
)
DATA: 1
RESULT: Auth=eyJhbGciOiJSUzI1NiIsImtpZCI6IjZhMWJkYjlkZjVkMTAxZDg0NDI1NWE3MGQ1MzI2NTNhMzAxNDUwMDQifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTE4MTczNjg4MTk4MDkzMTIxMzU0IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoibGFzZGthc3Frd3dxa2VAZ21haWwuY29tIiwiaWF0IjoxNDQ1NzE1OTg4LCJleHAiOjE0NDU3MTk1ODh9.C_YFuL3bLuabaDvPLpBpFbmNduzQAx2STH9IFlk8RSjbi5MfDdknQpfpb1ePA-klfpnAyoyB1jOh6iqh2CNomcmd2ztMjRgXVloDoBG62ZL3umRAPtiBCEuRTs2L_e1jVQpoOcNFA8PUqddzQMH82UAcJoIyeTgjVCMHbOgERYfntnrZT7vu6OIuvwKiJMLkPSiKmScJZpqFmKfUuUHsQxZd5-VVWCkJROgKubsOg-eQKzv6YneMaATU9LFXFuvNLKdHDLvLhnEqMTgXRZJGeDhNnIT5a-8iS9OEIeQexbx4ILWmHKmZW4IL5UrH--9qEeuSGbQ-r15RDVvEa2txDA
issueAdvice=auto
Expiry=1445719588
storeConsentRemotely=1

REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/login

Sent Request info: POST /loq/login HTTP/1.1
User-Agent: Snapchat/9.16.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: _/_
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZhMWJkYjlkZjVkMTAxZDg0NDI1NWE3MGQ1MzI2NTNhMzAxNDUwMDQifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTE4MTczNjg4MTk4MDkzMTIxMzU0IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoibGFzZGthc3Frd3dxa2VAZ21haWwuY29tIiwiaWF0IjoxNDQ1NzE1OTg4LCJleHAiOjE0NDU3MTk1ODh9.C_YFuL3bLuabaDvPLpBpFbmNduzQAx2STH9IFlk8RSjbi5MfDdknQpfpb1ePA-klfpnAyoyB1jOh6iqh2CNomcmd2ztMjRgXVloDoBG62ZL3umRAPtiBCEuRTs2L_e1jVQpoOcNFA8PUqddzQMH82UAcJoIyeTgjVCMHbOgERYfntnrZT7vu6OIuvwKiJMLkPSiKmScJZpqFmKfUuUHsQxZd5-VVWCkJROgKubsOg-eQKzv6YneMaATU9LFXFuvNLKdHDLvLhnEqMTgXRZJGeDhNnIT5a-8iS9OEIeQexbx4ILWmHKmZW4IL5UrH--9qEeuSGbQ-r15RDVvEa2txDA
X-Snapchat-Client-Auth: v1:79ae1c567c5fc557ffe2a0ca:3e8b029a69a8199a29c11785025e89005910e27e071d486f8c8fcbb474da2da69f96cb8a3197e76ca4176cd0f501705d11efb45a747a0d93a8955472e24cd0473fb79fdf030b28c540e3b483f6b4be18befd7b9ce37a46f0786d96fe53488bf01a174465a2f1ad695a9db72ca72a75dab55c272f983d5fe24841dc0b4922d589fa05
Accept-Encoding: gzip
Content-Length: 5041
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue

DATA: username=jonatan.ive&password=123456cat&height=1280&width=720&max_video_height=640&max_video_width=480&dsig=b281e1bfecf87e341472&dtoken1i=00001%3AC9729%2FCPTHOkGeqYd7A9pTBkgwL6UpqxIJhCn4MpxKWlN7go7g2o7HH2n8kULRwA&ptoken=ie&timestamp=1445715988571&attestation=eyJhbGciOiJSUzI1NiIsIng1YyI6WyJNSUlFZmpDQ0EyYWdBd0lCQWdJSVZaeDlNZDVhb3JVd0RRWUpLb1pJaHZjTkFRRUxCUUF3U1RFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBb1RDa2R2YjJkc1pTQkpibU14SlRBakJnTlZCQU1USEVkdmIyZHNaU0JKYm5SbGNtNWxkQ0JCZFhSb2IzSnBkSGtnUnpJd0hoY05NVFV3T0RNeE1qQXpOalE0V2hjTk1UWXdPRE13TURBd01EQXdXakJzTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNBd0tRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCd3dOVFc5MWJuUmhhVzRnVm1sbGR6RVRNQkVHQTFVRUNnd0tSMjl2WjJ4bElFbHVZekViTUJrR0ExVUVBd3dTWVhSMFpYTjBMbUZ1WkhKdmFXUXVZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzaWpVemNKOHl3NmhlYnpiQTRYbDJsOTM0dG96SFYyNWdJZ2VMNnU0eWVNNE4yMTh4WitPMWhkelBLbmR6bjArc1VuUHNTekl6SWZiMzV3Nk9xRDlxLysydlk5OUN3T2c0RXF2QXU2OTV1ZjVibzFjNk4rcHpNOWRWMDZIR3dSdUUxUE1OY2Y4Y01CUEJDZy9jWmo2bUlsbFdGVXFERlFmVE5tL25vU0lucmg2WUpUOWhvdUJ6U2d5ZE1Kb2NsYnZEdjlEcThFQ1lWUVhFanA4Z00yVWNnOTNTZXhjb2xmZCtLVUFrNXdkaVBTeXhINFVRaDFvV25iMFR1bzJzeUpQZHh1cWQ3MVRFd1NweE5wcDZxZEFicy9XNE8vZ2swMVVxWEVqbFZvaFhmSE1sbHZsZEd5dWhEM0Z0dFIzOEFEb0dRaWVUVnlzK2VaZWY3ZXYzem9uNFFJREFRQUJvNElCUlRDQ0FVRXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUIwR0ExVWRFUVFXTUJTQ0VtRjBkR1Z6ZEM1aGJtUnliMmxrTG1OdmJUQm9CZ2dyQmdFRkJRY0JBUVJjTUZvd0t3WUlLd1lCQlFVSE1BS0dIMmgwZEhBNkx5OXdhMmt1WjI5dloyeGxMbU52YlM5SFNVRkhNaTVqY25Rd0t3WUlLd1lCQlFVSE1BR0dIMmgwZEhBNkx5OWpiR2xsYm5Sek1TNW5iMjluYkdVdVkyOXRMMjlqYzNBd0hRWURWUjBPQkJZRUZIVGh6cHVGbTNYcGs5c2xScDlRLzNSTGVNK2NNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVTdDBHRmh1ODltaTFkdldCdHJ0aUdycGFnUzh3RndZRFZSMGdCQkF3RGpBTUJnb3JCZ0VFQWRaNUFnVUJNREFHQTFVZEh3UXBNQ2N3SmFBam9DR0dIMmgwZEhBNkx5OXdhMmt1WjI5dloyeGxMbU52YlM5SFNVRkhNaTVqY213d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFENkxLN25UZlhaUzZEMTg1ZlQvencxVGp0SUxOditrYlE3bVJZT2Z6dzY5bW1xWGNaeFppZllsNXRsdWVNZ0xzWFNFOWJQRXNKZk9hZzJLSnFiTVhXUUpGR1F5cmJ1OGszeDZXNDEvNWkzdUl6ZWsvTm5hZ00yV2hmK2lYcWcrdkxmakgyVlJoRmtQQ2k4Z21DTDZneEZidm5ldUd5UlpyMEErS3NOUUxMMW1SQ3RjLzZRYWF0ZWV5Uy9TMmVGcVJaT2NJN2hpak95QTdvRUo4ZDNJMnlOZXdJSmlWd2dMZDNmYWRyekpwVmFyN1ZRR2ljRnJUK0doVnpHSld4U1E0VEQzdUhZY0hHZTAwR2VYUVoxMms3SEtEWDRpRUNrek9jMEtXbG1WVXNXMXRrMTJnTitXQXlkM0QrVkdhV1lwQjNYeWd4VytTd3JrSkZoalpOaURBRkE9IiwiTUlJRDhEQ0NBdGlnQXdJQkFnSURBanFETUEwR0NTcUdTSWIzRFFFQkN3VUFNRUl4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MUhaVzlVY25WemRDQkpibU11TVJzd0dRWURWUVFERXhKSFpXOVVjblZ6ZENCSGJHOWlZV3dnUTBFd0hoY05NVE13TkRBMU1UVXhOVFUyV2hjTk1UWXhNak14TWpNMU9UVTVXakJKTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNoTUtSMjl2WjJ4bElFbHVZekVsTUNNR0ExVUVBeE1jUjI5dloyeGxJRWx1ZEdWeWJtVjBJRUYxZEdodmNtbDBlU0JITWpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSndxQkhkYzJGQ1JPZ2FqZ3VEWVVFaThpVC94R1hBYWlFWis0SS9GOFluT0llNWEvbUVOdHpKRWlhQjBDMU5QVmFUT2dtS1Y3dXRaWDhiaEJZQVN4RjZVUDd4YlNEajBVL2NrNXZ1UjZSWEV6L1JURGZSSy9KOVUzbjIrb0d0dmg4RFFVQjhvTUFOQTJnaHpVV3gvL3pvOHB6Y0dqcjFMRVFUcmZTVGU1dm44TVhIN2xOVmc4eTVLcjBMU3krckVhaHF5ekZQZEZVdUxIOGdaWVIvTm5hZytZeXVFTldsbGhNZ1p4VVlpK0ZPVnZ1T0FTaERHS3V5Nmx5QVJ4em1aRUFTZzhHRjZsU1dNVGxKMTRyYnRDTW9VL000aWFyTk96MFlEbDVjRGZzQ3gzbnV2UlRQUHVqNXh0OTcwSlNYQ0RUV0puWjM3RGhGNWlSNDN4YStPY21rQ0F3RUFBYU9CNXpDQjVEQWZCZ05WSFNNRUdEQVdnQlRBZXBob2pZbjdxd1ZrREJGOXFuMWx1TXJNVGpBZEJnTlZIUTRFRmdRVVN0MEdGaHU4OW1pMWR2V0J0cnRpR3JwYWdTOHdEZ1lEVlIwUEFRSC9CQVFEQWdFR01DNEdDQ3NHQVFVRkJ3RUJCQ0l3SURBZUJnZ3JCZ0VGQlFjd0FZWVNhSFIwY0RvdkwyY3VjM2x0WTJRdVkyOXRNQklHQTFVZEV3RUIvd1FJTUFZQkFmOENBUUF3TlFZRFZSMGZCQzR3TERBcW9DaWdKb1lrYUhSMGNEb3ZMMmN1YzNsdFkySXVZMjl0TDJOeWJITXZaM1JuYkc5aVlXd3VZM0pzTUJjR0ExVWRJQVFRTUE0d0RBWUtLd1lCQkFIV2VRSUZBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcXZxcElNMXFaNFB0WHRSKzNoM0VmK0FsQmdERkpQdXB5QzF0ZnQ2ZGdtVXNnV00wWmo3cFVzSUl0TXN2OTErWk9tcWNVSHFGQll4OTBTcEloTk1KYkh6Q3pUV2Y4NEx1VXQ1b1grUUFpaGNnbHZjcGpacE55NmplaHNnTmIxYUhBMzBEUDl6NmVYMGhHZm5JT2k5UmRvekhRWkp4anlYT04vaEtUQUFqNzhRMUVLN2dJNEJ6ZkUwMExzaHVrTllRSHBtRWN4cHc4dTFWRHU0WEJ1cG43akxyTE4xbkJ6LzJpOEp3M2xzQTVyc2IwellhSW14c3NEVkNiSkFKUFpQcFpBa2lEb1VHbjhKeklkUG1YNERrallVaU9uTURzV0NPcm1qaTlENlg1MkFTQ1dnMjNqclc0a09WV3plQmtvRWZ1NDNYclZKa0ZsZVcyVjQwZnNnMTJBPT0iXX0.eyJub25jZSI6Ilcrc3BYbzFqN0VNVTdGNnE0R3pQS1gxTG9RUEVZY1llWFo2SWppNzVTMmM9IiwidGltZXN0YW1wTXMiOjE0NDU3MTU5OTExOTYsImFwa1BhY2thZ2VOYW1lIjoiY29tLnNuYXBjaGF0LmFuZHJvaWQiLCJhcGtEaWdlc3RTaGEyNTYiOiJ3eUkxZ1dMS1MxMkZyQjBZMGJ4TzVtMktVQXl0ZER4UnprUmRwbUpTMXpNPSIsImN0c1Byb2ZpbGVNYXRjaCI6ZmFsc2UsImV4dGVuc2lvbiI6IkNSY0FKYm1YWVdlSiIsImFwa0NlcnRpZmljYXRlRGlnZXN0U2hhMjU2IjpbIkx4eXEvS0h0TU5DMDQ0aGo3dnErb09nVmNSK2t6M200SWxHYWdsblpXbGc9Il19.ZkQ6F9098ZHNyr_yKZEL9Y-4nOCqugUT8KiM5cDRXKLjIOORoDRU3O4f-7xkO8uS1W-YXPaMeBcYI0IQjPvxtPzzcjnO82txAwRQtOheVTptUATLDkEY-eBVUAZKMkqYpnrZPPug3hO89kqwmRUfEWXtZaabiYwg9zJaS-eDdO2ftnd9fIi9xg_nj0cAk-x1ausIPom5zJn4GfpEJfH099QkpbQz2unDT_r_b94B5E0DQuJSfyhVLlevl3kiOAePFHc5sPg5slNepdBqnZz4Sn0MVu8h43CGNgVlF6Be0H3A4NZQKbD81NIlNif5GCq6wzsS-4vVZJbKkRGxqAeUHg&sflag=1&application_id=com.snapchat.android&req_token=930ebb5f6c51de086e0ed2e7f2a0d4143aef4d86198bba8b19b4e014dfc51b4b
stdClass Object
(
    [message] => Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)
    [status] => -103
    [logged] => 
)
RESULT: 1

**Comment by mgp25** [comment]
@kripsbro Casper API it's working good. Make sure your data is correct. And try again.

Regards
