### ISSUE TITLE
Request not procedd

### ISSUE THREAD

**Issue by pank123** [mgp25/Snap-API#243]
I am facing follwoing debug error  Please help me

REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id Sent Request info: POST /loq/device_id HTTP/1.1 User-Agent: Snapchat/9.16.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip) Host: feelinsonice-hrd.appspot.com Accept: _/_ Accept-Language: en Accept-Locale: en_US X-Snapchat-Client-Auth-Token: Bearer Content-Length: 98 Content-Type: application/x-www-form-urlencoded DATA: timestamp=1445628909201&req_token=9309675e24f17d086e8f92e9f7a70b64bced4d84197a6a84d9b46514d0c51b0b RESULT: {"dtoken1i":"00001:Jivl3URwTb6Om7e7Vkpf4ChIcUn821oNd5mQgez5jMnT/BxJgcgOJ7d9WPEVRZjq","dtoken1v":"aSCzGDHJTakcp9FJdrxi56pKBv6xVI3cnlIP3KNmd8w\u003d"}

**Comment by mgp25** [comment]
@pank123 what you have posted is not an error
