### ISSUE TITLE
Video size

### ISSUE THREAD

**Issue by pank123** [mgp25/Snap-API#244]
How many size is allowed for video media.
I am not able to upload more than 1 mb video.
When i am trying to upload more than 1 mb video that video not shown me on snapchat
is there any limitation in api for video to allow maximum 1 mb. ?

Please confirm.

**Comment by mgp25** [comment]
Duplicate #240

**Comment by pank123** [comment]
I know about 10 second video length.
I am asking about size there is limitation for size i cant able to upload more than 1 mb video on snapchat api.

Thanks

**Comment by liamcottle** [comment]
@pank123 Please refrain from posting duplicate questions and creating duplicate issues.
