### ISSUE TITLE
getSnaps(true) does not work

### ISSUE THREAD

**Issue by brangnu** [mgp25/Snap-API#245]
It does not fetch new snaps. If it sometimes does, it fetches only the first snap.

**Comment by mgp25** [comment]
@nshung will fix it tomorrow

Regards

**Comment by mgp25** [comment]
@nshung its working at least for me.

If you have any issue, you can check the debug log when we do `/loq/all_updates` and search for `pending_snaps`.

Regards

**Comment by brangnu** [comment]
Yes. The snap is in the log, but it is not downloaded. This is not folder permission issue since it successfully downloads sometimes and when it does, it is only the first snap.

Let's say I receive three snaps from a person. getSnaps(true) fetches only the first one and not the last two ones.
