### ISSUE TITLE
Issue when downloading story

### ISSUE THREAD

**Issue by dundua** [mgp25/Snap-API#246]
When downloading some stories using "$snapchat->getFriendStories(true);" or with getStory(...), the file is not correctly downloaded, and thus not correctly decrypted. No errors are outputted by any function. This does not happen often with other user's stories, but for some reason, it happens with this specific user.

Here is the story_blob: https://mega.nz/#!9RQCGLgY!7EVAY2w7icKPtho6Q8uKF_0gdCrr9Z380VpZAP56FrE

Here is the file as obtained from php curl: https://mega.nz/#!BJoBCAaL!YqLTbCygVrwOA_5N_aQp8YqoEeuyKislN4ppMZz_8mg
Notice the 404 error shown in the curl file, but not returning an error when running 'get($endpoint)'. Downloading the blob from the browser works. At first I thought it was because curl was downloading from https://feelinsonice-hrd.appspot.com instead of https://app.snapchat.com, but that made no difference.

And here is the final file: https://mega.nz/#!cBIBGQDQ!179eJtospb7ANjSj2Ced6QUJ1Fs8Qll8GxwCIBLmD6k

Details on the specific story:

```
[197] => stdClass Object
    (
        [id] => cpslo_chat~1446102001077
        [username] => cpslo_chat
        [mature_content] => 
        [client_id] => CPSLO_CHAT~08354A9F-FE4E-4B5A-B0CB-6C8D3EFC7D0D
        [timestamp] => 1446102001077
        [media_id] => 6652167175372800
        [media_key] => SeUNPnmyWfqMXj+KhMaLLdQtfq1cGv/RqyGt7El0DLQ=
        [media_iv] => Xv9T0R6BiWUOzLha4aXbdA==
        [thumbnail_iv] => vOWNvFGoSFZGdXyteESRuw==
        [media_type] => 1
        [time] => 9.8750113378685
        [caption_text_display] => Send in your halloween snaps Ã°ÂŸÂŽÂƒ
        [zipped] => 1
        [story_filter_id] => 
        [time_left] => 72539622
        [is_shared] => 
        [media_url] => https://app.snapchat.com/bq/story_blob?story_id=6652167175372800&t=3&mt=1
        [thumbnail_url] => https://app.snapchat.com/bq/story_thumbnail?story_id=6652167175372800&t=3&mt=1
        [needs_auth] => 1
        [ad_can_follow] => 1
    )
```

**Comment by dundua** [comment]
Duplicate of #233

**Comment by liamcottle** [comment]
If you're getting a 404, the story no longer exists.

**Comment by dundua** [comment]
But it is still viewable on the Android app with over 12 hrs left
