### ISSUE TITLE
Can't add friends and folder permissions

### ISSUE THREAD

**Issue by HW73** [mgp25/Snap-API#247]
Hi, I've been using the bot for the last 6 weeks and I haven't been able to add users back. I've used the example bot to add them but that hasn't worked. I've also found out I have an error since turning off the debug which is "Should have write access to own folder" and also this error "You have to add 'username' as a friend first". Do you have any idea how I could get this working again, any help would be great. 

Thank you

**Comment by shane2710** [comment]
Hey there, I had the same problem with write permissions.  I tried chmod -R 666 to change the permissions on the src/ directory recursively, but that didn't work.  Neither did running my script as root.

However, it seems like adding your .php file to a new directory in the SC-API folder (i.e. /SC-API/tools/ in my case) solves the issue.  You can keep calling scripts in any directory, but the .php file running $snapchat commands likes to reside with the rest of the build.

**Comment by mgfigueroa** [comment]
The bot never worked for me, I modified getUnconfirmedFriends() for it to work, glancing at it again now it still looks incorrect.

**Comment by emiliobasualdo** [comment]
My solution:
`array_diff(getFriends, getAddedFriends):`

**Comment by mgp25** [comment]
If you have a fix for something, send a pull request

Regards
