### ISSUE TITLE
How to mark snaps viewed after successful getSnaps(true)?

### ISSUE THREAD

**Issue by shane2710** [mgp25/Snap-API#248]
I'm working on a bot to take its recently received snapchats and regurgitate them as it's own story, with a few other features as well.  Now, when I run getSnaps(true) and then use glob() to find the files, I can successfully capture incoming snaps, find paths to the files, and story them.  I then clear the src/snaps/ directory for the next use.

However, everytime this script is run, EVERY previous snap is put back on the story because getSnaps(true) doesn't mark the snapchat as viewed...  I can cp the whole src/snaps directory somewhere, clear it out, then use diff() in linux to figure out which snaps are new and need to be posted, but it would be much cleaner/save computing power and space on my RasPi to be able to simply mark a snapchat as viewed and thus not have to deal with downloading every snap on login and making comparisons to previously stored files....  

So, is there a way to mark the snap as viewed upon opening?  Or is this in the pipes for future implementation?  I'd be happy to help work on it.

Thanks for all your work @mgp25!

**Comment by emiliobasualdo** [comment]
Use ->clearFeed to delete the entire conversatiom list, o use markasviewd

**Comment by shane2710** [comment]
Thank you very much!

Is there more documentation for this project?  It doesn't list either of those attributes in the Wiki
