### ISSUE TITLE
Login Failed !!!

### ISSUE THREAD

**Issue by heliumsoft** [mgp25/Snap-API#251]
I can get Attestation token 

but It have return in Snapcaht Login 

```
 "message": "Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)",
      "status": -103,
      "logged": false
```

Let me know solution. 

thanks for your help!!

**Comment by glennchirino** [comment]
thanks for your help!!

**Comment by mgp25** [comment]
@glennchirino make sure your setting correctly your gmail data and Casper API tokens, retry logging in, and it should work

Rgerads

**Comment by heliumsoft** [comment]
thanks for your help...
