### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by phplab83** [mgp25/Snap-API#256]
Analytics for open, screen shots on texts and snaps.  Can we get some of these stats using the api?

**Comment by emiliobasualdo** [comment]
You can. By calling GetUpdates and iterating through the arrays

**Comment by pank123** [comment]
but in getupdates there is no data return 
can you please guide me any how the exact array return?

**Comment by emiliobasualdo** [comment]
log the GetUpdates or GetConversation functions to see them first, and search for the info there.

> On 6/11/2015, at 10:48, mgp25 notifications@github.com wrote:
> 
> Closed #256 https://github.com/mgp25/SC-API/issues/256.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/mgp25/SC-API/issues/256#event-456927940.

Pilo Basualdo

**Comment by phplab83** [comment]
when i am call this its not return anything.. Please help me on this.

``` php
$updates = $this->getUpdates();                
                echo "<pre>";
                print_r($updates);
                exit;
```

**Comment by emiliobasualdo** [comment]
you are then doing something wrong

> On 6/11/2015, at 10:55, phplab83 notifications@github.com wrote:
> 
> when i am call this its not return anything.. Please help me on this.
> $updates = $this->getUpdates();
> 
> echo "
> 
> ";
> 
> ```
>             print_r($updates);
> 
>             exit;
> ```
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/mgp25/SC-API/issues/256#issuecomment-154415405.

Pilo Basualdo

**Comment by mgp25** [comment]
@phplab83 first of all: learn php, once you know, come back here and ask API questions not PHP.

``` php
//considering $snapchat has the instance

$updates = $snapchat->getUpdates();                
print_r($updates); // you can also use var_dump
```
