### ISSUE TITLE
GetSnaps returns nothing

### ISSUE THREAD

**Issue by umbreon222** [mgp25/Snap-API#257]
## GetSnaps is called then debug log shows the following

REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/all_updates

Sent Request info: POST /loq/all_updates HTTP/1.1
Host: feelinsonice-hrd.appspot.com
User-Agent: Snapchat/9.16.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip)
Accept: _/_
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjI5MGRjZmQ2NThiZjEyZDFhYjRiNzliMThlMTU2MDcxYTcyNjYxODgifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTAyMDUyOTExNTI4MDk0MjYxNDMyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoidW1icmVvbjIyMkBnbWFpbC5jb20iLCJpYXQiOjE0NDY5MTc0MzIsImV4cCI6MTQ0NjkyMTAzMiwibmFtZSI6IkRldmluIFdlbmR0IiwicGljdHVyZSI6Imh0dHBzOi8vbGg1Lmdvb2dsZXVzZXJjb250ZW50LmNvbS8tZ0JzeUFyNWxOaGMvQUFBQUFBQUFBQUkvQUFBQUFBQUFBSEEvemx1ZkZ6b25zb1Evczk2LWMvcGhvdG8uanBnIiwiZ2l2ZW5fbmFtZSI6IkRldmluIiwiZmFtaWx5X25hbWUiOiJXZW5kdCJ9.TBC-i5CM36IQLF1PcnKDt3H3aRfw6NMaOLyr3be1na3u0JvyBHnROf5LqP9_7SEnz1_1gJmOfw93UpnQJFwjp_qSvHHxXMN9qqX2OxoaI85BR-al7xcsb6979keL1sS5PwJ3Eefdwsu4rp0qVR-2YiUa_uY0zawUTlQxaPFxCgktgo4Cbqs7ql1zH2kX405kGbWRAAtZmKTIvkIzOqd-EfrUi2Hetnxcmq2aBdg6pQ52ycJFfmPNG7iC0ztYd0B4dZ_YiM180-qTtqHd7qPqlgW_2jKV4z-JUmbZ6veEmS45a6sNlEzZZ8lt12a4hGJRw_1hAi_sG_syYbyFi9RTpQ
Content-Length: 178
Content-Type: application/x-www-form-urlencoded

DATA: timestamp=1446917713209&username=TPVegas&height=1280&width=720&max_video_height=640&max_video_width=480&req_token=93f4cae897c3f195c7cfc891df9368bc67269c09d1512e06c71aa8a6f3a5c06e
RESULT:

**Comment by umbreon222** [comment]
Tried on 3 different PC's all with different network providers and obviously IPs. Account isn't blocked either since I can access it from my phone using Casper or Snapchat.

**Comment by mgp25** [comment]
@umbreon222 its working perfectly

Regards
