### ISSUE TITLE
Error: UNAUTHORIZED

### ISSUE THREAD

**Issue by zqrt** [mgp25/Snap-API#259]
REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id Sent Request info: POST /loq/device_id HTTP/1.1 User-Agent: Snapchat/9.16.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip) Host: feelinsonice-hrd.appspot.com Accept: _/_ Accept-Language: en Accept-Locale: en_US X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImYwMTY2N2MyMjY0Y2E1MDk5OTc3YmFhM2FhZjU3YWZmYmJkZjRlNDcifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTE0NDk4MzgyNjE5MTk4NDI3NzQ3IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoiaGFtYWRhbHdhaGJpQGdtYWlsLmNvbSIsImlhdCI6MTQ0NzMzNDQwNiwiZXhwIjoxNDQ3MzM4MDA2LCJuYW1lIjoiaGFtYWQgYWx3YWhiaSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vLWxPZTBZb2k3WGFNL0FBQUFBQUFBQUFJL0FBQUFBQUFBQk5ZL2pOUXpwa1B5aTU4L3M5Ni1jL3Bob3RvLmpwZyIsImdpdmVuX25hbWUiOiJoYW1hZCIsImZhbWlseV9uYW1lIjoiYWx3YWhiaSJ9.bPJPHmkND9knkZyFppucGjcHsfCPFWQ2Sh9rPyCd3S3yfmY9eS1BbxqCGFCuJ81va4g_GE0FrtY1BtK_huNcAym1fr90L2mP20ZQ4wNfkL0WLxJBsjoMvCkirWUJgtnzatrcvXJ_JsPRtugs8CBYmWoELTanjr1SZgd1TOjQds80acvcAzZpL7sOoFAfCeZhDXBLywGVBAKssnYH_p78afu7bBG5KJbz007KuhTyGvEJpvEw029aF7436oMZUtfV6d_W0-XZFln-dLp73zq-ih2EYYLu2YOjuyXm89G7EZPxUN1mstDOCtRWCZvFYSEIDzWZIULm-04_Wysa-ZElLg Content-Length: 102 Content-Type: application/x-www-form-urlencoded DATA: timestamp=1.44733441885E+12&req_token=930d495c32e15bb86e6e32e4f5a774f4e8e34d8a19312a8419b46b14d6c51b6b RESULT:
Error: UNAUTHORIZED

REQUEST TO: https://android.clients.google.com/auth Array ( [device_country] => us [operatorCountry] => us [lang] => en_US [sdk_version] => 19 [google_play_services_version] => 7097038 [accountType] => HOSTED_OR_GOOGLE [Email] => hamadalwahbi@gmail.com [service] => audience:server:client_id:694893979329-l59f3phl42et9clpoo296d8raqoljl6p.apps.googleusercontent.com [source] => android [androidId] => 378c184c6070c26c [app] => com.snapchat.android [client_sig] => 49f6badb81d89a9e38d65de76f09355071bd67e7 [callerPkg] => com.snapchat.android [callerSig] => 49f6badb81d89a9e38d65de76f09355071bd67e7 [EncryptedPasswd] => AFcb4KQ8XPGMw2zsvySdaFIkrRxmK0jyKCSXvlR-uD4c3bXnBdXjJd4-EzFVBEzGa_E5ziNljNphypYFk1nGQjFa9o5MhB5nxqlfB6jcwDkuCtI4_izvV3dc29tRY7GRuUbXGpcDvstrLFuyw8HDtrAS0p4Xc7ws8hdqw9QbfQA5h2Q2NQ== ) DATA: 1 RESULT: Auth=eyJhbGciOiJSUzI1NiIsImtpZCI6ImYwMTY2N2MyMjY0Y2E1MDk5OTc3YmFhM2FhZjU3YWZmYmJkZjRlNDcifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTE0NDk4MzgyNjE5MTk4NDI3NzQ3IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoiaGFtYWRhbHdhaGJpQGdtYWlsLmNvbSIsImlhdCI6MTQ0NzMzNDQyMSwiZXhwIjoxNDQ3MzM4MDIxLCJuYW1lIjoiaGFtYWQgYWx3YWhiaSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vLWxPZTBZb2k3WGFNL0FBQUFBQUFBQUFJL0FBQUFBQUFBQk5ZL2pOUXpwa1B5aTU4L3M5Ni1jL3Bob3RvLmpwZyIsImdpdmVuX25hbWUiOiJoYW1hZCIsImZhbWlseV9uYW1lIjoiYWx3YWhiaSJ9.Xjn4QsyiQ1aWF3znfKvWGpHMM2g_E-lhjBtf9LnS9ustl1xBdxm9vFgSWaIC_HJ89YyO04Qy7y2XAfMPbgkE1Sm9JeVgYBp8KJIYniP5m_WxbW5eRqaDndRQJAWvbsR81jlfXTKqXIAV1LA0T4RZr_yGSfHaulec7hTPfwb5L-aSD6tzIV6owf3sJ-4hrzXEJ-J0FIMgBIgiEKpFQSgmd3C4a2ddLB4LDUUz9BR0__EDqd90qEAfi7ktKxZd2NRahzyym7wLlQX-MUvNwru3YyIYXd87C6Ru-lR80090zf-YdLaDz30x16fDqveT3yz2MCT_VB2NWPChQVDGhSZiQg issueAdvice=auto Expiry=1447338021 storeConsentRemotely=1

**Comment by mgp25** [comment]
#258
