### ISSUE TITLE
Snapchat account alert.

### ISSUE THREAD

**Issue by dstjerne** [mgp25/Snap-API#26]
Mail from Snapchat.

https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xta1/v/t34.0-12/11063062_10153171552427431_1372648165_n.jpg?oh=367ca9d7a931d6034e4d87bdb894abb9&oe=550B1ABA&__gda__=1426731674_f93b1a9451be079d88e8339dd8783bb9

**Comment by sallaben** [comment]
An empty threat. They've been sending my personal account these for months.

**Comment by dstjerne** [comment]
I hope so ;-)
