### ISSUE TITLE
casper api issue

### ISSUE THREAD

**Issue by phplab83** [mgp25/Snap-API#260]
I am facing issue with casper api with valid api and secret key

Fatal error: Uncaught exception 'CasperException' with message 'API Response: [503] The Attestation Service is unavailable until further notice.' in D:\Xampp\htdocs\snapchat\system\libraries\src\Casper-API-PHP\CasperAgent.php:180 Stack trace: #0 D:\Xampp\htdocs\snapchat\system\libraries\src\Casper-API-PHP\CasperAgent.php(95): CasperAgent->request('/snapchat/attes...', NULL, Array, true) #1 D:\Xampp\htdocs\snapchat\system\libraries\src\Casper-API-PHP\CasperAPI.php(92): CasperAgent->post('/snapchat/attes...', NULL, Array) #2

Can you please guide me whats a wrong with that

**Comment by LanchaBasualdo** [comment]
Liam is working on it. Follow his page on FB for Updates: Casper App

**Comment by mgp25** [comment]
#258
