### ISSUE TITLE
casper api issue When Fix ?

### ISSUE THREAD

**Issue by phplab83** [mgp25/Snap-API#261]
Hello Support,

Can you please let us know when this casper api issue will resolved ?

Fatal error: Uncaught exception 'CasperException' with message 'API Response: [503] The Attestation Service is unavailable until further notice.' in D:\Xampp\htdocs\snapchat\system\libraries\src\Casper-API-PHP\CasperAgent.php:180 Stack trace: #0 D:\Xampp\htdocs\snapchat\system\libraries\src\Casper-API-PHP\CasperAgent.php(95): CasperAgent->request('/snapchat/attes...', NULL, Array, true) #1

**Comment by LanchaBasualdo** [comment]
Facebook: Casper App

**Comment by mgp25** [comment]
#258
