### ISSUE TITLE
Getting BadAuthentication error when attempting to login

### ISSUE THREAD

**Issue by robocos987** [mgp25/Snap-API#266]
Whenever I attempt to login,I get this error: 

```
"hVmRg==
)
DATA: 1
RESULT: Error=BadAuthentication"
```

Is there a solution for this?
Thank you

**Comment by liamcottle** [comment]
Either your Google Account password is incorrect, or you haven't enabled `Less Secure Apps` in Google Settings.

**Comment by robocos987** [comment]
Sorry about writing in the other issue. The problem still persists when I entered the correct credentials and enabled "less secure settings"

**Comment by mgp25** [comment]
@robocos987 post full debug log, use latest commit ( just pushed about 1 min ago)

**Comment by robocos987** [comment]
Alright.
Full log:
http://pastebin.com/9bUm5ULT

**Comment by mgp25** [comment]
@robocos987 it seems you havent set your gmail data correctly like Liam said or something related, is not API issue as its a request we do to google

**Comment by robocos987** [comment]
I have set the correct credentials and even with that I am still getting the error(I also have Less Secure apps enabled on my google account)..

**Comment by mgp25** [comment]
@robocos987 send me your data / script to my mail, and let me test if it works at my side.

**Comment by robocos987** [comment]
Script: http://pastebin.com/L6JK4FiS

**Comment by robocos987** [comment]
Alright I sent it
