### ISSUE TITLE
Invalid X-Casper-Signature

### ISSUE THREAD

**Issue by sraboni** [mgp25/Snap-API#267]
Hello
When I am trying to login this API, I am getting "API Response: [401] Invalid X-Casper-Signature" error though Casper API key and secret are correct. I have double checked it. I can see there is an issue listed "Casper API is upgrading", can you please inform me if I am getting this error because of the same or anything else.

Thanks

**Comment by hako** [comment]
@sraboni It's working for me, It could be your secret key. Regenerate your API keys and try again.

**Comment by sraboni** [comment]
Hello @hako 
 I have already regenerated API key & secret. But still getting the same issue. I am posting here my debug log. Can you please  check if everything is fine with the code. I am trying directly on the downloaded file. Just entered my credentials.
Please have a look.

Debug Log:
REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id
Sent Request info: POST /loq/device_id HTTP/1.1
User-Agent: Snapchat/9.16.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: _/_
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImFlMTRhYzI1ZjQwMzVhY2Q5ZDIxZWY3MjAxZGM4ODNjMDkwZWI4NDMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTA1OTE4MjQ0OTI0NDAwODc1MTcyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImhkIjoibXlwaHBkZXZlbG9wZXJzLmNvbSIsImVtYWlsIjoic3JhYm9uaWNoYWtyYWJvcnR5LnNickBteXBocGRldmVsb3BlcnMuY29tIiwiaWF0IjoxNDQ4ODkxMDc4LCJleHAiOjE0NDg4OTQ2NzgsIm5hbWUiOiJTcmFib25pIENoYWtyYWJvcnR5IiwiZ2l2ZW5fbmFtZSI6IlNyYWJvbmkiLCJmYW1pbHlfbmFtZSI6IkNoYWtyYWJvcnR5In0.hW8aGBXIQP6m7qJgvuLb4CUnTgujm19Ivpzgbla5tjVaQpqlBMf0EK2BBwSSKDJ1gVCk4ihwejfMA3w8jpTEXAtA7BRfTF3lIE1cabVkotEETFVA9FsgcARhDkYVKPmGuvW3-92IgZtq--xdO276KnmIfNObD-xo_eCSiuuRecWskgp-lp9FUCqLXu5gZZGjNrJ5fEGsSypoW0jZ8eTMrhzCo1si8EalDRgrLUp3M0Q3OSCYSSKeuvqm3BKCvtNTyezqyvrpIwjBIM7dDhmyGul-8nnf3c5AvJBk4xEU4bsrHTAeM1WxcTeE7WgqeqdYIu0IFxFc7acft2IVjJbmZw
Content-Length: 102
Content-Type: application/x-www-form-urlencoded
DATA: timestamp=1.44889107925E+12&req_token=9307f5506de1d9f86e3cf8eefaa4e2e4d5e74d8419c3ea8599b45914d6c510ab
RESULT: 
Error: UNAUTHORIZED

REQUEST TO: https://android.clients.google.com/auth
Array
(
    [device_country] => us
    [operatorCountry] => us
    [lang] => en_US
    [sdk_version] => 19
    [google_play_services_version] => 7097038
    [accountType] => HOSTED_OR_GOOGLE
    [Email] => <MY EMAIL>
    [service] => audience:server:client_id:694893979329-l59f3phl42et9clpoo296d8raqoljl6p.apps.googleusercontent.com
    [source] => android
    [androidId] => 378c184c6070c26c
    [app] => com.snapchat.android
    [client_sig] => 49f6badb81d89a9e38d65de76f09355071bd67e7
    [callerPkg] => com.snapchat.android
    [callerSig] => 49f6badb81d89a9e38d65de76f09355071bd67e7
    [EncryptedPasswd] => <ENCRYPTED PWD>
)
DATA: 1
RESULT: Auth=eyJhbGciOiJSUzI1NiIsImtpZCI6ImFlMTRhYzI1ZjQwMzVhY2Q5ZDIxZWY3MjAxZGM4ODNjMDkwZWI4NDMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTA1OTE4MjQ0OTI0NDAwODc1MTcyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImhkIjoibXlwaHBkZXZlbG9wZXJzLmNvbSIsImVtYWlsIjoic3JhYm9uaWNoYWtyYWJvcnR5LnNickBteXBocGRldmVsb3BlcnMuY29tIiwiaWF0IjoxNDQ4ODkxMDc5LCJleHAiOjE0NDg4OTQ2NzksIm5hbWUiOiJTcmFib25pIENoYWtyYWJvcnR5IiwiZ2l2ZW5fbmFtZSI6IlNyYWJvbmkiLCJmYW1pbHlfbmFtZSI6IkNoYWtyYWJvcnR5In0.k57Mo6BTfO6tTnBF8Lo3KykprIiupZOu0qGMsx42r0g1NLy3z6IpzJd97Sg6qF1iaxGvq_KYjl8SFtESVbiFl7XDI7j-a-4AhowYjgVecMODz9w1ZrdMmFnL_QQW4SKbCgJuAFbjvFsGkq2MLuLTrgUi7pzwKTCpWmccJ3zVZMqikXq1N2LkmV5fEc8jX3zMzGRxcocO3xVXUeECDaTq25bLhapyY-jAtKK7FhX4Ti5DVfsG5-zJFj6NQkg4fVcj1huZv7lzLekKne2S7Z51SeGKOe8lqg8U6-TNmMhbjnaCgVFPxVx6YUJxdxNMGxjwiNkiMGM55JRuDgx5XecLWQ
issueAdvice=auto
Expiry=1448894679
storeConsentRemotely=1
Fatal error:  Uncaught exception 'CasperException' with message 'API Response: [401] Invalid X-Casper-Signature'

Thanks

**Comment by mgp25** [comment]
Please read #258
