### ISSUE TITLE
Casper API Client registration

### ISSUE THREAD

**Issue by 0anasm** [mgp25/Snap-API#268]
Thank you for your amazing work. how can I register as a new client? is registration going to be enabled soon? I need to get an account please.

Thank you

**Comment by hako** [comment]
@0anasm Please elaborate, do you mean Snapchat registration? Or the Casper API registration?

**Comment by 0anasm** [comment]
I mean the API client registration on this link: https://clients.casper.io/register.php

**Comment by mgp25** [comment]
As soon as its fixed, it will be enabled.

Regards
