### ISSUE TITLE
Kept Auth File - Logging in results in 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by moinnadeem** [mgp25/Snap-API#270]
Hello!

Thanks for taking the time to help me out, I really appreciate it.

I try to login with accounts I already have the auth file for, but keep on getting this. I've tried it from multiple servers, I don't think it's an IP ban. Removed a few key details for privacy

REQUEST TO: https://android.clients.google.com/auth
Array
(
    [device_country] => us
    [operatorCountry] => us
    [lang] => en_US
    [sdk_version] => 19
    [google_play_services_version] => 7097038
    [accountType] => HOSTED_OR_GOOGLE
    [Email] => [SCRUBBED]
    [service] => audience:server:client_id:694893979329-l59f3phl42et9clpoo296d8raqoljl6p.apps.googleusercontent.com
    [source] => android
    [androidId] => 378c184c6070c26c
    [app] => com.snapchat.android
    [client_sig] => 49f6badb81d89a9e38d65de76f09355071bd67e7
    [callerPkg] => com.snapchat.android
    [callerSig] => 49f6badb81d89a9e38d65de76f09355071bd67e7
    [EncryptedPasswd] => AFcb4KQ46amADd9cLezXO78u_WNtkPdeWAa6zlAEfWyxdK-rw2STyaSRVjYc9cBaxUu34_U25DqVzMZlBWxlpRTghHyDxLdHiEGlDojTKTZKRUaqHkyCf2RZeLefBZ3y1woX8ksYt1Hn8agMoIqGEIg==
)
DATA: 1
RESULT: Auth=eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzZGQzYTZmOGQ0MjlkMWMwNmNlNjAxOTliZmZkZDBiYWI0ZGUzNGUifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTE3NjY4OTU5NTIxNjQxMzgyMTc1IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoibW9pbm4xOTk4QGdtYWlsLmNvbSIsImlhdCI6MTQ0OTAyMzIwMywiZXhwIjoxNDQ5MDI2ODAzLCJuYW1lIjoiTW9pbiBOYWRlZW0iLCJnaXZlbl9uYW1lIjoiTW9pbiIsImZhbWlseV9uYW1lIjoiTmFkZWVtIn0.A-HUGn6ELSILsXdasJEcTsBB9EklFUMI5tfr0J3HVyq0YF_ggcLiFjmOA6vfD9lQ3N4M0QBtiaD_sOb7SXJQA6bPFPfVWD_clxhxnd6V6Cs2EAm5H3Yh-NmYhC02HNj5f2tiRPGfQ3isepNBsh9vSRxxWc_IrpVhJ8Anrk5vv6mgOdpXHIifVXp4L7LShn6qkDbX8u_2pde7pyz9ZkYv38qvbQsDPvL191EwM_8kBET4-n9LK_m7jls9JCbrgOAua5buFxJdW6JtbrgLRiY87U8rI98D5BbZF8BZmYCqKize-_qKtN9ZEJe1XNZrHRn_yJlErmVbIdiR4aPCxB5vFw
issueAdvice=auto
Expiry=1449026803
storeConsentRemotely=1

REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/all_updates

Sent Request info: POST /loq/all_updates HTTP/1.1
User-Agent: Snapchat/9.20.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: _/_
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzZGQzYTZmOGQ0MjlkMWMwNmNlNjAxOTliZmZkZDBiYWI0ZGUzNGUifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwicTIxNjQxMzgyMTc1IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoibW9pbm4xOTk4QGdtYWlsLmNvbSIsImlhdCI6MTQ0OTAyMzIwMywiZXhwIjoxNDQ5MDI2ODAzLCJuYW1lIjoiTW9pbiBOYWRlZW0iLCJnaXZlbl9uYW1lIjoiTW9pbiIsImZhbWlseV9uYW1lIjoiTmFkZWVtIn0.A-HUGn6ELSILsXdasJEcTsBB9EklFUMI5tfr0J3HVyq0YF_ggcLiFjmOA6vfD9lQ3N4M0QBtiaD_sOb7SXJQA6bPFPfVWD_clxhxnd6V6Cs2EAm5H3Yh-NmYhC02HNj5f2tiRPGfQ3isepNBsh9vSRxxWc_IrpVhJ8Anrk5vv6mgOdpXHIifVXp4L7LShn6qkDbX8u_2pde7pyz9ZkYv38qvbQsDPvL191EwM_8kBET4-n9LK_m7jls9JCbrgOAua5buFxJdW6JtbrgLRiY87U8rI98D5BbZF8BZmYCqKize-_qKtN9ZEJe1XNZrHRn_yJlErmVbIdiR4aPCxB5vFw
Content-Length: 181
Content-Type: application/x-www-form-urlencoded

DATA: timestamp=1449023203117&username=[SCRUBBED]&height=1280&width=720&max_video_height=640&max_video_width=480&req_token=2505c26bb238dbc16813319d63282b6baa1c30fa8be1f3f1e18087c137daaa13
RESULT: <html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>401 UNAUTHORIZED</title>
</head>
<body text=#000000 bgcolor=#ffffff>

<h1>Error: UNAUTHORIZED</h1>

</body></html>

Warning: Invalid argument supplied for foreach() in /home/ubuntu/workspace/SC-API/SC-API/src/snapchat.php on line 3097

Call Stack:
    0.0001     234288   1. {main}() /home/ubuntu/workspace/SC-API/SC-API/examples/exampleBots/friendBot.php:0
    0.1269    2545024   2. Snapchat->login() /home/ubuntu/workspace/SC-API/SC-API/examples/exampleBots/friendBot.php:17
    0.1269    2545400   3. Snapchat->openAppEvent() /home/ubuntu/workspace/SC-API/SC-API/src/snapchat.php:409

REQUEST TO: https://sc-analytics.appspot.com/post_events

DATA: {"common_params":{"user_id":"ad00b879b3a2587498f87ab94ce5da07188e5f40291dd84b17c3787ba0146cf1","city":"Unimplemented","sc_user_agent":"Snapchat\/9.20.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip)","session_id":"00000000-0000-0000-0000-000000000000","region":"Unimplemented","latlon":"Unimplemented","friend_count":-1,"country":"Unimplemented"},"events":[{"event_name":"APP_OPEN","event_timestamp":1449023203003,"event_params":{"open_state":"NORMAL","intent_action":"null"}}],"batch_id":"5ce0f054-ddf1-000a-01c1-4c0926df88bd-Snapchat92020HTCOneAndroid502482424221gzip1449023203003"}

REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/all_updates

Sent Request info: POST /loq/all_updates HTTP/1.1
User-Agent: Snapchat/9.20.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: _/_
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzZGQzYTZmOGQ0MjlkMWMwNmNlNjAxOTliZmZkZDBiYWI0ZGUzNGUifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTE3NjY4OTU5NTIxNjQxMzgyMTc1IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5Mzk3OTMyOS1xZzBpMHU4OHQwaG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW5NDQ5MDI2ODAzLCJuYW1lIjoiTW9pbiBOYWRlZW0iLCJnaXZlbl9uYW1lIjoiTW9pbiIsImZhbWlseV9uYW1lIjoiTmFkZWVtIn0.A-HUGn6ELSILsXdasJEcTsBB9EklFUMI5tfr0J3HVyq0YF_ggcLiFjmOA6vfD9lQ3N4M0QBtiaD_sOb7SXJQA6bPFPfVWD_clxhxnd6V6Cs2EAm5H3Yh-NmYhC02HNj5f2tiRPGfQ3isepNBsh9vSRxxWc_IrpVhJ8Anrk5vv6mgOdpXHIifVXp4L7LShn6qkDbX8u_2pde7pyz9ZkYv38qvbQsDPvL191EwM_8kBET4-n9LK_m7jls9JCbrgOAua5buFxJdW6JtbrgLRiY87U8rI98D5BbZF8BZmYCqKize-_qKtN9ZEJe1XNZrHRn_yJlErmVbIdiR4aPCxB5vFw
Content-Length: 131
Content-Type: application/x-www-form-urlencoded

DATA: type=android&timestamp=1449023203912&username=[SCRUBBED]&req_token=2504d161eb98e77168cfcb976e2db98ba11530f98b9153f2c18005c137daae43
RESULT: <html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>401 UNAUTHORIZED</title>
</head>
<body text=#000000 bgcolor=#ffffff>

<h1>Error: UNAUTHORIZED</h1>

</body></html>

REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/all_updates

Sent Request info: POST /loq/all_updates HTTP/1.1
User-Agent: Snapchat/9.20.2.0 (HTC One; Android 5.0.2#482424.2#21; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: _/_
Accept-Language: en
Accept-Locale: en_US
X-Snapchat-Client-Auth-Token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzZGQzYTZmOGQ0MjlkMWMwNmNlNjAxOTliZmZkZDBiYWI0ZGUzNGUifQ.eyJpc3MiOi5nb29nbGUuY29tIiwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTE3NjY4OTU5NTIxNjQxMzgyMTc1IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjY5NDg5M[DELETED A FEW CHARS FOR PRIVACY]waG04azZrMW1icmJuc3VqMTAxaDczdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoibW9pbm4xOTk4QGdtYWlsLmNvbSIsImlhdCI6MTQ0OTAyMzIwMywiZXhwIjoxNDQ5MDI2ODAzLCJuYW1lIjoiTW9pbiBOYWRlZW0iLCJnaXZlbl9uYW1lIjoiTW9pbiIsImZhbWlseV9uYW1lIjoiTmFkZWVtIn0.A-HUGn6ELSILsXdasJEcTsBB9EklFUMI5tfr0J3HVyq0YF_ggcLiFjmOA6vfD9lQ3N4M0QBtiaD_sOb7SXJQA6bPFPfVWD_clxhxnd6V6Cs2EAm5H3Yh-NmYhC02HNj5f2tiRPGfQ3isepNBsh9vSRxxWc_IrpVhJ8Anrk5vv6mgOdpXHIifVXp4L7LShn6qkDbX8u_2pde7pyz9ZkYv38qvbQsDPvL191EwM_8kBET4-n9LK_m7jls9JCbrgOAua5buFxJdW6JtbrgLRiY87U8rI98D5BbZF8BZmYCqKize-_qKtN9ZEJe1XNZrHRn_yJlErmVbIdiR4aPCxB5vFw
Content-Length: 181
Content-Type: application/x-www-form-urlencoded

DATA: timestamp=1449023203990&username=[SCRUBBED]&height=1280&width=720&max_video_height=640&max_video_width=480&req_token=2506bc6dde98450168afd190622ce83bd61530f28b2733f65180d1c133daa153
RESULT: <html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>401 UNAUTHORIZED</title>
</head>
<body text=#000000 bgcolor=#ffffff>

<h1>Error: UNAUTHORIZED</h1>

</body></html>

Warning: Invalid argument supplied for foreach() in /home/ubuntu/workspace/SC-API/SC-API/src/snapchat.php on line 1264

Call Stack:
    0.0001     234288   1. {main}() /home/ubuntu/workspace/SC-API/SC-API/examples/exampleBots/friendBot.php:0
    1.1132    2562416   2. Snapchat->getFriends() /home/ubuntu/workspace/SC-API/SC-API/examples/exampleBots/friendBot.php:20

Any help or advice on which direction to head in would be really appreciated!

**Comment by mgp25** [comment]
It seems your authfile is bad or your server is blocked

Regards
