### ISSUE TITLE
How to get statistics of snap ?

### ISSUE THREAD

**Issue by pank123** [mgp25/Snap-API#271]
I want to statistics of my snap.
Like no of views, no of screens ,No of time capture screenshot.
There is one site he has implmented this how can we get it. This is below url
https://app.snaplytics.io/#/account/demo/campaigns/12810
Looking forward

**Comment by mgp25** [comment]
https://github.com/mgp25/SC-API/wiki/How-to-use-proxy

**Comment by emiliobasualdo** [comment]
I didn't try proxy. But what I did was iterate through the return of the getUpdates function which provides all of that information. I also used msqly to keep record of the friend added over time.
