### ISSUE TITLE
return "ie" is not working and give us casper error.

### ISSUE THREAD

**Issue by pank123** [mgp25/Snap-API#274]
return "ie";    is not working for now. 

Fatal error: Uncaught exception 'CasperException' with message 'API Response: [503] The Snapchat version '9.16.2.0' is not currently supported by this endpoint.' in D:\Xampp\htdocs\snapchtapi\src\Casper-API-PHP\CasperAgent.php:180 Stack trace: #0 D:\Xampp\htdocs\snapchtapi\src\Casper-API-PHP\CasperAgent.php(95): CasperAgent->request('/snapchat/clien...', NULL, Array, true) #1 D:\Xampp\htdocs

**Comment by liamcottle** [comment]
Version `9.16.2.0` is no longer supported by my servers. You'll need to update the version in the Casper-API-PHP files to `9.18.2.0` for now.

**Comment by pank123** [comment]
I have change my casper version from 9.16.2.0 to 9.18.2.0
But its give me following error after change that
 stdClass Object ( [message] => Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :) [status] => -103 [logged] => ) RESULT: 1 
Is there any solution for that my credential is correct.

**Comment by kripsbro** [comment]
code = 404;
    message = "The Attestation Service is no longer available.";

**Comment by mgp25** [comment]
@kripsbro please read before comment!

**Comment by kripsbro** [comment]
I changed 9.18.2.0 and it wont work stdClass Object ( [message] => Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :) [status] => -103 [logged] => ) RESULT: 1

**Comment by mgp25** [comment]
@kripsbro of course it wont work! We havent enabled any system or algorithm to auth yet. If you are patient enough, i'll do a system so all people could login easily, but i have to fix some stuff from WA protocol. You can still capture your auth from your device using a proxy, remember to disable the cert pinning and there you go.

Regards
