### ISSUE TITLE
Update snapchat

### ISSUE THREAD

**Issue by HW73** [mgp25/Snap-API#275]
Hi, this might be a stupid question but do you know how to update Snapchat?

**Comment by teknogeek** [comment]
............................uhm. what platform

**Comment by HW73** [comment]
On Android, I'm connecting over ssh

**Comment by teknogeek** [comment]
you would have to open the play store and update it lol

**Comment by teknogeek** [comment]
or just install the latest APK

**Comment by HW73** [comment]
Fair enough, I'm not quite sure how to do this over ssh but I'll do some research. Thanks

**Comment by mgp25** [comment]
Use android debug mode

`adb install sc.apk`

Not API issue
