### ISSUE TITLE
 Snapchat version '9.23.0.1

### ISSUE THREAD

**Issue by k41ed** [mgp25/Snap-API#280]
API Response: [503] The Snapchat version '9.16.2.0' is not currently supported by this endpoint.

**Comment by mgp25** [comment]
Update the UA

Regards

**Comment by k41ed** [comment]
whats ua?

**Comment by teknogeek** [comment]
UA = User Agent but that isn't correct however. you need to change [this line](https://github.com/mgp25/SC-API/blob/ee826c20feb3b39c7fa5b88ea575a77b5da4dd16/src/Casper-API-PHP/CasperAPI.php#L12) to say

``` php
const SNAPCHAT_VERSION = "9.20.2.0";
```

instead of

``` php
const SNAPCHAT_VERSION = "9.16.2.0";
```
