### ISSUE TITLE
Error in logging snapchat api 

### ISSUE THREAD

**Issue by gerstaro** [mgp25/Snap-API#281]
I've Sniffed the traffic for snapchat in android using charles. HTTP requests goes to a private server API. then it send requests to Snapchat API as Shows below:

---

HTTP POST:

POST https://app.snapchat.com/loq/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Connection: keep-alive
Accept: _/_
User-Agent:Snapchat/9.2.0.0 (A0001; Android 4.4.4#5229c4ef56#19; gzip)
Accept-Language: en-US;q=1, ar-US;q=0.9
Accept-Encoding: gzip, deflate
Content-Length: 104

password=mypasst&sign=89390375953fb95443f5411ebbcea87ce58e002f76dee1e6a3edddb3d401b9cc&username=gerstaro

 I'd like to know how the post requests generate an "Sign="

Thankx

**Comment by teknogeek** [comment]
lmao 😂 before going any further, you're reversing version `9.2.0.0` and that has been depreciated for the past 8 months at least lol
