### ISSUE TITLE
PHP parse error.

### ISSUE THREAD

**Issue by arnarhelgi** [mgp25/Snap-API#282]
I am getting this error when I run 'php registerTool.php'  :
PHP Parse error:  syntax error, unexpected ')' in /home/pi/vendor/mgp25/snapapi/src/snapchat.php on line 3222.
PHP 5.4.45-0+deb7u4 (cli) (built: Jun 29 2016 17:23:52).
Any Ideas?? I really want to get this sorted out as soon as possible. Thanks!
![screenshot_251](https://cloud.githubusercontent.com/assets/13206793/18413305/7159e5b6-7793-11e6-96e5-c5a8caa8b3a0.png)

**Comment by mgp25** [comment]
Unafortunately this API is outdated, sorry

Regards

**Comment by arnarhelgi** [comment]
Oh that sucks, are there any alternatives?
