### ISSUE TITLE
mgp25/SC-API is not supporting?

### ISSUE THREAD

**Issue by maxim-danilov** [mgp25/Snap-API#286]
Casper API is not working. How can I use mgp25/SC-API? Maybe I can buy premium Casper API account?
Thanks!

**Comment by mgp25** [comment]
@700ghz i hate casper api, it makes users to pay. I have released some time ago the new auth of snapchat, eventually it will arrive here. Anyway, im doing an script-bridge API + emulator to get all auths + tokens working.

Im busy at the moment, but ill do it. Anyway, if any its interested, is just taking some requests from emulator and then putting the data back into the api.

Regards

**Comment by liamcottle** [comment]
I was going to build a free API for everyone, but you never got back to @teknogeek about the iOS tokens.

**Comment by Snowlav** [comment]
LOL are you joking Liam ?

**Comment by MarkVink** [comment]
Since the Casper API isn't accepting new registrants, this issue would apply to all new users of this project. Is there any way to use your library when you have an extracted AUTH_TOKEN?

**Comment by mgp25** [comment]
@MarkVink yes, is what Casper API is more or less doing. Its very easy to do a setup like that using emulators for example
