### ISSUE TITLE
Does this still work??

### ISSUE THREAD

**Issue by twitteriosdevelopment** [mgp25/Snap-API#289]

**Comment by mgp25** [comment]
Yes and no, unfortunately you need to get a key, purchasing it. If you are patient, i have released more than one year ago a way to use snapchat api for free, it eventually come here or be published

Regards

**Comment by twitteriosdevelopment** [comment]
I have a Casper key if that is useful?   
  

  
  

  
  
>

**Comment by mgp25** [comment]
Yes, but this API is now way too outdated, you should look to other repo
