### ISSUE TITLE
/all_updates 404

### ISSUE THREAD

**Issue by ddaddy** [mgp25/Snap-API#3]
Using your login method, `/all_updates` returns a 404 error. We must use `/log/all_updates` however the results are completely different.

**Comment by mgp25** [comment]
@ddaddy i know, ill be updating this soon.

Regards

**Comment by sveinbjorng** [comment]
Same thing in getMedia. 
Its supposed to be `/bq/blob`

**Comment by mgp25** [comment]
https://github.com/mgp25/Snap-API/commit/6ad650ddd2562cd892090fa4bbe468e45e092b61

Regards
