### ISSUE TITLE
getSnaps issue

### ISSUE THREAD

**Issue by sallaben** [mgp25/Snap-API#34]
I can login fine, that all works, no unauthorized errors, and I know I'm not blocked. What's up though with getSnaps? Whenever I call it I don't see any outgoing requests displayed even if `$debug=true`, and when I `var_dump` the `$snaps` variable (which is set to `$snapchat->getSnaps()`), I just get `bool(false)`.

what's up?

**Comment by mgp25** [comment]
@sallaben If you dont have any snap you will get a `false`

``` php
        $updates = $this->getUpdates();
        if(empty($updates))
        {
            return FALSE;
        }
```

It doesnt display anything in `Debug Mode` because its not a request. You can do 

``` php
$snapchat->getSnaps(true);
```

And it will store the snaps (if there is any)

Regards
