### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by thefactor** [mgp25/Snap-API#38]
`REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id Sent Request info: POST /loq/device_id HTTP/1.1 User-Agent: Snapchat/9.2.0.0 (A0001; Android 4.4.4#5229c4ef56#19; gzip) Host: feelinsonice-hrd.appspot.com Accept: _/_ Accept-Language: en;q=1 Accept-Locale: en Content-Length: 102 Content-Type: application/x-www-form-urlencoded DATA: timestamp=1.42754578431E+12&req_token=93014a575691fec86e6e9ee2f5abb7a43fec4d8119bd7a8139b4c214dbc51d6b RESULT:
Error: UNAUTHORIZED
RESULT:
Error: UNAUTHORIZED
REQUEST TO: https://android.clients.google.com/c2dm/register3 Array ( [device] => 3847872624728098287 [sender] => 191410808405 [app_ver] => 564 [gcm_ver] => 7097038 [app] => com.snapchat.android [iat] => 1427545785 [cert] => 49f6badb81d89a9e38d65de76f09355071bd67e7 ) DATA: 1 RESULT: token=APA91bE3od4Mtcd1w9hqwZpdkPrndfqwHAH_ruv8MGtmcf7-Gb--WjoRnb59tggIrEXD1ZRXHjOF4FmAAjsZBzyppFp9c6u1duGMI2dmHCTaWD8L0_qBiIzhQi5RsJ3X3TkRaJPHOELoM0Z4O6WaSmXlFifRhyfV7A REQUEST TO: https://android.clients.google.com/auth Array ( [device_country] => us [operatorCountry] => us [lang] => en_US [sdk_version] => 19 [google_play_services_version] => 7097038 [accountType] => HOSTED_OR_GOOGLE [system_partition] => 1 [has_permission] => 1 [add_account] => 1 [service] => ac2dm [source] => android [androidId] => 356663c3e9de45ef [get_accountid] => 1 [Email] => [app] => com.google.android.gms [client_sig] => 38918a453d07199354f8b19af05ec6562ced5788 [EncryptedPasswd] => ) DATA: 1 RESULT:
500. That’s an error.

There was an error. Please try again later. That’s all we know.

Snapchat Object ( [auth_token:protected] => [chat_auth_token:protected] => [username:protected] => xxxx [debug:protected] => 1 )`

**Comment by mgp25** [comment]
Your host/ip its blocked by Snapchat

Regards

**Comment by thefactor** [comment]
Thank you

**Comment by thefactor** [comment]
Just a question, do you know/have any way of replicating this in Xcode for an iOS app. @mgp25

**Comment by sallaben** [comment]
Just find some way to send API calls. However I don't think apple would
approve the code

**Comment by mgp25** [comment]
@sallaben could you contact me?

Regards

**Comment by sallaben** [comment]
@mgp25 check your me@mgp25 address
