### ISSUE TITLE
"QuotaExceeded" error when getting android device id

### ISSUE THREAD

**Issue by sallaben** [mgp25/Snap-API#40]
```
REQUEST TO: https://android.clients.google.com/c2dm/register3
Array
(
    [device] => 3847872624728098287
    [sender] => 191410808405
    [app_ver] => 564
    [gcm_ver] => 7097038
    [app] => com.snapchat.android
    [iat] => 1427587341
    [cert] => 49f6badb81d89a9e38d65de76f09355071bd67e7
)
DATA: 1
RESULT: Error=QuotaExceeded
```

so, uh, I'm figuring we need a new cert?

and now it works except doesn't download snaps. It downloads snaps on my personal account, however. any ideas? I just get `bool(false)` for `getSnaps()`

**Comment by sallaben** [comment]
and now it works except doesn't download snaps. It downloads snaps on my personal account, however. any ideas? I just get bool(false) for getSnaps()

**Comment by mgp25** [comment]
@sallaben should work now.

Use `getSnaps(true)` remember that `snaps` folders must have permissions to write data in it. Post debug of that, but its 100% working
