### ISSUE TITLE
Authentication with dynamic password generation fails

### ISSUE THREAD

**Issue by md726** [mgp25/Snap-API#42]
I'm currently using an old commit from your repository before the dynamic password authentication was implemented.

Today I thought to update my scripts while using your newest commit but I'm only getting a `Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)`

I tried to change `line 199` on `snapchat.php` from:

```
'EncryptedPasswd' => $password
```

to:

```
'EncryptedPasswd' => 'oauth2rt_1/evzrOtQ2qaGBrmz4VkJG-KMyIOsASmhluoocbXeDVhM'
```

and since I'm able to login and to get my results again.

My server seems to receive the values from `https://tekno.pw/snapchat_password.php` since I did some debug outputs and received email and `encryptedPassword` in the JSON file.

Is there anyone with some thoughts on that? And is it possible to provide the `snapchat_password.php` script to host it locally without calling the external server?

Thanks to you all! :-)

**Comment by mgp25** [comment]
@mands72 Retry again, it should work.

We can't provide that script sorry, you can capture your own data instead by using a proxy.

Regards

**Comment by KyleBoyer** [comment]
You can also change the email and password to use your own google account. Simply replace the 'email' field with your own google account. Then replace EncryptedPasswd, with "Passwd" and set the value equal to your own google account password.

**Comment by md726** [comment]
@mgp25 I wasn't able to make it working with the dynamic JSON file. But... :

@KyleBoyer Great! Thank you! I really like that solution and it's working!

**Comment by sallaben** [comment]
I still get unauthorized even when using my own google account, although it
doesn't say anything about incorrect login anymore.

```
REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/conversation_auth_token

Sent Request info: POST /loq/conversation_auth_token HTTP/1.1
User-Agent: Snapchat/9.2.0.0 (A0001; Android 4.4.4#5229c4ef56#19; gzip)
Host: feelinsonice-hrd.appspot.com
Accept: */*
Accept-Language: en;q=1
Accept-Locale: en
Content-Length: 148
Content-Type: application/x-www-form-urlencoded


DATA: username=seents×tamp=1427664177725&conversation_id=username~username&req_token=096ec71fb87ee1d506910711b188234c996e1bc3522~censor~
RESULT:



Error: UNAUTHORIZED
```

**Comment by KyleBoyer** [comment]
A few basic things to check, your google login information was changed in both locations(you may have changed only one of the locations in the script). Your gmail/password combo is correct. Your snapchat username/password combo is correct?
