### ISSUE TITLE
Issues running with XAMPP

### ISSUE THREAD

**Issue by aurnik** [mgp25/Snap-API#44]
Sorry that this is more of a personal issue but I really don't know what I'm doing wrong. I brought over this whole folder into XAMPP and when I run exampleFunctional with my Snapchat login I get the following:

```
Notice: Undefined variable: auth_token in /Applications/XAMPP/xamppfiles/htdocs/snaps/examples/exampleFunctional.php on line 15

Warning: curl_setopt(): supplied argument is not a valid File-Handle resource in /Applications/XAMPP/xamppfiles/htdocs/snaps/src/snapchat_agent.php on line 378

Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /Applications/XAMPP/xamppfiles/htdocs/snaps/src/snapchat.php on line 123

Warning: file_get_contents(): Failed to enable crypto in /Applications/XAMPP/xamppfiles/htdocs/snaps/src/snapchat.php on line 123

Warning: file_get_contents(https://tekno.pw/snapchat_password.php): failed to open stream: operation failed in /Applications/XAMPP/xamppfiles/htdocs/snaps/src/snapchat.php on line 123
My friends:
```

But I'm assuming that rather than 5 different problems it's actually just one thing that I set up wrong.

Any advice?

**Comment by mgp25** [comment]
@aurnik could you run it in terminal / cmd? Maybe you havent installed the dependencies + related problems with XAMPP. It will be easier and faster if you run the scripts with shell / cmd / terminal :stuck_out_tongue_winking_eye:

**Comment by aurnik** [comment]
Thanks for the quick reply! Even in the terminal I'm still getting this after installing dependencies (had to do php53-*)

```
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure in ../src/snapchat.php on line 123

Warning: file_get_contents(): Failed to enable crypto in ../src/snapchat.php on line 123

Warning: file_get_contents(https://tekno.pw/snapchat_password.php): failed to open stream: operation failed in ../src/snapchat.php on line 123
```

**Comment by mgp25** [comment]
@aurnik you need to enable crypto, you hare having problems with SSL

**Comment by aurnik** [comment]
Ah okay, I'm a bit of an amateur though, do I need to add an additional parameter to line 123?

``` php
$passwordJSON = file_get_contents("https://tekno.pw/snapchat_password.php");
```

Also I'm on OS X if that changes anything

**Comment by KyleBoyer** [comment]
I'll push a fix to this. The solution is to use CURL with the certificate. I ran into the same problem on my mac, and for some reason it is just having problems with OpenSSL in combination with PHP.
