### ISSUE TITLE
401 UNAUTHORIZED

### ISSUE THREAD

**Issue by Mxchael** [mgp25/Snap-API#5]
Hi,

I keep getting `401 unauthorized`. Cannot seem to work out why.

Any guide on how to fix or what is needed to get this setup. I noticed it has places for gmail email and stuff. Is that needed?

**Comment by mgp25** [comment]
It has default values, it should work. Can you paste your debug and code?

Regards

**Comment by Mxchael** [comment]
@JayNZ will paste our code

**Comment by jzush** [comment]
``` php
    $snapchat = new Snapchat();
    $snapchat->login('usr', 'pwd');
    $snaps = $snapchat->getSnaps(); 
```

**Comment by Mxchael** [comment]
Using the default example with only the username and password filled out even returns 401 UNAUTHORIZED

**Comment by KyleBoyer** [comment]
> Using the default example with only the username and password filled out even returns 401 UNAUTHORIZED

The login function does, or the getSnaps function does?

**Comment by Mxchael** [comment]
@KyleBoyer 
Using the following 

``` php
require_once('./src/snapchat.php');
//////////// CONFIG ////////////
$username = 'SendThatSnapTes'; // Your snapchat username
$password = 'abc123456'; // Your snapchat password
$debug = true; // Set this to true if you want to see all outgoing requests and responses from server
////////////////////////////////
$snapchat = new Snapchat($username, $auth_token, $debug);
$snapchat->login($username, $password);
```

Produces the 401

**Comment by KyleBoyer** [comment]
Make sure the auth_token is empty when you call the login function. I'll take a closer look in a little bit when I'm on my computer.

**Comment by Mxchael** [comment]
@KyleBoyer Auth token is empty. Okay cool hopefully you can figure it out :)

**Comment by KyleBoyer** [comment]
Do you have skype?
Also, there was a recent pull request on this repo, try using that?

**Comment by KyleBoyer** [comment]
I'm just using:

``` PHP
include_once 'dependencies/snapchat.php';
$su = "username";
$sp = "password";
$snapchat = new Snapchat($su);
$login = $snapchat->login($su, $sp);
```

**Comment by Spurlex** [comment]
Trying with that code doesn't seem to do anything. Page just renders white. No error or nothing.

Skype Xelrups @KyleBoyer

**Comment by mgp25** [comment]
Can you try it in terminal / shell / cmd instead of webserver?

Regards

**Comment by Mxchael** [comment]
@mgp25 How exactly do I do that :)

**Comment by mgp25** [comment]
Solved: curl wasnt installed

Regards

**Comment by Mxchael** [comment]
This still wont work on my webserver. Works locally in terminal
@KyleBoyer @mgp25 

I get the following errors in php.

```
Notice: Undefined variable: auth_token in /home/spurlex/public_html/web/snap/index.php on line 17
Notice: Undefined variable: multipart in /home/spurlex/public_html/web/snap/src/snapchat.php on line 90
Notice: Undefined index: error in /home/spurlex/public_html/web/snap/src/snapchat.php on line 251
Notice: Trying to get property of non-object in /home/spurlex/public_html/web/snap/src/snapchat.php on line 285
Notice: Trying to get property of non-object in /home/spurlex/public_html/web/snap/src/snapchat.php on line 286
Notice: Undefined variable: multipart in /home/spurlex/public_html/web/snap/src/snapchat.php on line 295
Notice: Undefined index: error in /home/spurlex/public_html/web/snap/src/snapchat.php on line 299
```

**Comment by sveinbjorng** [comment]
@Spurlex missing php-curl?

**Comment by Mxchael** [comment]
@sveinbjorng cURL support   enabled
(CurlSSL)

**Comment by Mxchael** [comment]
http://spurlex.com/web/snap/index.php I added PHPINFO to bottom of this so you guys can see if i've missed anythig
@sveinbjorng @KyleBoyer @mgp25

**Comment by sveinbjorng** [comment]
@Spurlex My guess is that the server is blacklisted.

**Comment by Mxchael** [comment]
Server was blacklisted. Using a new IP from different server works :)
