### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by ghost** [mgp25/Snap-API#52]
It worked yesterday. But just now login returns error. Has something changed?

**Comment by teknogeek** [comment]
what is the error

**Comment by teknogeek** [comment]
We changed the login and constructor methods today. This is how you want to create it now

``` php
$snapchat = new Snapchat($username, $debug);
$snapchat->login($password);
```

instead of

``` php
$snapchat = new Snapchat($username, $auth_token, $debug);
$snapchat->login($username, $password);
```
