### ISSUE TITLE
Is there a auth_token timeout?

### ISSUE THREAD

**Issue by md726** [mgp25/Snap-API#53]
Good morning guys,
It seems I'm able to use the auth_token for login/fetching data when the time between the requests is short (a couple minutes). But when I wait a few more minutes (10-15) the script recognizes the auth.dat file but cannot login because the token seems to be expired (?). I have to delete the file manually to be able to fetch data again. Is it neccessary to do a logout every time to delete the auth.dat or am I doing something else wrong?

Thanks you!

**Comment by mgp25** [comment]
@mands72 there is no time out. If you use `logout()` or login in your device it will revoke your auth.

No, its not necessary to `logout()` its better you keep online. Use this `$snapchat->closeAppEvent();`

If you get stuck get your auth, you don´t  need to delete the auth manually, just do this:

``` php
$snapchat->login($password, true);
```

But only use it if you get stuck with auth, you need to simulate as much as possible Snapchat, so its better not to be logging in multiple times, thats why its better to keep online with the auth.

Regards
