### ISSUE TITLE
Notice:  Undefined index: request_header in snapchat_agent.php on line 386

### ISSUE THREAD

**Issue by NichoTheMan** [mgp25/Snap-API#55]
Whenever i do something i get this error:

```
Notice:  Undefined index: request_header in C:\xampp\htdocs\snap\api\snapchat_agent.php on line 386
```

And it pulls no valid information or any information at all.

EDIT:
created a new folder without changing any names uploading all the content from the zip as it is, still get the same error:

```
Notice: Undefined index: request_header in C:\xampp\htdocs\snapchat\src\snapchat_agent.php on line 386
```

![0475939c677397c9a91ea390866cfb78 1](https://cloud.githubusercontent.com/assets/5790097/6927003/9fd29bf8-d7ea-11e4-8744-07eade8314b6.png)
![30e8564af71f2db3841ddbe0c7d4751b 1](https://cloud.githubusercontent.com/assets/5790097/6927149/b3ffcf6e-d7eb-11e4-960b-19217ecc0357.png)
![a7de02bb1e2c3b23b9c89a4df277fa42 1](https://cloud.githubusercontent.com/assets/5790097/6927157/bd64384c-d7eb-11e4-9c01-3c75cc982acc.png)
![a5ea591635ffb76f648e115fc9879edf 1](https://cloud.githubusercontent.com/assets/5790097/6927162/c59b1616-d7eb-11e4-9780-b3b356d93fa4.png)

**Comment by mgp25** [comment]
@NichoTheMan try running the script in terminal / shell / cmd. Sometimes XAMPP isnt the best choice.

Regards

**Comment by NichoTheMan** [comment]
Okay, now i installed wamp on the server, still getting the same error, tried it in CMD, got the same errors aswell.

**Comment by mgp25** [comment]
@NichoTheMan it should work now

Regards
