### ISSUE TITLE
Should i login everytime I poll the server?

### ISSUE THREAD

**Issue by ObjectiveTruth** [mgp25/Snap-API#56]
Firstly, great job on this library man, so happy you maintain it so well.:+1:

Anyways, I'm planning on using the cli and I want to know your opinion on logging into the server.

If i make a script that polls the server every `n` seconds, should I call `login()` on every iteration before `getFriends()` and `getSnaps(true)` or is it safe to just call `getFriends()` and `getSnaps(true)`

is it enough that I do it at the beginning of the script? I'm worried they might see me logging in too many times and ban the account. But then again do I have to refresh the login tokens?

Cheers

**Comment by Mxchael** [comment]
Its possible to get banned with that. Usually just the network banned. I've implemented a system where I cache the auth_token and just use that to login and haven't had any bans since.

**Comment by ObjectiveTruth** [comment]
@Spurlex That's interesting, I investigated the code a bit (I'm no php expert) and noticed there's alot of checks for the auth_token already.

Leads me to believe I can just call get `getFriends()` and `getSnaps(true)` without having to worry about the low level auth_token cache handling myself?

Just noticed https://github.com/mgp25/Snap-API/issues/53 which makes me think I should just poll every few minutes and if i do try/catch and it fails then I'll redo the `login()`

**Comment by mgp25** [comment]
@ObjectiveTruth if you are using the latest code, you can login normally all the times you want because you will remain logged in because of the auth token, this is done by the API by default (you will notice a file called `auth.dat`)

Consider using `$snapchat->closeAppEvent();` before exit the script

Regards
