### ISSUE TITLE
Errors with getSnaps()

### ISSUE THREAD

**Issue by adrienrougeron** [mgp25/Snap-API#59]
Hello, when I use the getSnaps() function, I get that : 

> **Notice:** Trying to get property of non-object in /public_html/test/src/snapchat.php on line 927
> **Warning:** Invalid argument supplied for foreach() in /public_html/test/src/snapchat.php on line 928
> array(0) { }

My code is : 

``` php
require_once("src/snapchat.php");
$username = "name";
$password = "pass";
$debug = false;
$snapchat = new Snapchat($username,$debug);
$snapchat->login($username,$password);
$snaps = $snapchat->getSnaps();
var_dump($snaps);
```

Thanks for helping me !

**Comment by mgp25** [comment]
@adrienrougeron Update your code:

``` php
$snapchat->login($password);
```

If you set `$debug` to `true`, you will see more information..

Regards
