### ISSUE TITLE
login issue 

### ISSUE THREAD

**Issue by ghost** [mgp25/Snap-API#60]
As of right now when I login I keep getting message "Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)", with a status code of -103.

Thanks.

**Comment by teknogeek** [comment]
what email is it using

**Comment by ghost** [comment]
magicloginswag1@gmail.com,  or test@gmail.com?

**Comment by teknogeek** [comment]
first one. try again and tell me if it gives you the error again (should be
a different first email)

**Comment by ghost** [comment]
Still get the same error with magicloginswag4@gmail.com

**Comment by teknogeek** [comment]
hmm might be your account. can you try a different one? if not I'll remove
those emails from the selections

**Comment by ghost** [comment]
I tried different accounts, same error. I'm pretty sure it is not my account. Even if you give a random username and password, it still return the same message. It should be "wrong password" or something different.

So the script still works for you as of now?

**Comment by teknogeek** [comment]
I'll double check it for myself

**Comment by ghost** [comment]
magicloginswag3@gmail.com this one also doesn't work. Arent' these emails only used for google auth? It appears google auth does work fine. It's the last login call that fails.

**Comment by k41ed** [comment]
login doesn't work

**Comment by teknogeek** [comment]
aware and looking into it

**Comment by ghost** [comment]
@teknogeek Thanks!

**Comment by mgp25** [comment]
People, if you use last code, once you are logged in, you dont need to use google auth anymore!

just do

``` php
$snapchat->login($password);
```

**Comment by ghost** [comment]
@mgp25 I know. But once you logged in from your phone, you have to re-login. You can not really log in now.

**Comment by mgp25** [comment]
@rpw98 sniff your auth token from your phone and use it with the API.

**Comment by ghost** [comment]
I don't know how :-(

**Comment by md726** [comment]
@rpw98 Use a proxy on your computer like http://www.charlesproxy.com/ and set up your phone to use this proxy. If you also enable SSL you can look on your computer into the requests your App is doing to find out the token.

**Comment by ghost** [comment]
But that really defeats my purpose of using this api :-( I was trying to build a client.

**Comment by k41ed** [comment]
where i will put the sniffed  auth token

**Comment by k41ed** [comment]
it's working

**Comment by aurnik** [comment]
@k41ed What did you do?

**Comment by mgp25** [comment]
Put the sniffed auth token in the `auth.dat` file, as simply as that

**Comment by teknogeek** [comment]
pull the latest commit :)

**Comment by ghost** [comment]
Are you sure it works? It still doesn't work for me:

`Warning: gzdecode(): data error in D:\webs\snapsave\src\snapchat_agent.php on line 401`

It appears `login()` call returns nothing.

**Comment by rpw98** [comment]
It appears login() call returns nothing.

**Comment by sallaben** [comment]
I got gzdecode error on specific accounts. I get it on an account with 30000+ friends and about 6 months old, I get it on an account with 0 friends that I just made, but I don't get it on an account about half a month old with ~40 friends.

Any ideas?

**Comment by teknogeek** [comment]
try again
