### ISSUE TITLE
login() issue, property of non-object from response to request

### ISSUE THREAD

**Issue by ObjectiveTruth** [mgp25/Snap-API#62]
I keep getting this error, everything was working fine a few days ago. My guess is that it can't find those tokens its looking for and its causing havok.

Here the issue on line [#354-355](https://github.com/mgp25/Snap-API/blob/master/src/snapchat.php#L354-L355)

Output

```
REQUEST TO: https://android.clients.google.com/auth
Array
(
    [device_country] => us
    [operatorCountry] => us
    [lang] => en_US
    [sdk_version] => 19
    [google_play_services_version] => 7097038
    [accountType] => HOSTED_OR_GOOGLE
:PHP Notice:  Trying to get property of non-object in /home/objectivetruth/SnapchatBot-API/src/snapchat.php on line 354
PHP Stack trace:
PHP   1. {main}() /home/objectivetruth/SnapchatBot-API/examples/exampleFunctional.php:0
PHP   2. Snapchat->login() /home/objectivetruth/SnapchatBot-API/examples/exampleFunctional.php:18
PHP Notice:  Trying to get property of non-object in /home/objectivetruth/SnapchatBot-API/src/snapchat.php on line 355
PHP Stack trace:
PHP   1. {main}() /home/objectivetruth/SnapchatBot-API/examples/exampleFunctional.php:0
PHP   2. Snapchat->login() /home/objectivetruth/SnapchatBot-API/examples/exampleFunctional.php:18
    [Email] => test@gmail.com
    [service] => audience:server:client_id:694893979329-l59f3phl42et9clpoo296d8raqoljl6p.apps.googleusercontent.com
    [source] => android
    [androidId] => 378c184c6070c26c
    [app] => com.snapchat.android
    [client_sig] => 49f6badb81d89a9e38d65de76f09355071bd67e7
    [callerPkg] => com.snapchat.android
    [callerSig] => 49f6badb81d89a9e38d65de76f09355071bd67e7
    [EncryptedPasswd] => oauth2rt_1/F0QMC8_1pq-IJdk2P6Iw5DC3F47Pn7MCU0D8gaku5OU
)
```

**Comment by nickcicero** [comment]
If you haven't read this article you should. Just came out yesterday.
Snapchat supposedly actively trying to close up people using their APIs
altogether. We work with a lot of Snapchat influencers and they're all
experiencing the issues when they auth in on their various devices.

https://medium.com/backchannel/snapchat-s-non-vanishing-message-you-can-trust-us-6606e6774b8b

On Fri, Apr 3, 2015 at 11:48 AM, Jose Miguel Mendez <
notifications@github.com> wrote:

> I keep getting this error, everything was working fine a few days ago. My
> guess is that it can't find those tokens its looking for and its causing
> havok.
>
> Here the issue on line #354-355
> <https://github.com/mgp25/Snap-API/blob/master/src/snapchat.php#L354-L355>
>
> Output
>
> REQUEST TO: https://android.clients.google.com/auth
> Array
> (
>     [device_country] => us
>     [operatorCountry] => us
>     [lang] => en_US
>     [sdk_version] => 19
>     [google_play_services_version] => 7097038
>     [accountType] => HOSTED_OR_GOOGLE
> :PHP Notice:  Trying to get property of non-object in /home/objectivetruth/SnapchatBot-API/src/snapchat.php on line 354
> PHP Stack trace:
> PHP   1. {main}() /home/objectivetruth/SnapchatBot-API/examples/exampleFunctional.php:0
> PHP   2. Snapchat->login() /home/objectivetruth/SnapchatBot-API/examples/exampleFunctional.php:18
> PHP Notice:  Trying to get property of non-object in /home/objectivetruth/SnapchatBot-API/src/snapchat.php on line 355
> PHP Stack trace:
> PHP   1. {main}() /home/objectivetruth/SnapchatBot-API/examples/exampleFunctional.php:0
> PHP   2. Snapchat->login() /home/objectivetruth/SnapchatBot-API/examples/exampleFunctional.php:18
>     [Email] => test@gmail.com
>     [service] => audience:server:client_id:694893979329-l59f3phl42et9clpoo296d8raqoljl6p.apps.googleusercontent.com
>     [source] => android
>     [androidId] => 378c184c6070c26c
>     [app] => com.snapchat.android
>     [client_sig] => 49f6badb81d89a9e38d65de76f09355071bd67e7
>     [callerPkg] => com.snapchat.android
>     [callerSig] => 49f6badb81d89a9e38d65de76f09355071bd67e7
>     [EncryptedPasswd] => oauth2rt_1/F0QMC8_1pq-IJdk2P6Iw5DC3F47Pn7MCU0D8gaku5OU
> )
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Snap-API/issues/62>.
>



-- 
Nick Cicero
315-720-0677

Email: ncicero0@gmail.com
Website: http://nickcicero.com
Twitter:   @nickcicero <http://www.twitter.com/nickcicero>
LinkedIN: http://www.linkedin.com/in/nicholascicero
<http://www.linkedin.com/in/nicholascicero>

**Comment by ObjectiveTruth** [comment]
Ah, gotcha. 
I know they are cracking down hard, just figure someone might of found a way to slip by.

I bet they're reading this conversation right now....

Yo Snapchat Developers:exclamation:, 
Go home and enjoy the Easter holidays with your families and stop reading github forums :unamused:

**Comment by teknogeek** [comment]
Hahaha yea me and @mgp25 are digging but I'll try to :) thanks, you too!

**Comment by teknogeek** [comment]
pull the latest commit :)

**Comment by GarrettBlackmon** [comment]
I've been racking my brain for hours with this problem. If it was last fixed with a commit I think it may need another update. My local IP gets the 403 UNAUTHORIZED error when i run the code locally. (however I can log in from my mobile phone.) When I attempt to use a proxy I get the error above. I'm working on getting my auth_token but I don't yet know what I'm looking for which is why I wanted the API to log me in once so I would have an example. If anyone wants to make some documentation or either give me a quick few sentence lesson I'll make a nice write-up after all the trouble it's cause me.

**Comment by mgp25** [comment]
403 UNAUTHORIZED = IP blocked

**Comment by GarrettBlackmon** [comment]
What's happening to the other guy that was going through a VPN with lots of IPs is happening to me as well. I've tried probably 30+ proxy's, and 4 different digital ocean IPS as well as my home connection really trying to follow the consensus that 403 means an IP ban.

However, everything broke down when I completely logged out of Snapchat on my mobile phone connected to my home network and logged into the account without problems.

Is there an explanation for this? It's my understanding that it would not be using an auth_token on its first log in rather would generate one.

**Comment by sallaben** [comment]
There can only be one login session at a time. You can't be logged in on
two devices with the same account.
