### ISSUE TITLE
Login still not working for me

### ISSUE THREAD

**Issue by ghost** [mgp25/Snap-API#63]
I'm getting: 

```
Warning: gzdecode(): data error in D:\webs\snapsave\src\snapchat_agent.php on line 401
```

It appears `login()` call returns nothing.

**Comment by teknogeek** [comment]
please show me your code

**Comment by ghost** [comment]
I just run the example.

**Comment by teknogeek** [comment]
did you fill in your username and password in the variables

**Comment by ghost** [comment]
``` php
$username = "xxxxx"; // Your snapchat username
$password = "xxxxx"; // Your snapchat password
$debug = true; // Set this to true if you want to see all outgoing requests and responses from server
////////////////////////////////

$imagePath = ""; // URL or local path to a media file (image or video)
$sendTo = array();

$snapchat = new Snapchat($username, $debug);

//Login to Snapchat with your username and password
$snapchat->login($password, true);

// Get your friends in an array
$friends = $snapchat->getFriends();

echo "My friends: ";
print_r($friends);
```

**Comment by ghost** [comment]
@teknogeek yes, sure.

**Comment by teknogeek** [comment]
can you copy and paste the entire output please

**Comment by teknogeek** [comment]
can you copy and paste the entire output please and make sure you xxxx your username and password :P

**Comment by rpw98** [comment]
Yes, of course. I'm programmer, too. :-)

**Comment by ghost** [comment]
Yes, of course. I'm programmer, too. :-)

```
REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id DATA: timestamp=1428089212776&req_token=93043258e961d6586e0365eef7a60c9471ea4d8a19792a8969b48514dfc51c0b RESULT: REQUEST TO: https://android.clients.google.com/auth Array ( [device_country] => us [operatorCountry] => us [lang] => en_US [sdk_version] => 19 [google_play_services_version] => 7097038 [accountType] => HOSTED_OR_GOOGLE [system_partition] => 1 [has_permission] => 1 [add_account] => 1 [service] => ac2dm [source] => android [androidId] => 356663c3e9de45ef [get_accountid] => 1 [Email] => dontliketoken4@gmail.com [app] => com.google.android.gms [client_sig] => 38918a453d07199354f8b19af05ec6562ced5788 [EncryptedPasswd] => AFcb4KRcd9cRtNc0vFCnCFAWQL29BKteRTnqFADGBdw67LB4sVWebMDHOnughNT1ECj5Pr_xuCeeY5TzwgiqrC-ZqW4ASJ4HLNORRVToSgsiGxn9sKROOW2nuHZwlp315drgwlF9E_yEqRZSU_oxyhf6tff8UGT6f1A_vDJYTr1TtV-ybg== ) DATA: 1 RESULT: SID=DQAAAMkAAACQGpwsmDhQLa1JQAX-8si_N9dcVapeXLV4i2DM0Q0TSoW8kazm8Fx7PjDWkj0UjUL8ZuIJef_AN6FYq94hOJM7kjNnbAIfF0cXPeRVElU06TLyIeGHg7968IjgcQOTuR26Y6EUYmtR-L44V4Q1Fz9Jv8VOyvN70V5Tjr2egYCf0eLRqgBKhq5fkvmIqwi0nIRhzNylZVRb_MOx529Egy3opVs4EgNbYFJ3WHxd353vf10pA4vv2hXfTXYwM9mCtTciyZ85Oew5fO75qu9j9yI9 LSID=DQAAAMsAAAB9lUbaBRgRo_9XF-mcWE9AtbvTVpjxj9L22Al5uq3KThdqdbKuxcJSAKRl-F1PFaZ8EMYZIPeAngDcFkLmTPsC0MrZtl5_j8tGsMSvDYzW6tg9TCe-hYh7ChgC5z6FyVaqo_eYO5tubBoRRk8ky6cB_ijf9ajlBB3r4YMF9gbb73lKstwO9V4ELugaX8tT3RVthehb8ncu34Lw6ZpU-RDvOeQ2Yp1Qtvk5KvZ8ov-Iumi2pEcDZPfXonF9Mp_NLTNQTpZ4mqeDkib4mjgd-YBv Auth=DQAAAMwAAAAEM3DEVYNYuDFGvqR1XlvYBZEGZaKqBAYmMPIuF1IagjT5-CPtUGArSQ3LYfLWOySD3AkoPcnQ9bnW4pbqRBoi5kaeCz3l52z8gyrYWaXMcEvEZ8AK3enchrLvxJ3mEECH8MbPQyQZc42xu8K6x92kfESRDRW5_OPcJkOH0bZFRaMoYCFtS2Nk8FM3swmff9VepFTwWsVHRXYg9jFjDKn7hgZcJAQSgJ_kfa8HfrKi-zPGcf4XZncWEfc_z1UMn-tScUgbacuAKXfkR1ENKTaQ issueAdvice=auto services=hist,mail Email=dontliketoken4@gmail.com Token=oauth2rt_1/IbRLQWjkqUfMw0HxHmrb5bhfavPs0mkhegAjN54dQhA GooglePlusUpgrade=1 RopText= RopRevision=1 firstName=larry lastName=cucumber accountId=109571864279016666127 REQUEST TO: https://android.clients.google.com/auth Array ( [device_country] => us [operatorCountry] => us [lang] => en_US [sdk_version] => 19 [google_play_services_version] => 7097038 [accountType] => HOSTED_OR_GOOGLE [Email] => test@gmail.com [service] => audience:server:client_id:694893979329-l59f3phl42et9clpoo296d8raqoljl6p.apps.googleusercontent.com [source] => android [androidId] => 378c184c6070c26c [app] => com.snapchat.android [client_sig] => 49f6badb81d89a9e38d65de76f09355071bd67e7 [callerPkg] => com.snapchat.android [callerSig] => 49f6badb81d89a9e38d65de76f09355071bd67e7 [EncryptedPasswd] => oauth2rt_1/IbRLQWjkqUfMw0HxHmrb5bhfavPs0mkhegAjN54dQhA ) DATA: 1 RESULT: issueAdvice=auto Auth=eyJhbGciOiJSUzI1NiIsImtpZCI6IjE4Mjg4ZTRmMTA2NzA3ZWI2OTkzMmY3NTRhNTk2MTQxYjllN2M3MDUifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwic3ViIjoiMTA5NTcxODY0Mjc5MDE2NjY2MTI3IiwiYXpwIjoiNjk0ODkzOTc5MzI5LXFnMGkwdTg4dDBobThrNmsxbWJyYm5zdWoxMDFoNzN2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJkb250bGlrZXRva2VuNEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXVkIjoiNjk0ODkzOTc5MzI5LWw1OWYzcGhsNDJldDljbHBvbzI5NmQ4cmFxb2xqbDZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiaWF0IjoxNDI4MDg5MTc4LCJleHAiOjE0MjgwOTI4MDh9.j8s88otC0f9eS0AQUtS5LmxMX07mWN3xZZ9DXeHuYBvdyoqZlGsXnjX_Ez-fpS0vrCpsAafVbutVQKMvDLksbF_4bFVL2lgMzRDBcOByJIKQhjCQA3t3Qzkgpa7a-moY5f43haffn4m5jbh0vHq1k36WTgSEAgcMJ7qoXQpJDk4 Expiry=1428092808 storeConsentRemotely=1 REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/login DATA: username=bpbai&password=xxxxxxxx&height=1280&width=720&max_video_height=640&max_video_width=480&dsig=ad10564adacddfa41bad&dtoken1i=00001%3AK%2FzKR4GcQtKSenJKzlmRshQdWK7bV8HB5XVUHWmFBtNTTriz5dlNYbrYb08%2FFjYQ&ptoken=ie×tamp=1428089213119&req_token=93001852a2318be86e0d43e2f1a9c4844ee14d8319ca6a8849b4c814d6c51cfb Raw result:
( ! ) Warning: gzdecode(): data error in D:\webs\snapsave\src\snapchat_agent.php on line 402
Call Stack
#   Time    Memory  Function    Location
1   0.0000  240504  {main}( )   ..\exampleFunctional.php:0
2   0.0156  780392  Snapchat->login( )  ..\exampleFunctional.php:18
3   4.1496  786560  SnapchatAgent->post( )  ..\snapchat.php:367
4   4.2120  796176  gzdecode ( )    ..\snapchat_agent.php:402
RESULT: 1 My friends: 
```

**Comment by ghost** [comment]
I added one line before gzdecode() call to print out the "Raw result".

**Comment by teknogeek** [comment]
are you sure that you are using the latest version? it should print request headers too

**Comment by ghost** [comment]
@teknogeek If you want my account to test, let me know your email and I will send it to you.

**Comment by teknogeek** [comment]
joel@ocelotworks.com

**Comment by ghost** [comment]
Just sent it.

**Comment by teknogeek** [comment]
I was able to log in successfully with that account using the API

**Comment by ghost** [comment]
What? I just redownload the code and only change the username and password, and run it. What I get is this:

"My friends: You must add username to your friends list first! "

**Comment by teknogeek** [comment]
that's because it's trying to send a message to "username" who isnt on your friends list

**Comment by ghost** [comment]
Shouldn't it print out friend list?

**Comment by teknogeek** [comment]
yes

**Comment by rpw98** [comment]
But it printed this message. So you are able to run the same script and get my friend list?

**Comment by ghost** [comment]
But it printed this message. So you are able to run the same script and get the friend list?

I found these lines a little puzzling:

``` php
if($endpoint == "/loq/login" || $endpoint == "/all_updates")
            {
                $result = gzdecode($result);
                $jsonResult = json_decode($result);
                echo 'RESULT: ' . print_r($jsonResult) . "\n";
            }
```

First shouldn't it be `/loq/all_updates` instead of `all_updates`? Also, why is `gzdecode()` called only in the debug mode?

Maybe you didn't check in the right version?

**Comment by rpw98** [comment]
Maybe you didn't check in the right version?

**Comment by teknogeek** [comment]
hmm true. i will push a change

**Comment by mgp25** [comment]
@rpw98 it will be nice if you quote code and debug for easy reading

**Comment by ghost** [comment]
@mgp25 I will do. Thank you! I thought it was automatically formatted by some github magic :P

**Comment by teknogeek** [comment]
(editing is magic)

**magic** :smile:

**Comment by ghost** [comment]
@teknogeek I see your new checkin. But it still doesn't work for me. login call returns nothing :-(

**Comment by teknogeek** [comment]
not sure what's wrong on your end then

**Comment by teknogeek** [comment]
not sure what's wrong on your end then. 

Make sure that there's not an auth.dat file or `auth-<username>.dat` file in the folder

**Comment by ghost** [comment]
There was no such file because it never worked. I deleted the whole folder before putting in new one any way. Why doesn't it work for me?😫

**Comment by teknogeek** [comment]
honestly i have no idea xD hard to say without being there and looking at it myself

@mgp25 ideas?

**Comment by teknogeek** [comment]
@mgp25 ideas?

**Comment by ghost** [comment]
Could it be some of my php setup? I use wamp on a Windows PC.

Can someone else confirm if the new code works for you please?

**Comment by rpw98** [comment]
Can someone else confirm if the new code works for you please?

**Comment by teknogeek** [comment]
it might be. im also on windows but using the direct binary

**Comment by ghost** [comment]
Oh god... I'm gonna go crazy tonight 😫

I just tried it on a remote server, it works! Still don't know why it doesn't work on my local server but I can't complain too much now :-)

**Comment by rpw98** [comment]
I just tried it on a remote server, it works! Still don't know why it doesn't work on my local server but I can't complain too much now :-)

**Comment by k41ed** [comment]
gzdecode(): data error 
what is the solution
this is the most api i found alot of problems in it 
instagram api , and whatapp api working wonderful

**Comment by ObjectiveTruth** [comment]
@k41ed if you find it so bad you should try to improve it, brotha.

@rpw98 You find anything on your end? I'm going to try it on my server and see if I get any different results, but so far I can't get it to work on my local system :sob:

**Comment by ghost** [comment]
No, I can't get it on my local server to work after I tried a few php settings. But my remote server works.

**Comment by ObjectiveTruth** [comment]
@rpw98 Holy hell, i got it to work, well on my server, works flawlessly. 

I'm wondering if our comps are part of this "collateral damage" they're talking about

> When Snapchat detects suspicious activity, it shuts down the Internet neighborhood where the threat originates, even at the risk of affecting innocent users. “We were willing to cause a little bit of collateral damage to regular users

[source](https://medium.com/backchannel/snapchat-s-non-vanishing-message-you-can-trust-us-6606e6774b8b)

**Comment by mgp25** [comment]
@k41ed this API its still in develop, if you only bother and dont contribute then your comments are useless, try to find a solution by yourself, search in google, push commits, talking without doing nothing its very easy. Don't use xampp

**Comment by fewjative** [comment]
When I run on my local server(xampp), '$result' is empty and then it attempts to use gzdecode(), which would explain the data error.

**Comment by mgp25** [comment]
@fewjative dont use xampp

**Comment by fewjative** [comment]
I know. I have servers at AWS, Linode, and Namecheap(in the process of getting a server set up with vlexo). I'm using xampp because the product I am creating is not something that will ever be put into production and only needs to be usable for the next few days.
