### ISSUE TITLE
Seeing friends who've added you

### ISSUE THREAD

**Issue by ObjectiveTruth** [mgp25/Snap-API#65]
I made a comment on the commit but this might be better,

does `getUnconfirmedFriends()` return those you haven't accepted yet? 

If it is, maybe changing it to getNewFriendRequest might be better, semantically? 
Unconfirmed makes me think they have been confirmed by Snapchat

**Comment by mgp25** [comment]
@ObjectiveTruth oks, ill rename it, but can you check if this function works properly?

**Comment by ObjectiveTruth** [comment]
@mgp25, Thanks!

I keep getting this back when I do `getUnconfirmedFriends()`

```
PHP Notice:  Undefined property: stdClass::$is_shared_story in <DIR>snapchat.php on line 1209
```

Note: I changed the DIR part

But, it does indeed return an array of those with the code FRIEND_UNCONFIRMED (now i see where you got the naming from :ghost:)

**Comment by mgp25** [comment]
@ObjectiveTruth yes :yum: ill update it later.

**Comment by ObjectiveTruth** [comment]
I realized my issue is mute, you can just search for `.addedFriends()`
thanks!

**Comment by emiliobasualdo** [comment]
@mgp25  @ObjectiveTruth  can you confirm 'getUnconfirmedFriends()' work?
