### ISSUE TITLE
Can't login now

### ISSUE THREAD

**Issue by vasilywang** [mgp25/Snap-API#69]
```
Error
{
    logged = 0;
    message = "Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)";
    status = "-103";
}
```

It worked yesterday.

**Comment by vasilywang** [comment]
I can login with my own gmail. I think Snapchat has blocked the email returned from https://tekno.pw/snapchat_password.php

**Comment by teknogeek** [comment]
which email is blocked

**Comment by vasilywang** [comment]
@teknogeek I think you just changed the emails on your server. It's working now.
But I worry Snapchat will disable them again.
The old emails were working for me yesterday.

**Comment by teknogeek** [comment]
yes i did, working on making a bunch more accounts now
