### ISSUE TITLE
401 - Unauthorized (many IP addresses)

### ISSUE THREAD

**Issue by fgambino** [mgp25/Snap-API#70]
Hi, I'm getting a 401 when posting to /loq/device_id. Normally this would indicate an IP address ban, but I wanted to get your thoughts on it:

I was using an older version of the API (my own code) a few hours ago, and it was setting stories using my auth-token that I've had for about 2 months. I tried logging into another account, but it seems that they now require you to update the app to create new sessions. I didn't feel like reversing the new auth method, so I stumbled upon your library (great work by the way). All of my requests were routed through a VPN which changes the IP address every time I connect to it. Snapchat returns a 401 using your library, but the same IP addresses were working a few hours ago using the old API. Either they have a separate banned IP list for clients connecting to the new API or it was simply a coincidence?

I've tried connecting with 10+ IP addresses, and they all don't work.

Does this have anything to do with the Google authentication that they added?

Thanks guys.

Debug output:

```
REQUEST TO: https://feelinsonice-hrd.appspot.com/loq/device_id

Sent Request info: POST /loq/device_id HTTP/1.1
User-Agent: Snapchat/9.3.1.0 (HTC One; Android 4.4.2#302626.7#19; gzip
Host: feelinsonice-hrd.appspot.com
Accept: */*
Accept-Language: en
Accept-Locale: en_US
Content-Length: 98
Content-Type: application/x-www-form-urlencoded


DATA: timestamp=1428362053031&req_token=930706578f71cba86eae11ebfcafa27433e04d86195bba8429b49214dec51f8b
RESULT: <html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>401 UNAUTHORIZED</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: UNAUTHORIZED</h1>
</body></html>
```

**Comment by ghost** [comment]
I'm getting the same error.

**Comment by GarrettBlackmon** [comment]
I've been getting this for a long time. I was using IPV6 as suggested by @Spurlex on a digital ocean droplet but after one day I started getting this error. I tried making a clone of the droplet with a different IP but no cigar.

**Comment by Mxchael** [comment]
@Cheater912 What host are you using. Test it locally on an IP you know wont be banned. 

Hosts like DigitalOcean have majority of there IP's banned. Im pretty sure most if not all there current IPV4 IP's are banned along with some of there IPV6's.

**Comment by fgambino** [comment]
It's going through a VPN. Don't want to mention the name just in case they
look here. The VPN company has over 100,000 addresses around the world, so
I doubt they blocked all of them during the time I switched libs.

**Comment by Mxchael** [comment]
Have you tried changing https://github.com/mgp25/Snap-API/blob/master/src/snapchat.php#L195 to one of the emails from https://tekno.pw/snapchat_password.php

**Comment by fgambino** [comment]
Since it's failing on getDeviceToken() I don't think getAuthToken() is even being executed. All of that comes after the device token, no?

Thanks for the fast reply

**Comment by mgp25** [comment]
@Cheater912 your host/server its blocked. You can set a proxy doing this: 
https://github.com/mgp25/Snap-API/wiki/Snap-API-Documentation#setting-a-proxy

Regards

**Comment by ghost** [comment]
@mgp25 so `getDeviceToken()` still works for you? I highly doubt they blocked my ips, I tried a few different ones, even my mobile connection. The official app still works. Does that mean they only block 3rd party ones?

**Comment by mgp25** [comment]
@rpw98 yes.

**Comment by ghost** [comment]
Sorry, yes means it still works for you or they only block 3rd party apps? :P

**Comment by mgp25** [comment]
It works for everyone, Snapchat only blocked your IP because of using third party apps, use auth and remain logged in, thats it.

**Comment by ghost** [comment]
I know using auth still likely works. Problem for me is I logged in from the official app, so the auth needs to be updated. Then I can't login any more from the script. I just want to confirm if this is an ip issue or code issue. Are you still able to `getDeviceToken()`? I just want to confirm. Thanks.

**Comment by mgp25** [comment]
@rpw98 sniff your auth from you device so you can use it in your device and it the API at the same time, think easy.

**Comment by ghost** [comment]
So login() will not work then?
