### ISSUE TITLE
Private group chat?

### ISSUE THREAD

**Issue by hako** [mgp25/Snap-API#72]
I was thinking about creating a private [Gitter](https://gitter.im) or [Slack](https://slack.com) chat for this repo.

A similar group chat that was started at JorgenPhi/php-snapchat#89 using Skype but I have no idea what's going on there.

Feel free to voice your opinions on this if you're interested.

**Comment by Mxchael** [comment]
We have a group chat on Skype that we have been using for this API. Its pretty active and probably easier to just add people into that.

If people wanna be added they can post there usernames and i'll add them in.

**Comment by hako** [comment]
Alright, here's my username: fly3r

**Comment by mgp25** [comment]
I recommend doing a public chat instead of a skype group

**Comment by kristjanmik** [comment]
Could you add me as well? Mine is kristjanmik

**Comment by mgp25** [comment]
We are using this chat --> https://gitter.im/mgp25/Snap-API

Regards

**Comment by JohnRipper** [comment]
add me on skype john_ripper5150

**Comment by mgp25** [comment]
Use the gitter chat: https://gitter.im/mgp25/Snap-API

Regards
