### ISSUE TITLE
Example script

### ISSUE THREAD

**Issue by jkaberg** [mgp25/Snap-API#73]
Could you guys show me a code snippet on how to post snap's directly to story? Or perhaps it isn't possible?

**Comment by sallaben** [comment]
$snapchat->setStory(pathtoimage, durationinseconds) if I recall correctly.

Check out exampleFunctional.php.

**Comment by mgp25** [comment]
@jkaberg read wiki: https://github.com/mgp25/Snap-API/wiki

And check examples in `/example` folder

**Comment by jkaberg** [comment]
Yeah I saw thoes, so I need to download the images and then scan "a" folder for images and upload to story? 

Was hopeing for something simpler, like this python code :smile: 

> from SnapWrap import Snapchat
> 
> class CustomBot(Snapchat):
>    def on_snap(self, snap):
>        self.post_story(snap)
> 
> bot = CustomBot(*["username", "password"])
> bot.begin()

on_snap() is an event listner, and post_story() posts a snap object to story

But I'll give that a shot

**Comment by mgp25** [comment]
@jkaberg simpler than this?

``` php
$username = ""; // Your snapchat username
$password = ""; // Your snapchat password
$debug = false; // Set this to true if you want to see all outgoing requests and responses from server

$snapchat = new Snapchat($username, $debug);
$snapchat->login($password);

$imagePath = ""; // URL or local path to a media file (image or video)
$snapchat->setStory($imagePath, $time, $text);
```

Maybe you need to get used to php first.

**Comment by jkaberg** [comment]
@mgp25 Still need to save it localy, and then re-transmit upstream. Anyhow not a big problem, was just wondering if there was an similar function in your lib as to what the python code in my previous post was doing

**Comment by mgp25** [comment]
@jkaberg you dont need to store anything.

``` php
$imagePath = ""; // URL or local path to a media file (image or video)
```

URL means internet link, you can set that var to `http://whatever.src/myimge.jpg`

**Comment by jkaberg** [comment]
Yeah I get that, what I'am trying to do is create a bot that receives snaps from friends and posts thoes snaps on the bot's story

But I think we're done here, I got my awnser. Thanks for your time

**Comment by mgp25** [comment]
@jkaberg 

you can do this:

``` php
$snapsData = $snapchat->getSnaps();
```

And from there just take every snap and send it :)

**Comment by sallaben** [comment]
Joel:

Check out http://www.github.com/sallaben/storybot

**Comment by jkaberg** [comment]
@mgp25 

Is this what you mean? I'm new to php so..

> $snapchat = new Snapchat($username, $gEmail, $gPasswd, $debug);
> $snapchat->login($password);
> 
> $snaps = $snapchat->getSnaps(true);
> 
> if (!is_null($snaps))
> {
>  foreach($snaps as $snap)
>      $snapchat->setStory($snap);
> }
> 
> $snapchat->closeAppEvent();

Kinda awnsering my own question, seems it's not possible? 

> PHP Warning:  finfo_file() expects parameter 2 to be string, object given in /opt/Snap-API/src/snapchat.php on line 2179
> PHP Warning:  file_get_contents() expects parameter 1 to be a valid path, object given in /opt/Snap-API/src/snapchat.php on line 2196
> PHP Notice:  Undefined variable: type in /opt/Snap-API/src/snapchat.php on line 2226

It expects an file path where I'm giving an object
