### ISSUE TITLE
Can I automatically accept new friends somehow?

### ISSUE THREAD

**Issue by flyize** [mgp25/Snap-API#80]
Is there a way for me to list waiting friend requests and auto-accept them?

**Comment by flyize** [comment]
i think this is just a case of me not understanding Snapchat.  Nevermind.

**Comment by sallaben** [comment]
I mean it IS possible....still wanna know how?

**Comment by flyize** [comment]
Sure!

**Comment by sallaben** [comment]
Make a bot that gets current array of friends and saves it. Then at some
interval using a cron job get the list of friends and compare to the saved
list. If the script finds any accounts that are not in the saved list, it
should call addFriend( for each account. Then save the newest friend list
array and check again at an interval.

**Comment by emiliobasualdo** [comment]
Has anybody already done this?
if so , mind posting the code?
@sallaben  ??
