### ISSUE TITLE
Login failed, same issue as #23

### ISSUE THREAD

**Issue by TerrorFactor** [mgp25/Snap-API#85]
Hi,

I have the same issue as #23. Temporary fail of login. I tried again after resetting my ip, but same issue. 
It's running from ubuntu, without using the webserver `php examplefile.php`

**Comment by mgp25** [comment]
Use this:

``` php
$snapchat = new Snapchat($username, $debug);
$snapchat->setGmailData($gEmail, $gPasswd);

$snapchat->login($password);
```

where `$gEmail` and  `$gPasswd` are your data of a gmail account. That will solve your issue.

Regards

**Comment by TerrorFactor** [comment]
Seems to work now, awesome! 
Thanks for the fast response by the way :)

**Comment by ArneKnockaert** [comment]
I don't know if I may post here, but i have this problem on my phone with any account

**Comment by EricZeiberg** [comment]
Did you use the correct logins for both gmail and Snapchat?

**Comment by mgp25** [comment]
@ArneKnockaert download latest code and see wiki for more information. Its working 100%

Regards

**Comment by Boy300** [comment]
@mgp25 please what's your email let me send my account details please help me my login as temporarily failed on snapchat for the past 6 days can't login into my snapchat.
