### ISSUE TITLE
UNAUTHORIZED (issue 21) after a few goes, workaround?

### ISSUE THREAD

**Issue by TerrorFactor** [mgp25/Snap-API#86]
Same problem as in issue 21:
It seems that you get kicked of the server after a few times.
I tried to reset the IP, but that didn't help. Using another account does work however.
The account that gets unauthorized, works fine on snapchat. It seems that the middleman-website is blocking it for some reason.
I tried ~10 times, each time getting friends/snaps (5 or so), send a snap and post a few snaps to the storyline. 
Is there a solution/workaround for this, without resorting to multiple snapchat accounts?

**Comment by mgp25** [comment]
@TerrorFactor Does the src folder write permissions? You should have a file called `auth-<username>.dat`, look for it.

You can also set a proxy: https://github.com/mgp25/Snap-API/wiki/Snap-API-Documentation#setting-a-proxy

Or use IPv6.

Regards

**Comment by TerrorFactor** [comment]
Hi mgp25, 

src has write permissions (project folder is in my home dir). The auth.dat files are also there. 
I'm not sure how ipv6 or a proxy would help, as it seems to be unrelated to my ip?

Best regards

**Comment by mgp25** [comment]
@TerrorFactor check here: https://gitter.im/mgp25/Snap-API there you can chat with other users, i think some of them found a fix.

Once you got the fix, post it here and close the issue.

Regards

**Comment by TerrorFactor** [comment]
Seems it was a user error. I tried the account with the script, and checked with my phone, causing the .dat file to be invalid. 
Deleting the .dat, so that it would log in normally and recreate it, worked. 
My apologies!
