### ISSUE TITLE
New login issue

### ISSUE THREAD

**Issue by ghost** [mgp25/Snap-API#93]
One of my account is having problem logging in. It returns this error message: `You are using an older version of Snapchat. Please update to the latest version to log in :)`

Other accounts are fine. I think the reason is I logged in from the latest official snapchat app using that account. Then all of sudden I can't log in with that account using the script anymore. Always give me that error.

Logged in from the official snapchat app with another account, and that account starts to get the same error. Is snapchat coming up with some new trick?

**Comment by rpw98** [comment]
Logged in from the official snapchat app with another account, and that account starts to get the same error. Is snapchat coming up with some new trick?

**Comment by ferdau** [comment]
On one account I also got a warning + one with 3rd party warning. On my android vm there was a new update of the snapchat app, so maybe the update is still rolling out.

This occasionally happens when Snapchat thinks you should have received the update already but your device hasn't there is like a gap between: receiving and really updating. Headers will probably need an update.

**Comment by ghost** [comment]
I tried to update the user-agent to 9.6.0.0 which is the latest version, then I get "login temparily failed" error.

**Comment by sallaben** [comment]
Try sending a request thru a middleman proxy and analyzing exactly what
user agent it uses now.

**Comment by ghost** [comment]
@ferdau This time is a little different I think. Before I was able to log in from official snapchat app and this  script before. But now once I logged in from the official app, I can't log in with script anymore. :-(

**Comment by mgp25** [comment]
Til we update the new login mechanish. I recommend you doing this:

Use a proxy and sniff your `auth_token`, go to `/src` folder and create a file called `auth-<username>.dat` and place your token there.

Regards

**Comment by EricZeiberg** [comment]
How often does Snapchat change their login API? Seems like they do it pretty much every update.....

**Comment by mgp25** [comment]
Yes, mostly because of us

**Comment by teknogeek** [comment]
yep, we're the main reason they do it

**Comment by EricZeiberg** [comment]
We must continue to fight the oppression! Resist the Snapchat foes!

**Comment by teknogeek** [comment]
lol yea they keep trying but I have yet to see anything that's stopped us for any period of time (that is, soley using the API) besides the latest attestation check. even that doesn't really count because the attestation is Google's code, not Snapchat's.

**Comment by teknogeek** [comment]
and it will be broken by me and @mgp25 within a week or 2 if things go as planned

**Comment by KyleBoyer** [comment]
@MasterEjay @rpw98 I actually fixed this today :)
